package it.vintedaffari.app;
import org.junit.Test;
import static org.junit.Assert.*;
public final class VintedBrowserPolicyTest {
 @Test public void exactHttpsOriginsOnly(){for(String u:new String[]{"https://www.vinted.it/catalog","https://vinted.it/items/123","https://www.vinted.it:443/member/7"})assertTrue(u,VintedBrowserPolicy.allowedPage(u));for(String u:new String[]{null,"http://www.vinted.it/items/1","file:///items/1","content://x","javascript:alert(1)","intent://x","https://www.vinted.it.evil.com/items/1","https://evil.com/items/1","https://user@www.vinted.it/items/1","https://www.vinted.it:444/items/1","https://www.vinted.it\\@evil.com/","https://www.vinted.it/login","https://www.vinted.it/inbox"})assertFalse(String.valueOf(u),VintedBrowserPolicy.allowedPage(u));}
 @Test public void bridgeRequiresMainFrameOriginAndBoundedBytes(){assertTrue(VintedBrowserPolicy.allowedMessage("https://www.vinted.it",true,1));assertTrue(VintedBrowserPolicy.allowedMessage("https://vinted.it",true,131072));assertFalse(VintedBrowserPolicy.allowedMessage("https://www.vinted.it",false,10));assertFalse(VintedBrowserPolicy.allowedMessage("https://evil.com",true,10));assertFalse(VintedBrowserPolicy.allowedMessage("https://www.vinted.it/catalog",true,10));assertFalse(VintedBrowserPolicy.allowedMessage("https://www.vinted.it",true,131073));assertFalse(VintedBrowserPolicy.allowedMessage("https://www.vinted.it",true,0));}
 @Test public void itemUrlAndIdMustAgree(){assertTrue(VintedBrowserPolicy.matchesItem("https://www.vinted.it/items/123-catan","123"));assertFalse(VintedBrowserPolicy.matchesItem("https://www.vinted.it/items/124-catan","123"));assertFalse(VintedBrowserPolicy.matchesItem("https://www.vinted.it/items/123abc","123"));assertFalse(VintedBrowserPolicy.matchesItem("https://evil.com/items/123","123"));assertFalse(VintedBrowserPolicy.matchesItem("https://www.vinted.it/items/123","0"));}
 @Test public void entryModesFailClosed(){assertTrue(VintedBrowserPolicy.startsEnabled("SEARCH"));assertTrue(VintedBrowserPolicy.startsEnabled("BUNDLE"));assertFalse(VintedBrowserPolicy.startsEnabled("VIEW"));assertFalse(VintedBrowserPolicy.startsEnabled(null));assertFalse(VintedBrowserPolicy.startsEnabled("unexpected"));}
}
