package it.vintedaffari.app;
import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;
import java.util.*;
/** Short atomic writes on the existing helper. No WebView/network invocation inside transactions. */
public final class BrowserCaptureStore {
 public static final String JOB_TYPE="BROWSER_ANALYSIS";
 private final DealDatabase helper;
 public BrowserCaptureStore(DealDatabase helper){this.helper=helper;}
 public static final class CommitReceipt {public int confirmedIds,updatedIds,incompleteIds;}
 public static final class Claim {public long jobId,revision,leaseStartedAt;public String itemId;public BrowserCandidate candidate;}
 public static final class Row {public BrowserCandidate candidate;public String state,reason;public long revision,listingId;}
 public static final class Snapshot {public long captureId,startedAt,updatedAt;public String url,state;public final List<Row> rows=new ArrayList<>();}
 public long beginCapture(String url,long now){if(!VintedBrowserPolicy.allowedPage(url))throw new IllegalArgumentException("Pagina non consentita");ContentValues v=new ContentValues();v.put("url",url);v.put("started_at",now);v.put("updated_at",now);v.put("state","CAPTURING");return helper.getWritableDatabase().insertOrThrow("browser_captures",null,v);}
 public void finishCapture(long id,String state,long now){ContentValues v=new ContentValues();v.put("state",state);v.put("updated_at",now);helper.getWritableDatabase().update("browser_captures",v,"id=?",new String[]{String.valueOf(id)});}
 private static String key(String id){return "browser_analysis:"+id;}
 public CommitReceipt commit(long captureId,int page,List<BrowserCandidate> candidates,long now){
  if(captureId<=0||page<1||page>10||candidates.size()>32)throw new IllegalArgumentException("Pacchetto non valido");
  SQLiteDatabase db=helper.getWritableDatabase();CommitReceipt receipt=new CommitReceipt();db.beginTransaction();
  try{
   try(Cursor c=db.rawQuery("SELECT 1 FROM browser_captures WHERE id=?",new String[]{String.valueOf(captureId)})){if(!c.moveToFirst())throw new IllegalStateException("Ricerca assente");}
   Set<String> packetIds=new HashSet<>();
   for(BrowserCandidate incoming:candidates){if(!packetIds.add(incoming.itemId))continue;Row existing=readRow(db,incoming.itemId);BrowserCandidate merged=existing==null?incoming:existing.candidate.merge(incoming);boolean changed=existing==null||!merged.revisionKey().equals(existing.candidate.revisionKey());long revision=existing==null?1:existing.revision+(changed?1:0);String state=existing==null||changed?(merged.elaborable()?"QUEUED":"INCOMPLETE"):existing.state;
    ContentValues v=new ContentValues();v.put("item_id",merged.itemId);v.put("url",merged.url);v.put("title",merged.title);nullable(v,"price_cents",merged.priceCents);nullable(v,"protected_price_cents",merged.protectedPriceCents);String payload=encode(merged);v.put("payload",payload);v.put("content_key",merged.revisionKey());v.put("revision",revision);v.put("observed_at",merged.observedAt);v.put("state",state);if(changed){v.put("reason",merged.elaborable()?"":merged.title.isEmpty()?"Titolo non leggibile":"Prezzo articolo non leggibile");v.put("lease_started_at",0);v.put("claimed_revision",0);}
    if(existing==null)db.insertOrThrow("browser_candidates",null,v);else db.update("browser_candidates",v,"item_id=?",new String[]{merged.itemId});
    db.execSQL(BrowserCaptureSql.UPSERT_MEMBERSHIP,new Object[]{captureId,merged.itemId,page,now,now,revision,payload});db.execSQL(BrowserCaptureSql.UPDATE_MEMBERSHIP,new Object[]{page,now,revision,payload,captureId,merged.itemId});
    if(changed&&merged.elaborable())enqueue(db,merged.itemId,now);else if(changed){ContentValues j=new ContentValues();j.put("state",MarketStore.COMPLETE);j.put("updated_at",now);j.put("processing_started_at",0);db.update("processing_jobs",j,"job_key=?",new String[]{key(merged.itemId)});}
    receipt.confirmedIds++;if(existing!=null&&changed)receipt.updatedIds++;if(!merged.elaborable())receipt.incompleteIds++;
   }
   ContentValues capture=new ContentValues();capture.put("updated_at",now);db.update("browser_captures",capture,"id=?",new String[]{String.valueOf(captureId)});db.setTransactionSuccessful();return receipt;
  }finally{db.endTransaction();}
 }
 private void enqueue(SQLiteDatabase db,String id,long now){ContentValues v=new ContentValues();v.put("job_key",key(id));v.put("job_type",JOB_TYPE);v.put("state",MarketStore.PENDING);v.put("created_at",now);v.put("updated_at",now);v.put("next_attempt_at",0);v.put("source","BROWSER_CAPTURE");v.put("priority",250);db.insertWithOnConflict("processing_jobs",null,v,SQLiteDatabase.CONFLICT_IGNORE);v.remove("created_at");v.put("processing_started_at",0);v.put("progress",0);v.put("attempt",0);v.put("last_error","");db.update("processing_jobs",v,"job_key=?",new String[]{key(id)});}
 public List<Claim> claim(int limit,long now){SQLiteDatabase db=helper.getWritableDatabase();List<Claim> out=new ArrayList<>();db.beginTransaction();try{
  long stale=now-15L*60_000L;
  db.execSQL("UPDATE processing_jobs SET state='PENDING',processing_started_at=0,updated_at=? WHERE job_type=? AND state='PROCESSING' AND processing_started_at<?",new Object[]{now,JOB_TYPE,stale});
  db.execSQL("UPDATE browser_candidates SET state='QUEUED',lease_started_at=0,claimed_revision=0 WHERE state='ANALYZING' AND lease_started_at<?",new Object[]{stale});
  try(Cursor c=db.rawQuery("SELECT j.id,b.item_id,b.revision FROM processing_jobs j JOIN browser_candidates b ON j.job_key='browser_analysis:'||b.item_id WHERE j.job_type=? AND j.state IN ('PENDING','FAILED_RETRYABLE') AND j.next_attempt_at<=? AND b.state IN ('QUEUED','TECHNICAL_ERROR') AND b.price_cents IS NOT NULL AND b.title<>'' ORDER BY j.created_at,j.id LIMIT ?",new String[]{JOB_TYPE,String.valueOf(now),String.valueOf(Math.max(1,Math.min(8,limit)))})){while(c.moveToNext()){Claim claim=new Claim();claim.jobId=c.getLong(0);claim.itemId=c.getString(1);claim.revision=c.getLong(2);claim.leaseStartedAt=now;out.add(claim);}}
  for(Claim claim:out){ContentValues v=new ContentValues();v.put("state",MarketStore.PROCESSING);v.put("processing_started_at",now);v.put("updated_at",now);db.update("processing_jobs",v,"id=?",new String[]{String.valueOf(claim.jobId)});v.clear();v.put("state","ANALYZING");v.put("lease_started_at",now);v.put("claimed_revision",claim.revision);db.update("browser_candidates",v,"item_id=?",new String[]{claim.itemId});claim.candidate=readRow(db,claim.itemId).candidate;}
  db.setTransactionSuccessful();return out;
 }finally{db.endTransaction();}}
 public boolean isCurrent(SQLiteDatabase db,Claim claim){try(Cursor c=db.rawQuery("SELECT 1 FROM browser_candidates WHERE item_id=? AND revision=? AND claimed_revision=? AND lease_started_at=? AND state='ANALYZING'",new String[]{claim.itemId,String.valueOf(claim.revision),String.valueOf(claim.revision),String.valueOf(claim.leaseStartedAt)})){return c.moveToFirst();}}
 public boolean complete(Claim claim,String outcome,String reason,long now){SQLiteDatabase db=helper.getWritableDatabase();db.beginTransaction();try{boolean done=complete(db,claim,outcome,reason,now);db.setTransactionSuccessful();return done;}finally{db.endTransaction();}}
 boolean complete(SQLiteDatabase db,Claim claim,String outcome,String reason,long now){if(!isCurrent(db,claim))return false;db.execSQL(BrowserCaptureSql.COMPLETE_CURRENT,new Object[]{outcome,reason,claim.revision,now,claim.itemId,claim.revision,claim.leaseStartedAt});ContentValues v=new ContentValues();v.put("state",MarketStore.COMPLETE);v.put("updated_at",now);v.put("processing_started_at",0);v.put("progress",100);v.put("last_error","");db.update("processing_jobs",v,"id=? AND processing_started_at=?",new String[]{String.valueOf(claim.jobId),String.valueOf(claim.leaseStartedAt)});return true;}
 public void fail(Claim claim,String reason,long retryAt){SQLiteDatabase db=helper.getWritableDatabase();db.beginTransaction();try{if(isCurrent(db,claim)){ContentValues v=new ContentValues();v.put("state","TECHNICAL_ERROR");v.put("reason",reason);v.put("lease_started_at",0);v.put("claimed_revision",0);db.update("browser_candidates",v,"item_id=?",new String[]{claim.itemId});v.clear();v.put("state",MarketStore.FAILED_RETRYABLE);v.put("last_error",reason);v.put("next_attempt_at",retryAt);v.put("processing_started_at",0);v.put("updated_at",System.currentTimeMillis());db.update("processing_jobs",v,"id=? AND processing_started_at=?",new String[]{String.valueOf(claim.jobId),String.valueOf(claim.leaseStartedAt)});}db.setTransactionSuccessful();}finally{db.endTransaction();}}
 public int activeJobs(){try(Cursor c=helper.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM processing_jobs WHERE job_type=? AND state IN ('PENDING','PROCESSING','FAILED_RETRYABLE')",new String[]{JOB_TYPE})){return c.moveToFirst()?c.getInt(0):0;}}
 public Snapshot snapshot(long id){SQLiteDatabase db=helper.getReadableDatabase();Snapshot snapshot=new Snapshot();snapshot.captureId=id;try(Cursor c=db.rawQuery("SELECT url,started_at,updated_at,state FROM browser_captures WHERE id=?",new String[]{String.valueOf(id)})){if(!c.moveToFirst())return snapshot;snapshot.url=c.getString(0);snapshot.startedAt=c.getLong(1);snapshot.updatedAt=c.getLong(2);snapshot.state=c.getString(3);}try(Cursor c=db.rawQuery("SELECT b.item_id,b.payload,b.state,b.reason,b.revision,COALESCE(b.listing_id,0) FROM browser_capture_items m JOIN browser_candidates b ON b.item_id=m.item_id WHERE m.capture_id=? ORDER BY m.first_observed_at,m.item_id",new String[]{String.valueOf(id)})){while(c.moveToNext())snapshot.rows.add(row(c));}return snapshot;}
 public List<Snapshot> listCaptures(int limit){List<Long> ids=new ArrayList<>();try(Cursor c=helper.getReadableDatabase().rawQuery("SELECT id FROM browser_captures ORDER BY started_at DESC,id DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,Math.min(50,limit)))})){while(c.moveToNext())ids.add(c.getLong(0));}List<Snapshot> out=new ArrayList<>();for(long id:ids)out.add(snapshot(id));return out;}
 static Row readRow(SQLiteDatabase db,String id){try(Cursor c=db.rawQuery("SELECT item_id,payload,state,reason,revision,COALESCE(listing_id,0) FROM browser_candidates WHERE item_id=?",new String[]{id})){return c.moveToFirst()?row(c):null;}}
 private static Row row(Cursor c){Row row=new Row();row.candidate=decode(c.getString(1));row.state=c.getString(2);row.reason=c.getString(3);row.revision=c.getLong(4);row.listingId=c.getLong(5);return row;}
 static String encode(BrowserCandidate c){try{JSONObject j=new JSONObject();j.put("id",c.itemId).put("url",c.url).put("title",c.title).put("price",c.priceCents==null?JSONObject.NULL:c.priceCents).put("protected",c.protectedPriceCents==null?JSONObject.NULL:c.protectedPriceCents).put("metadata",new JSONObject(c.metadata)).put("sources",new JSONObject(c.provenance)).put("observedAt",c.observedAt).put("fieldObservedAt",new JSONObject(c.fieldObservedAt));return j.toString();}catch(org.json.JSONException e){throw new IllegalArgumentException(e);}}
 static BrowserCandidate decode(String payload){try{JSONObject j=new JSONObject(payload);return new BrowserCandidate(j.getString("id"),j.getString("url"),j.optString("title"),j.isNull("price")?null:j.getInt("price"),j.isNull("protected")?null:j.getInt("protected"),strings(j.optJSONObject("metadata")),strings(j.optJSONObject("sources")),j.getLong("observedAt"),longs(j.optJSONObject("fieldObservedAt")));}catch(org.json.JSONException e){throw new IllegalStateException("Candidato non leggibile",e);}}
 private static Map<String,Long> longs(JSONObject j){if(j==null)return null;Map<String,Long> out=new TreeMap<>();Iterator<String> keys=j.keys();while(keys.hasNext()){String key=keys.next();out.put(key,j.optLong(key));}return out;}
 private static Map<String,String> strings(JSONObject j){Map<String,String> out=new TreeMap<>();if(j!=null){Iterator<String> keys=j.keys();while(keys.hasNext()){String key=keys.next();if(!j.isNull(key))out.put(key,j.optString(key));}}return out;}
 private static void nullable(ContentValues v,String key,Integer value){if(value==null)v.putNull(key);else v.put(key,value);}
}
