package it.vintedaffari.app;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.*;

/** Persistent bundle pipeline state, diagnostics and seller caches. */
public final class BundleDatabase extends SQLiteOpenHelper {
    private static final String N="ludo_bundles.db";
    private static final int V=4;
    public static final String[] STATUSES={
            "SELLER_UNKNOWN","SELLER_FOUND","SNAPSHOT_FOUND","SNAPSHOT_EMPTY",
            "DEEP_SCAN_QUEUED","DEEP_SCAN_RUNNING","NO_BOARDGAMES","BUNDLE_CANDIDATE",
            "BUNDLE_READY","RATE_LIMITED","ERROR"
    };
    public static final class Diagnostic {public String sourceSignature,sellerId,status,lastError;public int catalogCount,matchCount,publishedCount;public long updatedAt;}
    public BundleDatabase(Context c){super(c,N,null,V);}

    @Override public void onCreate(SQLiteDatabase db){
        db.execSQL("CREATE TABLE bundle_suggestions(id INTEGER PRIMARY KEY AUTOINCREMENT,source_signature TEXT,seller_id TEXT,item_id TEXT,item_url TEXT,title TEXT,bgg_id TEXT,game_name TEXT,rating REAL,quality_score INTEGER,item_price_cents INTEGER,benchmark_cents INTEGER,estimated_bundle_total_cents INTEGER,saving_pct INTEGER,language_code TEXT,image_url TEXT,scanned_at INTEGER,UNIQUE(source_signature,item_id))");
        db.execSQL("CREATE INDEX idx_bundle_source ON bundle_suggestions(source_signature,saving_pct DESC)");
        createDiagnostics(db);createSellerCache(db);createSnapshotCache(db);createCounters(db);
    }
    private static void createDiagnostics(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS bundle_diagnostics(source_signature TEXT PRIMARY KEY,seller_id TEXT,status TEXT NOT NULL,catalog_count INTEGER NOT NULL DEFAULT 0,match_count INTEGER NOT NULL DEFAULT 0,published_count INTEGER NOT NULL DEFAULT 0,last_error TEXT,updated_at INTEGER NOT NULL)");}
    private static void createSellerCache(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS seller_catalog_cache(seller_id TEXT PRIMARY KEY,items_json TEXT NOT NULL,fetched_at INTEGER NOT NULL,http_code INTEGER NOT NULL DEFAULT 200)");}
    private static void createSnapshotCache(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS seller_snapshot_cache(seller_id TEXT PRIMARY KEY,source_item_id TEXT,source_kind TEXT,items_json TEXT NOT NULL,fetched_at INTEGER NOT NULL)");}
    private static void createCounters(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS bundle_counters(metric TEXT PRIMARY KEY,value INTEGER NOT NULL DEFAULT 0)");}
    @Override public void onUpgrade(SQLiteDatabase db,int o,int n){if(o<2)createDiagnostics(db);if(o<3)createSellerCache(db);if(o<4){createSnapshotCache(db);createCounters(db);}}

    public synchronized void replace(String source,String seller,List<BundleSuggestion> rows){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{db.delete("bundle_suggestions","source_signature=?",new String[]{source});for(BundleSuggestion r:rows){ContentValues v=new ContentValues();v.put("source_signature",source);v.put("seller_id",seller);v.put("item_id",r.itemId);v.put("item_url",r.itemUrl);v.put("title",r.title);v.put("bgg_id",r.bggId);v.put("game_name",r.gameName);if(r.rating!=null)v.put("rating",r.rating);if(r.qualityScore!=null)v.put("quality_score",r.qualityScore);if(r.itemPriceCents!=null)v.put("item_price_cents",r.itemPriceCents);if(r.benchmarkCents!=null)v.put("benchmark_cents",r.benchmarkCents);if(r.estimatedBundleTotalCents!=null)v.put("estimated_bundle_total_cents",r.estimatedBundleTotalCents);if(r.savingPct!=null)v.put("saving_pct",r.savingPct);v.put("language_code",r.languageCode);v.put("image_url",r.imageUrl);v.put("scanned_at",System.currentTimeMillis());db.insertWithOnConflict("bundle_suggestions",null,v,SQLiteDatabase.CONFLICT_REPLACE);}db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public synchronized List<BundleSuggestion> forSource(String source,int limit){List<BundleSuggestion>o=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,source_signature,seller_id,item_id,item_url,title,bgg_id,game_name,rating,quality_score,item_price_cents,benchmark_cents,estimated_bundle_total_cents,saving_pct,language_code,image_url,scanned_at FROM bundle_suggestions WHERE source_signature=? ORDER BY COALESCE(saving_pct,-999) DESC,COALESCE(quality_score,0) DESC LIMIT ?",new String[]{source,String.valueOf(Math.max(1,limit))});while(c.moveToNext()){BundleSuggestion r=new BundleSuggestion();int i=0;r.id=c.getLong(i++);r.sourceSignature=c.getString(i++);r.sellerId=c.getString(i++);r.itemId=c.getString(i++);r.itemUrl=c.getString(i++);r.title=c.getString(i++);r.bggId=c.getString(i++);r.gameName=c.getString(i++);r.rating=c.isNull(i)?null:c.getDouble(i);i++;r.qualityScore=c.isNull(i)?null:c.getInt(i);i++;r.itemPriceCents=c.isNull(i)?null:c.getInt(i);i++;r.benchmarkCents=c.isNull(i)?null:c.getInt(i);i++;r.estimatedBundleTotalCents=c.isNull(i)?null:c.getInt(i);i++;r.savingPct=c.isNull(i)?null:c.getInt(i);i++;r.languageCode=c.getString(i++);r.imageUrl=c.getString(i++);r.scannedAt=c.getLong(i);o.add(r);}c.close();return o;}
    public synchronized int countForSource(String s){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM bundle_suggestions WHERE source_signature=?",new String[]{s});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}

    public synchronized void setDiagnostic(String source,String seller,String status,int catalog,int matches,int published,String error){if(source==null||source.isEmpty())return;ContentValues v=new ContentValues();v.put("source_signature",source);if(seller!=null)v.put("seller_id",seller);v.put("status",normalizeStatus(status));v.put("catalog_count",Math.max(0,catalog));v.put("match_count",Math.max(0,matches));v.put("published_count",Math.max(0,published));if(error==null)v.putNull("last_error");else v.put("last_error",error);v.put("updated_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("bundle_diagnostics",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    private static String normalizeStatus(String s){if(s==null)return"ERROR";for(String allowed:STATUSES)if(allowed.equals(s))return s;if("NO_SELLER".equals(s))return"SELLER_UNKNOWN";if("NO_CATALOG".equals(s))return"SNAPSHOT_EMPTY";if("NO_MATCH".equals(s))return"NO_BOARDGAMES";return"ERROR";}
    public synchronized String diagnosticStatus(String source){Cursor c=getReadableDatabase().rawQuery("SELECT status FROM bundle_diagnostics WHERE source_signature=?",new String[]{source==null?"":source});String status=c.moveToFirst()?normalizeStatus(c.getString(0)):"SELLER_UNKNOWN";c.close();return status;}
    public synchronized List<Diagnostic> recentDiagnostics(int limit){List<Diagnostic> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT source_signature,seller_id,status,catalog_count,match_count,published_count,last_error,updated_at FROM bundle_diagnostics ORDER BY updated_at DESC LIMIT ?",new String[]{String.valueOf(Math.max(1,limit))});while(c.moveToNext()){Diagnostic d=new Diagnostic();d.sourceSignature=c.getString(0);d.sellerId=c.getString(1);d.status=normalizeStatus(c.getString(2));d.catalogCount=c.getInt(3);d.matchCount=c.getInt(4);d.publishedCount=c.getInt(5);d.lastError=c.getString(6);d.updatedAt=c.getLong(7);out.add(d);}c.close();return out;}
    public synchronized int diagnosticCount(String where){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM bundle_diagnostics WHERE "+where,null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    public synchronized int metricSum(String col){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM("+col+"),0) FROM bundle_diagnostics",null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    public synchronized Map<String,Integer> statusCounts(){Map<String,Integer>m=new LinkedHashMap<>();for(String s:STATUSES)m.put(s,0);Cursor c=getReadableDatabase().rawQuery("SELECT status,COUNT(*) FROM bundle_diagnostics GROUP BY status",null);while(c.moveToNext())m.put(normalizeStatus(c.getString(0)),c.getInt(1));c.close();return m;}
    public synchronized long lastAttemptForSeller(String seller){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(MAX(updated_at),0) FROM bundle_diagnostics WHERE seller_id=?",new String[]{seller==null?"":seller});long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}
    public synchronized int resetRetryableDiagnostics(){
        // Pipeline generation 4 makes the verified local seller graph and the in-app seller rail
        // primary sources. Previous empty/no-match outcomes are inconclusive and must not keep a
        // seller in cooldown after this strategy change.
        return getWritableDatabase().delete("bundle_diagnostics","status IN (?,?,?,?,?,?)",new String[]{"SNAPSHOT_EMPTY","NO_BOARDGAMES","DEEP_SCAN_QUEUED","DEEP_SCAN_RUNNING","RATE_LIMITED","ERROR"});
    }
    public synchronized void resetPipelineCounters(){getWritableDatabase().delete("bundle_counters",null,null);}
    public synchronized int uniqueSellerCount(){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(DISTINCT seller_id) FROM bundle_diagnostics WHERE seller_id IS NOT NULL AND seller_id<>''",null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}

    public synchronized void increment(String metric){increment(metric,1);}
    public synchronized void increment(String metric,int by){if(metric==null||metric.isEmpty()||by==0)return;SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{Cursor c=db.rawQuery("SELECT value FROM bundle_counters WHERE metric=?",new String[]{metric});boolean exists=c.moveToFirst();long current=exists?c.getLong(0):0;c.close();ContentValues v=new ContentValues();v.put("metric",metric);v.put("value",current+by);if(exists)db.update("bundle_counters",v,"metric=?",new String[]{metric});else db.insert("bundle_counters",null,v);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public synchronized long counter(String metric){Cursor c=getReadableDatabase().rawQuery("SELECT value FROM bundle_counters WHERE metric=?",new String[]{metric});long v=c.moveToFirst()?c.getLong(0):0;c.close();return v;}

    public synchronized void storeSnapshot(String seller,String sourceItem,String kind,List<SellerBundleScanner.SellerItem> items){if(seller==null||seller.isEmpty())return;ContentValues v=new ContentValues();v.put("seller_id",seller);v.put("source_item_id",sourceItem);v.put("source_kind",kind==null?"item-page":kind);v.put("items_json",encode(items));v.put("fetched_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("seller_snapshot_cache",null,v,SQLiteDatabase.CONFLICT_REPLACE);increment("snapshotStored");}
    public synchronized boolean hasFreshSnapshot(String seller,long maxAge){Cursor c=getReadableDatabase().rawQuery("SELECT fetched_at FROM seller_snapshot_cache WHERE seller_id=?",new String[]{seller==null?"":seller});boolean hit=c.moveToFirst()&&System.currentTimeMillis()-c.getLong(0)<=maxAge;c.close();if(hit)increment("cacheHitSnapshot");return hit;}
    public synchronized List<SellerBundleScanner.SellerItem> cachedSnapshot(String seller,long maxAge){Cursor c=getReadableDatabase().rawQuery("SELECT items_json,fetched_at FROM seller_snapshot_cache WHERE seller_id=?",new String[]{seller==null?"":seller});List<SellerBundleScanner.SellerItem> out=new ArrayList<>();if(c.moveToFirst()&&System.currentTimeMillis()-c.getLong(1)<=maxAge){out=decode(c.getString(0));}c.close();return out;}
    public synchronized int snapshotCacheCount(){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM seller_snapshot_cache",null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}

    public synchronized void storeSellerCatalog(String seller,List<SellerBundleScanner.SellerItem> items,int code){if(seller==null||seller.isEmpty()||items==null)return;ContentValues v=new ContentValues();v.put("seller_id",seller);v.put("items_json",encode(items));v.put("fetched_at",System.currentTimeMillis());v.put("http_code",code);getWritableDatabase().insertWithOnConflict("seller_catalog_cache",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public synchronized boolean hasFreshSellerCatalog(String seller,long maxAge){Cursor c=getReadableDatabase().rawQuery("SELECT fetched_at FROM seller_catalog_cache WHERE seller_id=?",new String[]{seller==null?"":seller});boolean hit=c.moveToFirst()&&System.currentTimeMillis()-c.getLong(0)<=maxAge;c.close();if(hit)increment("cacheHitCatalog");return hit;}
    public synchronized List<SellerBundleScanner.SellerItem> cachedSellerCatalog(String seller,long maxAge){List<SellerBundleScanner.SellerItem>out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT items_json,fetched_at FROM seller_catalog_cache WHERE seller_id=?",new String[]{seller==null?"":seller});if(c.moveToFirst()&&System.currentTimeMillis()-c.getLong(1)<=maxAge){out=decode(c.getString(0));}c.close();return out;}
    public synchronized int sellerCacheCount(){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM seller_catalog_cache",null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}

    private static String encode(List<SellerBundleScanner.SellerItem> items){JSONArray a=new JSONArray();if(items!=null)for(SellerBundleScanner.SellerItem s:items){JSONObject o=new JSONObject();try{o.put("id",s.id);o.put("title",s.title);o.put("brand",s.brand);o.put("url",s.url);o.put("image",s.imageUrl);o.put("photos",s.photosCsv);o.put("published",s.publishedLabel);o.put("price",s.priceCents);o.put("ownerVerified",s.ownerVerified);o.put("sourceKind",s.sourceKind);a.put(o);}catch(Exception ignored){}}return a.toString();}
    private static List<SellerBundleScanner.SellerItem> decode(String json){List<SellerBundleScanner.SellerItem>out=new ArrayList<>();try{JSONArray a=new JSONArray(json==null?"[]":json);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;SellerBundleScanner.SellerItem s=new SellerBundleScanner.SellerItem();s.id=o.optString("id");s.title=o.optString("title");s.brand=o.optString("brand");s.url=o.optString("url");s.imageUrl=o.optString("image");s.photosCsv=o.optString("photos");s.publishedLabel=o.optString("published");s.priceCents=Math.max(0,o.optInt("price"));s.ownerVerified=o.optBoolean("ownerVerified",false);s.sourceKind=o.optString("sourceKind","");if(!s.id.isEmpty()&&!s.title.isEmpty())out.add(s);}}catch(Exception ignored){}return out;}

    public synchronized void invalidate(DealRecord d){if(d==null)return;getWritableDatabase().delete("bundle_suggestions","source_signature=?",new String[]{d.signature});getWritableDatabase().delete("bundle_diagnostics","source_signature=?",new String[]{d.signature});}
    public synchronized void clearAll(){SQLiteDatabase db=getWritableDatabase();db.delete("bundle_suggestions",null,null);db.delete("bundle_diagnostics",null,null);db.delete("seller_catalog_cache",null,null);db.delete("seller_snapshot_cache",null,null);db.delete("bundle_counters",null,null);}
}
