package it.vintedaffari.app;
import android.content.*;import android.database.*;import android.database.sqlite.*;import java.util.*;
public final class LibraryDatabase extends SQLiteOpenHelper{
    private static final String NAME="vinted_affari_library.db";private static final int VER=8;
    public LibraryDatabase(Context c){super(c,NAME,null,VER);}
    @Override public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE library_games(id INTEGER PRIMARY KEY AUTOINCREMENT,bgg_id TEXT UNIQUE,name TEXT,image_url TEXT,source TEXT,paid_cents INTEGER,shipping_cents INTEGER,rating REAL,weight REAL,playtime INTEGER,acquired_at INTEGER,added_at INTEGER,edition_id TEXT,edition_label TEXT,fee_cents INTEGER,fee_estimated INTEGER NOT NULL DEFAULT 0,bundle_purchase INTEGER NOT NULL DEFAULT 0,bundle_label TEXT,bundle_size INTEGER,geek_rating REAL,bgg_rank INTEGER,voters INTEGER,quality_score INTEGER,min_players INTEGER,max_players INTEGER,categories TEXT,personal_rating INTEGER,bundle_group_id TEXT,bundle_total_cents INTEGER,collection_state TEXT NOT NULL DEFAULT 'owned',sold_reason TEXT,sold_at INTEGER,sale_price_cents INTEGER)");}
    @Override public void onUpgrade(SQLiteDatabase db,int o,int n){
        if(o<2)db.execSQL("ALTER TABLE library_games ADD COLUMN acquired_at INTEGER");
        if(o<3){db.execSQL("ALTER TABLE library_games ADD COLUMN edition_id TEXT");db.execSQL("ALTER TABLE library_games ADD COLUMN edition_label TEXT");db.execSQL("ALTER TABLE library_games ADD COLUMN fee_cents INTEGER");db.execSQL("ALTER TABLE library_games ADD COLUMN fee_estimated INTEGER NOT NULL DEFAULT 0");}
        if(o<4){db.execSQL("ALTER TABLE library_games ADD COLUMN bundle_purchase INTEGER NOT NULL DEFAULT 0");db.execSQL("ALTER TABLE library_games ADD COLUMN bundle_label TEXT");db.execSQL("ALTER TABLE library_games ADD COLUMN bundle_size INTEGER");}
        if(o<5){db.execSQL("ALTER TABLE library_games ADD COLUMN geek_rating REAL");db.execSQL("ALTER TABLE library_games ADD COLUMN bgg_rank INTEGER");db.execSQL("ALTER TABLE library_games ADD COLUMN voters INTEGER");db.execSQL("ALTER TABLE library_games ADD COLUMN quality_score INTEGER");db.execSQL("ALTER TABLE library_games ADD COLUMN min_players INTEGER");db.execSQL("ALTER TABLE library_games ADD COLUMN max_players INTEGER");db.execSQL("ALTER TABLE library_games ADD COLUMN categories TEXT");db.execSQL("ALTER TABLE library_games ADD COLUMN personal_rating INTEGER");}
        if(o<6){db.execSQL("ALTER TABLE library_games ADD COLUMN bundle_group_id TEXT");db.execSQL("ALTER TABLE library_games ADD COLUMN bundle_total_cents INTEGER");}
        if(o<7){db.execSQL("ALTER TABLE library_games ADD COLUMN collection_state TEXT NOT NULL DEFAULT 'owned'");db.execSQL("ALTER TABLE library_games ADD COLUMN sold_reason TEXT");db.execSQL("ALTER TABLE library_games ADD COLUMN sold_at INTEGER");}
        if(o<8)db.execSQL("ALTER TABLE library_games ADD COLUMN sale_price_cents INTEGER");
    }
    private ContentValues gameValues(BggSearchClient.Game g){ContentValues v=new ContentValues();if(g.name!=null)v.put("name",g.name);if(g.imageUrl!=null)v.put("image_url",g.imageUrl);if(g.rating!=null)v.put("rating",g.rating);if(g.geekRating!=null)v.put("geek_rating",g.geekRating);if(g.weight!=null)v.put("weight",g.weight);if(g.playtime!=null)v.put("playtime",g.playtime);if(g.rank!=null)v.put("bgg_rank",g.rank);if(g.voters!=null)v.put("voters",g.voters);if(g.qualityScore!=null)v.put("quality_score",g.qualityScore);if(g.minPlayers!=null)v.put("min_players",g.minPlayers);if(g.maxPlayers!=null)v.put("max_players",g.maxPlayers);if(g.categories!=null)v.put("categories",g.categories);if(g.editionId!=null)v.put("edition_id",g.editionId);if(g.editionName!=null)v.put("edition_label",g.editionName);return v;}
    public synchronized void add(BggSearchClient.Game g,Integer paid,String source,Integer shipping,Long acquiredAt){add(g,paid,source,shipping,acquiredAt,null,false);}
    public synchronized void add(BggSearchClient.Game g,Integer paid,String source,Integer shipping,Long acquiredAt,Integer fee,boolean feeEstimated){
        if(g==null||g.id==null||g.id.trim().isEmpty())throw new IllegalArgumentException("BGG id mancante");if(g.name==null||g.name.trim().isEmpty())throw new IllegalArgumentException("Nome gioco mancante");
        ContentValues v=gameValues(g);v.put("bgg_id",g.id);v.put("collection_state","owned");v.putNull("sold_reason");v.putNull("sold_at");v.putNull("sale_price_cents");v.put("bundle_purchase",0);v.putNull("bundle_label");v.putNull("bundle_size");v.putNull("bundle_group_id");v.putNull("bundle_total_cents");if(source!=null)v.put("source",source);if("Regalo".equalsIgnoreCase(source)){v.putNull("paid_cents");v.putNull("shipping_cents");v.putNull("fee_cents");v.put("fee_estimated",0);}else{if(paid!=null)v.put("paid_cents",paid);if(shipping!=null)v.put("shipping_cents",shipping);if(fee!=null){v.put("fee_cents",fee);v.put("fee_estimated",feeEstimated?1:0);}}if(acquiredAt!=null)v.put("acquired_at",acquiredAt);
        SQLiteDatabase db=getWritableDatabase();if(db.update("library_games",v,"bgg_id=?",new String[]{g.id})==0){v.put("added_at",System.currentTimeMillis());db.insert("library_games",null,v);}
    }
    public synchronized void add(BggSearchClient.Game g,Integer paid,String source,Integer shipping){add(g,paid,source,shipping,null);}
    public synchronized void updateBgg(BggSearchClient.Game g){if(g==null||g.id==null)return;getWritableDatabase().update("library_games",gameValues(g),"bgg_id=?",new String[]{g.id});}
    public synchronized void markSold(String bggId,String reason){markSold(bggId,reason,null);}
    public synchronized void markSold(String bggId,String reason,Integer salePriceCents){if(salePriceCents!=null&&salePriceCents<0)throw new IllegalArgumentException("Prezzo vendita negativo");ContentValues v=new ContentValues();v.put("collection_state","sold");v.put("sold_at",System.currentTimeMillis());if(reason==null)v.putNull("sold_reason");else v.put("sold_reason",reason);if(salePriceCents==null)v.putNull("sale_price_cents");else v.put("sale_price_cents",salePriceCents);getWritableDatabase().update("library_games",v,"bgg_id=?",new String[]{bggId});}
    public synchronized boolean setSalePrice(String bggId,Integer salePriceCents){if(salePriceCents!=null&&salePriceCents<0)throw new IllegalArgumentException("Prezzo vendita negativo");ContentValues v=new ContentValues();if(salePriceCents==null)v.putNull("sale_price_cents");else v.put("sale_price_cents",salePriceCents);return getWritableDatabase().update("library_games",v,"bgg_id=? AND collection_state='sold'",new String[]{bggId})>0;}
    public synchronized void restoreOwned(String bggId){ContentValues v=new ContentValues();v.put("collection_state","owned");v.putNull("sold_reason");v.putNull("sold_at");v.putNull("sale_price_cents");getWritableDatabase().update("library_games",v,"bgg_id=?",new String[]{bggId});}
    public synchronized void deleteGame(String bggId){getWritableDatabase().delete("library_games","bgg_id=?",new String[]{bggId});}
    public synchronized void setPersonalRating(String bggId,Integer rating){ContentValues v=new ContentValues();if(rating==null)v.putNull("personal_rating");else v.put("personal_rating",Math.max(0,Math.min(10,rating)));getWritableDatabase().update("library_games",v,"bgg_id=?",new String[]{bggId});}
    public synchronized void setBundlePurchase(String bggId,boolean bundle,String label,Integer size,Integer allocatedShipping){setBundlePurchase(bggId,bundle,label,size,allocatedShipping,null,null);}
    public synchronized void setBundlePurchase(String bggId,boolean bundle,String label,Integer size,Integer allocatedShipping,String groupId,Integer totalCents){ContentValues v=new ContentValues();v.put("bundle_purchase",bundle?1:0);if(label==null)v.putNull("bundle_label");else v.put("bundle_label",label);if(size==null)v.putNull("bundle_size");else v.put("bundle_size",size);if(allocatedShipping!=null)v.put("shipping_cents",allocatedShipping);if(groupId==null)v.putNull("bundle_group_id");else v.put("bundle_group_id",groupId);if(totalCents==null)v.putNull("bundle_total_cents");else v.put("bundle_total_cents",totalCents);getWritableDatabase().update("library_games",v,"bgg_id=?",new String[]{bggId});}
    public synchronized List<LibraryGame> all(){List<LibraryGame>o=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,bgg_id,name,image_url,source,paid_cents,shipping_cents,rating,weight,playtime,acquired_at,added_at,edition_id,edition_label,fee_cents,fee_estimated,bundle_purchase,bundle_label,bundle_size,geek_rating,bgg_rank,voters,quality_score,min_players,max_players,categories,personal_rating,bundle_group_id,bundle_total_cents,collection_state,sold_reason,sold_at,sale_price_cents FROM library_games ORDER BY added_at DESC",null);while(c.moveToNext()){LibraryGame g=new LibraryGame();int i=0;g.id=c.getLong(i++);g.bggId=c.getString(i++);g.name=c.getString(i++);g.imageUrl=c.getString(i++);g.source=c.getString(i++);g.paidCents=c.isNull(i)?null:c.getInt(i);i++;g.shippingCents=c.isNull(i)?null:c.getInt(i);i++;g.rating=c.isNull(i)?null:c.getDouble(i);i++;g.weight=c.isNull(i)?null:c.getDouble(i);i++;g.playtime=c.isNull(i)?null:c.getInt(i);i++;g.acquiredAt=c.isNull(i)?null:c.getLong(i);i++;g.addedAt=c.getLong(i++);g.editionId=c.getString(i++);g.editionLabel=c.getString(i++);g.feeCents=c.isNull(i)?null:c.getInt(i);i++;g.feeEstimated=c.getInt(i++)==1;g.bundlePurchase=c.getInt(i++)==1;g.bundleLabel=c.getString(i++);g.bundleSize=c.isNull(i)?null:c.getInt(i);i++;g.geekRating=c.isNull(i)?null:c.getDouble(i);i++;g.rank=c.isNull(i)?null:c.getInt(i);i++;g.voters=c.isNull(i)?null:c.getInt(i);i++;g.qualityScore=c.isNull(i)?null:c.getInt(i);i++;g.minPlayers=c.isNull(i)?null:c.getInt(i);i++;g.maxPlayers=c.isNull(i)?null:c.getInt(i);i++;g.categories=c.getString(i++);g.personalRating=c.isNull(i)?null:c.getInt(i);i++;g.bundleGroupId=c.getString(i++);g.bundleTotalCents=c.isNull(i)?null:c.getInt(i);i++;g.collectionState=c.getString(i++);g.soldReason=c.getString(i++);g.soldAt=c.isNull(i)?null:c.getLong(i);i++;g.salePriceCents=c.isNull(i)?null:c.getInt(i);i++;o.add(g);}c.close();return o;}
}
