package it.vintedaffari.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.content.res.ColorStateList;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.webkit.CookieManager;
import android.webkit.RenderProcessGoneDetail;
import android.webkit.WebResourceRequest;
import android.webkit.WebResourceResponse;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;
import org.json.JSONArray;
import org.json.JSONObject;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

/** Public browser capture with durable local intake; no endpoint replay or automatic navigation. */
public final class VintedBrowserActivity extends Activity {
 private static final int BG=Color.rgb(10,11,20),TEXT=Color.WHITE,MUTED=Color.rgb(170,170,195);
 private final ThreadPoolExecutor ingest=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(4)){@Override protected void terminated(){if(captureDatabase!=null)captureDatabase.close();}};
 private final LinkedHashMap<String,JSONObject> items=new LinkedHashMap<>();
 private final LinkedHashSet<String> routes=new LinkedHashSet<>();
 private final AtomicInteger rejected=new AtomicInteger();
 private volatile boolean accepting,closed,resumed;
 private volatile long captureGeneration,pageGeneration;
 private boolean enabled,supported,rendererGone,pageFailed;
 private String mode,state="STARTING",expectedSeller="",lastReport="",navigationUrl="",lastSearchUrl="https://www.vinted.it/catalog/4881-board-games";
 private int updates,jsonItems,domItems,dropped,unknownShapes,readErrors,oversized;
 private DealDatabase captureDatabase;private MarketStore captureStore;
 private final LinkedHashSet<String> persistedPageIds=new LinkedHashSet<>();private volatile String intakeError="";
 private WebView web;private TextView status,previous,next;
 private enum BrowserUiState {exploreExpanded,exploreCollapsed,manualMatch}
 private BrowserUiState uiState=BrowserUiState.exploreExpanded;
 private ScrollView controlsHost;private LinearLayout expandedControls,manualCard,counterRow,paginationHost,pagesRow;private BrowserUiState renderedPagination;
 private TextView pageIndicator,relevant,newest,priceValue;
 private android.widget.Switch priceToggle;
 private TextView surpriseButton,huntsButton,priceMinus,pricePlus;
 private int priceLimitCents=2500;private boolean syncingControls;

 private Typeface appTypeface;private boolean loading;private int pageObserved,pagePrices;private volatile boolean pageDrained;private TextView counter;private LinearLayout progressSummary;private android.animation.ValueAnimator countMotion;private int shownCount,countTarget;
 @Override public void onCreate(Bundle saved){super.onCreate(saved);mode=getIntent().getStringExtra("mode");if(!"SEARCH".equals(mode)&&!"BUNDLE".equals(mode))mode="VIEW";enabled=VintedBrowserPolicy.startsEnabled(mode);expectedSeller=getIntent().getStringExtra("expected_seller_id");if(expectedSeller==null||!expectedSeller.matches("[1-9][0-9]{0,18}"))expectedSeller="";
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(0,statusBarHeight(),0,0);setContentView(root);
  try{appTypeface=Typeface.createFromAsset(getAssets(),"fonts/remus-variable.ttf");}catch(Exception ignored){appTypeface=Typeface.create("sans-serif",Typeface.NORMAL);}
  LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(16),dp(8),dp(16),dp(8));bar.setGravity(Gravity.CENTER_VERTICAL);bar.setMinimumHeight(dp(64));
  bar.addView(icon(LudoIcons.XMARK,"Chiudi browser",this::finish),new LinearLayout.LayoutParams(dp(48),dp(48)));
  TextView title=label("Vinted",20);title.setMaxLines(1);title.setEllipsize(android.text.TextUtils.TruncateAt.END);title.setPadding(dp(12),0,dp(12),0);bar.addView(title,new LinearLayout.LayoutParams(0,-2,1));
  bar.addView(icon(LudoIcons.ELLIPSIS_VERTICAL,"Opzioni browser",this::showMenu),new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(bar);
  if(saved!=null){try{uiState=BrowserUiState.valueOf(saved.getString("browser_ui","exploreExpanded"));}catch(IllegalArgumentException ignored){}priceLimitCents=saved.getInt("price_limit",2500);}
  else if("VIEW".equals(mode))uiState=BrowserUiState.manualMatch;
  if(uiState==BrowserUiState.manualMatch)enabled=false;
  buildBrowserChrome(root);

  web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));
  WebView.setWebContentsDebuggingEnabled(false);WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setSafeBrowsingEnabled(true);settings.setSupportMultipleWindows(false);settings.setJavaScriptCanOpenWindowsAutomatically(false);CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);
  web.setWebViewClient(new WebViewClient(){
   @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){if(!request.isForMainFrame())return false;boolean allowed=VintedBrowserPolicy.allowedPage(request.getUrl().toString());if(!allowed)Toast.makeText(VintedBrowserActivity.this,"Questa pagina non fa parte del test pubblico",Toast.LENGTH_SHORT).show();return !allowed;}
   @Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){observeRoute(request.getUrl());return null;}
   @Override public void onPageStarted(WebView view,String url,android.graphics.Bitmap icon){resetPage(url);loading=true;pageFailed=false;refreshStatus();if(!VintedBrowserPolicy.allowedPage(url)){view.stopLoading();state="PAGE_BLOCKED";refreshStatus();}}
   @Override public void onPageFinished(WebView view,String url){if(closed||rendererGone)return;navigationUrl=url;loading=false;if(pageFailed){accepting=false;}else if(!VintedBrowserPolicy.allowedPage(url)){state="PAGE_BLOCKED";accepting=false;}else{state=supported?(enabled?"CAPTURING":"PAUSED"):"UNSUPPORTED_PROVIDER";accepting=supported&&enabled&&resumed;if(supported)bindPage();}refreshStatus();}
   @Override public void onReceivedError(WebView view,WebResourceRequest request,android.webkit.WebResourceError error){if(request.isForMainFrame()){loading=false;pageFailed=true;accepting=false;state="PAGE_ERROR";refreshStatus();}}
   @Override public void onReceivedHttpError(WebView view,WebResourceRequest request,WebResourceResponse response){if(request.isForMainFrame()&&response.getStatusCode()>=400){loading=false;pageFailed=true;accepting=false;state="PAGE_ERROR";refreshStatus();}}
   @Override public boolean onRenderProcessGone(WebView view,RenderProcessGoneDetail detail){accepting=false;rendererGone=true;state="RENDERER_GONE";((LinearLayout)view.getParent()).removeView(view);view.destroy();web=null;refreshStatus();Toast.makeText(VintedBrowserActivity.this,"Browser interrotto. Chiudi e riapri per riprovare.",Toast.LENGTH_LONG).show();return true;}
  });
  supported=WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)&&WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER);
  try{if(supported){WebViewCompat.addWebMessageListener(web,"LudoCapture",new LinkedHashSet<>(java.util.Arrays.asList("https://www.vinted.it","https://vinted.it")),(view,message,origin,mainFrame,reply)->receive(message.getData(),origin.toString(),mainFrame,reply));String script;try(java.io.InputStream input=getAssets().open("browser/vinted-capture.js")){java.io.ByteArrayOutputStream output=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[4096];int count;while((count=input.read(buffer))!=-1)output.write(buffer,0,count);script=new String(output.toByteArray(),StandardCharsets.UTF_8);}JSONObject initial=new JSONObject();initial.put("enabled",enabled);initial.put("expectedSeller",expectedSeller);WebViewCompat.addDocumentStartJavaScript(web,"window.__LudoCaptureInitial="+initial+";\n"+script,new LinkedHashSet<>(java.util.Arrays.asList("https://www.vinted.it","https://vinted.it")));}}
  catch(Exception error){supported=false;accepting=false;state="CAPTURE_INIT_ERROR";}
  refreshStatus();String url=getIntent().getStringExtra("url");if(!VintedBrowserPolicy.allowedPage(url))url="https://www.vinted.it/catalog/4881-board-games";if("SEARCH".equals(mode)){Uri original=Uri.parse(url);Uri.Builder b=original.buildUpon().path("/catalog/4881-board-games").clearQuery();for(String key:original.getQueryParameterNames())if(!key.equals("catalog[]")&&!key.equals("catalog_ids[]")&&!key.equals("catalog_id"))for(String value:original.getQueryParameters(key))b.appendQueryParameter(key,value);url=b.build().toString();}navigationUrl=url;accepting=supported&&enabled&&resumed;web.loadUrl(url);
 }
 private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}
 private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private void section(LinearLayout host,String title){TextView t=label(title,13);t.setTextColor(MUTED);t.setPadding(dp(4),dp(8),dp(4),dp(4));host.addView(t);}
 private void buildBrowserChrome(LinearLayout root){
  expandedControls=column();expandedControls.setPadding(dp(16),0,dp(16),dp(8));
  section(expandedControls,"Ordine");LinearLayout orders=row();
  LinearLayout selector=row();selector.setBackground(capsule());selector.setPadding(dp(3),dp(3),dp(3),dp(3));
  relevant=orderOption("Rilevanti",LudoIcons.STAR,"relevance");newest=orderOption("Nuovi",LudoIcons.CLOCK,"newest_first");
  selector.addView(relevant,new LinearLayout.LayoutParams(0,-2,1));selector.addView(newest,new LinearLayout.LayoutParams(0,-2,1));
  boolean narrow=getResources().getConfiguration().screenWidthDp<360||getResources().getConfiguration().fontScale>1.3f;
  orders.addView(selector,new LinearLayout.LayoutParams(0,-2,1));
  LinearLayout quick=row();quick.setGravity(Gravity.CENTER);
  surpriseButton=icon(LudoIcons.SHUFFLE,"Sorprendimi",this::surprise);surpriseButton.setTextColor(Color.rgb(164,151,255));
  huntsButton=icon(LudoIcons.HEART,"Dalle mie cacce",this::fromHunts);huntsButton.setTextColor(Color.rgb(241,160,232));
  quick.addView(surpriseButton,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout.LayoutParams heart=new LinearLayout.LayoutParams(dp(48),dp(48));heart.leftMargin=dp(4);quick.addView(huntsButton,heart);
  if(!narrow){LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-2,-2);qp.leftMargin=dp(8);orders.addView(quick,qp);}expandedControls.addView(orders);
  if(narrow){LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,-2);qp.topMargin=dp(4);expandedControls.addView(quick,qp);}
  section(expandedControls,"Soglia prezzo");LinearLayout threshold=column();threshold.setBackground(capsule());threshold.setPadding(dp(8),dp(4),dp(8),dp(4));LinearLayout priceRow=row();
  TextView tag=label(LudoIcons.TAG,18);tag.setTypeface(LudoIcons.solid(this));tag.setTextColor(Color.rgb(164,151,255));priceRow.addView(tag,new LinearLayout.LayoutParams(dp(32),dp(48)));
  TextView priceLabel=label("Soglia prezzo",14);priceRow.addView(priceLabel,new LinearLayout.LayoutParams(0,-2,1));
  priceToggle=new android.widget.Switch(this);priceToggle.setContentDescription("Attiva soglia prezzo");priceToggle.setMinHeight(dp(48));priceToggle.setThumbTintList(ColorStateList.valueOf(Color.WHITE));priceToggle.setTrackTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{Color.rgb(151,113,224),Color.rgb(43,51,100)}));priceToggle.setOnCheckedChangeListener((button,on)->{if(!syncingControls)applyPriceLimit(on?priceLimitCents:0);});priceRow.addView(priceToggle);
  LinearLayout stepper=row();stepper.setGravity(Gravity.CENTER);priceMinus=icon("\uf068","Riduci soglia prezzo di 5 euro",()->stepPrice(-500));pricePlus=icon(LudoIcons.PLUS,"Aumenta soglia prezzo di 5 euro",()->stepPrice(500));
  stepper.addView(priceMinus,new LinearLayout.LayoutParams(dp(48),dp(48)));priceValue=label("25 €",18);priceValue.setGravity(Gravity.CENTER);priceValue.setTypeface(appTypeface,Typeface.BOLD);priceValue.setMinWidth(dp(64));priceValue.setPadding(dp(4),dp(8),dp(4),dp(8));stepper.addView(priceValue,new LinearLayout.LayoutParams(narrow?0:dp(76),-2,narrow?1:0));stepper.addView(pricePlus,new LinearLayout.LayoutParams(dp(48),dp(48)));
  threshold.addView(priceRow);threshold.addView(stepper);expandedControls.addView(threshold);
  section(expandedControls,"Filtri attivi");TextView category=label("Giochi da tavolo",14);category.setCompoundDrawablesWithIntrinsicBounds(LudoIcons.drawable(this,LudoIcons.TAG,TEXT,dp(18)),null,null,null);category.setCompoundDrawablePadding(dp(8));category.setPadding(dp(12),dp(10),dp(12),dp(10));category.setBackground(capsule());category.setContentDescription("Filtro attivo: Giochi da tavolo");expandedControls.addView(category,new LinearLayout.LayoutParams(-2,-2));
  // Bound the expanded chrome so larger accessibility fonts never consume the WebView.
  controlsHost=new ScrollView(this){@Override protected void onMeasure(int widthSpec,int heightSpec){int limit=Math.round(getResources().getDisplayMetrics().heightPixels*.38f);super.onMeasure(widthSpec,View.MeasureSpec.makeMeasureSpec(limit,View.MeasureSpec.AT_MOST));}};
  controlsHost.setFillViewport(false);controlsHost.addView(expandedControls);root.addView(controlsHost,new LinearLayout.LayoutParams(-1,-2));
  manualCard=column();manualCard.setPadding(dp(16),dp(4),dp(16),dp(8));TextView badge=label("Match manuale",14);badge.setTextColor(Color.rgb(184,164,255));badge.setPadding(dp(12),dp(8),dp(12),dp(8));badge.setBackground(capsule());badge.setCompoundDrawablesWithIntrinsicBounds(LudoIcons.drawable(this,LudoIcons.USER,Color.rgb(184,164,255),dp(18)),null,null,null);badge.setCompoundDrawablePadding(dp(8));manualCard.addView(badge,new LinearLayout.LayoutParams(-2,-2));
  LinearLayout paused=row();paused.setPadding(dp(16),dp(16),dp(16),dp(16));paused.setBackground(capsule());TextView pause=label(LudoIcons.PAUSE,24);pause.setTypeface(LudoIcons.solid(this));pause.setTextColor(Color.rgb(164,151,255));paused.addView(pause,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout copy=column();copy.setPadding(dp(12),0,0,0);TextView heading=label("Ludo in pausa",20);heading.setTypeface(appTypeface,Typeface.BOLD);copy.addView(heading);TextView detail=label("Stai cercando manualmente su Vinted.",14);detail.setTextColor(MUTED);detail.setPadding(0,dp(4),0,0);copy.addView(detail);paused.addView(copy,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams card=new LinearLayout.LayoutParams(-1,-2);card.topMargin=dp(12);manualCard.addView(paused,card);root.addView(manualCard);
  counterRow=row();if(getResources().getConfiguration().fontScale>1.3f)counterRow.setOrientation(LinearLayout.VERTICAL);counterRow.setGravity(Gravity.CENTER);counterRow.setPadding(dp(16),dp(4),dp(16),dp(4));progressSummary=counterRow;counterRow.setFocusable(true);counter=label("0",32);counter.setTypeface(appTypeface,Typeface.BOLD);counter.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);counterRow.addView(counter);TextView caption=label("annunci salvati",14);caption.setTextColor(MUTED);caption.setPadding(dp(8),0,0,0);counterRow.addView(caption);paginationHost=column();root.addView(paginationHost);
  LinearLayout pages=row();pagesRow=pages;pages.setGravity(Gravity.CENTER);pages.setPadding(dp(16),0,dp(16),dp(8));previous=icon(LudoIcons.CHEVRON_LEFT,"Pagina precedente",()->navigate("previous",""));next=icon(LudoIcons.CHEVRON_RIGHT,"Pagina successiva",()->navigate("next",""));pages.addView(previous,new LinearLayout.LayoutParams(dp(48),dp(48)));pageIndicator=label("1 di 10",18);pageIndicator.setTypeface(appTypeface,Typeface.BOLD);pageIndicator.setGravity(Gravity.CENTER);pageIndicator.setMinHeight(dp(48));pages.addView(pageIndicator,new LinearLayout.LayoutParams(0,-2,1));pages.addView(next,new LinearLayout.LayoutParams(dp(48),dp(48)));layoutPagination();
  status=label("",13);status.setGravity(Gravity.CENTER);status.setTextColor(MUTED);status.setPadding(dp(16),dp(4),dp(16),dp(8));status.setOnClickListener(v->{if(web!=null&&!loading&&(pageFailed||!intakeError.isEmpty()||readErrors>0||dropped>0||oversized>0)){pageDrained=false;web.reload();}});root.addView(status);
 }
 private void detach(View v){if(v.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)v.getParent()).removeView(v);}
 private void layoutPagination(){if(renderedPagination==uiState)return;renderedPagination=uiState;
  detach(previous);detach(next);detach(pageIndicator);detach(counterRow);detach(pagesRow);paginationHost.removeAllViews();pagesRow.removeAllViews();
  if(uiState==BrowserUiState.exploreExpanded)paginationHost.addView(counterRow);
  pagesRow.addView(previous,new LinearLayout.LayoutParams(dp(48),dp(48)));
  if(uiState==BrowserUiState.exploreCollapsed){counterRow.setPadding(dp(4),0,dp(4),0);pagesRow.addView(counterRow,new LinearLayout.LayoutParams(0,-2,1));}
  else{counterRow.setPadding(dp(16),dp(4),dp(16),dp(4));pagesRow.addView(pageIndicator,new LinearLayout.LayoutParams(0,-2,1));}
  pagesRow.addView(next,new LinearLayout.LayoutParams(dp(48),dp(48)));paginationHost.addView(pagesRow);
  if(uiState==BrowserUiState.exploreCollapsed)paginationHost.addView(pageIndicator,new LinearLayout.LayoutParams(-1,-2));
 }
 private TextView orderOption(String name,String glyph,String value){TextView t=label(name,14);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(48));t.setPadding(dp(8),dp(8),dp(8),dp(8));t.setCompoundDrawablesWithIntrinsicBounds(LudoIcons.drawable(this,glyph,TEXT,dp(16)),null,null,null);t.setCompoundDrawablePadding(dp(4));t.setContentDescription("Ordine: "+name);t.setOnClickListener(v->navigate("order",value));return t;}
 private String currentOrder(){String value=Uri.parse(lastSearchUrl).getQueryParameter("order");return "newest_first".equals(value)?value:"relevance";}
 private int currentPriceLimit(){try{String value=Uri.parse(lastSearchUrl).getQueryParameter("price_to");return value==null?0:new java.math.BigDecimal(value).movePointRight(2).intValueExact();}catch(RuntimeException invalid){return 0;}}
 private void syncExplorationControls(){boolean ready=!loading&&web!=null&&!rendererGone;relevant.setSelected(!"newest_first".equals(currentOrder()));newest.setSelected(!relevant.isSelected());for(TextView option:new TextView[]{relevant,newest}){option.setBackground(option.isSelected()?selectedCapsule():capsule());option.setEnabled(ready);option.setAlpha(ready?1f:.5f);}surpriseButton.setEnabled(ready);huntsButton.setEnabled(ready);int actual=currentPriceLimit();if(actual>0)priceLimitCents=actual;syncingControls=true;priceToggle.setChecked(actual>0);syncingControls=false;priceToggle.setEnabled(ready);priceValue.setText(java.math.BigDecimal.valueOf(priceLimitCents,2).stripTrailingZeros().toPlainString()+" €");priceMinus.setEnabled(ready&&actual>0&&priceLimitCents>500);pricePlus.setEnabled(ready&&actual>0&&priceLimitCents<9999900);priceMinus.setAlpha(priceMinus.isEnabled()?1f:.35f);pricePlus.setAlpha(pricePlus.isEnabled()?1f:.35f);}
 private android.graphics.drawable.Drawable selectedCapsule(){GradientDrawable shape=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{Color.rgb(111,77,216),Color.rgb(151,113,224)});shape.setCornerRadius(dp(24));return new RippleDrawable(ColorStateList.valueOf(Color.argb(65,255,255,255)),shape,null);}
 private void stepPrice(int delta){applyPriceLimit(Math.max(500,Math.min(9999900,priceLimitCents+delta)));}
 private void applyPriceLimit(int cents){if(closed||web==null||loading){syncExplorationControls();return;}Uri current=Uri.parse(lastSearchUrl);Uri.Builder b=current.buildUpon().clearQuery();for(String key:current.getQueryParameterNames())if(!"price_to".equals(key)&&!"page".equals(key))for(String value:current.getQueryParameters(key))b.appendQueryParameter(key,value);b.appendQueryParameter("page","1");if(cents>0)b.appendQueryParameter("price_to",java.math.BigDecimal.valueOf(cents,2).stripTrailingZeros().toPlainString());String url=b.build().toString();if(!VintedBrowserPolicy.allowedPage(url))return;loading=true;pageDrained=false;refreshStatus();web.loadUrl(url);}
 private void fromHunts(){if(closed||web==null||loading)return;java.util.Set<String> favorites=new java.util.TreeSet<>(getSharedPreferences("ludo_game_preferences_v1",MODE_PRIVATE).getStringSet("favorites",java.util.Collections.emptySet()));if(favorites.isEmpty()){Toast.makeText(this,"Salva un gioco con il cuore nelle tue Cacce",Toast.LENGTH_SHORT).show();return;}try{ingest.execute(()->{java.util.List<GameRecord> games=new java.util.ArrayList<>();boolean failed=false;try(DealDatabase lookup=new DealDatabase(getApplicationContext())){MarketStore store=new MarketStore(getApplicationContext(),lookup);for(String id:favorites){String normalized=GamePreferenceState.gameId(id);if(normalized==null)continue;GameRecord game=store.gameStatsByBggId(normalized);if(game!=null&&game.name!=null&&!game.name.trim().isEmpty()&&game.name.length()<=100)games.add(game);}}catch(RuntimeException error){failed=true;}final boolean failure=failed;runOnUiThread(()->{if(closed||isFinishing())return;if(failure||games.isEmpty()){Toast.makeText(this,failure?"Cacce non disponibili. Riprova.":"Nessun titolo disponibile nelle tue Cacce",Toast.LENGTH_SHORT).show();return;}android.app.Dialog dialog=sheet("Dalle mie cacce");LinearLayout box=sheetBody(dialog);for(GameRecord game:games)choice(box,LudoIcons.HEART,game.name,"Cerca su Vinted",()->{dialog.dismiss();loadExploration(game.name,currentOrder(),0,currentPriceLimit());});dialog.show();dialog.getWindow().setLayout(-1,-2);});});}catch(java.util.concurrent.RejectedExecutionException busy){Toast.makeText(this,"Sto salvando gli annunci. Riprova tra poco.",Toast.LENGTH_SHORT).show();}}
 private TextView label(String name,int size){TextView t=new TextView(this);t.setText(name);t.setTextSize(size);t.setTextColor(TEXT);t.setTypeface(appTypeface);t.setIncludeFontPadding(false);return t;}
 private android.graphics.drawable.Drawable capsule(){GradientDrawable shape=new GradientDrawable();shape.setColor(Color.rgb(22,26,47));shape.setCornerRadius(dp(24));shape.setStroke(dp(1),Color.rgb(43,51,100));return new RippleDrawable(ColorStateList.valueOf(Color.argb(65,164,151,255)),shape,null);}
 private TextView icon(String glyph,String description,Runnable run){TextView t=label(glyph,18);t.setTypeface(LudoIcons.solid(this));t.setGravity(Gravity.CENTER);t.setContentDescription(description);t.setBackground(new android.graphics.drawable.InsetDrawable(capsule(),dp(3)));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setOnClickListener(v->run.run());return t;}
 private Button action(String name,Runnable run){Button b=new Button(this);b.setText(name);b.setTextColor(TEXT);b.setTextSize(14);b.setTypeface(appTypeface);b.setAllCaps(false);b.setMinWidth(dp(48));b.setMinimumWidth(dp(48));b.setMinHeight(dp(56));b.setMinimumHeight(dp(56));b.setBackground(new android.graphics.drawable.InsetDrawable(capsule(),dp(3)));b.setPadding(dp(16),dp(12),dp(16),dp(12));b.setContentDescription(name);b.setOnClickListener(v->run.run());return b;}
 private android.app.Dialog sheet(String title){android.app.Dialog dialog=new android.app.Dialog(this);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(20),dp(20),dp(24));box.setBackground(capsule());TextView heading=label(title,24);heading.setTypeface(appTypeface,Typeface.BOLD);heading.setPadding(0,0,0,dp(16));box.addView(heading);scroll.addView(box);dialog.setContentView(scroll);dialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);dialog.getWindow().setGravity(Gravity.BOTTOM);dialog.getWindow().setLayout(-1,-2);box.setTag(dialog);return dialog;}
 private LinearLayout sheetBody(android.app.Dialog dialog){return (LinearLayout)((ScrollView)((android.widget.FrameLayout)dialog.findViewById(android.R.id.content)).getChildAt(0)).getChildAt(0);}
 private void choice(LinearLayout box,String glyph,String title,String description,Runnable run){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(16),dp(16),dp(16),dp(16));row.setMinimumHeight(dp(72));row.setBackground(capsule());TextView symbol=label(glyph,22);symbol.setTypeface(LudoIcons.solid(this));row.addView(symbol,new LinearLayout.LayoutParams(dp(36),dp(36)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);TextView name=label(title,17);name.setTypeface(appTypeface,Typeface.BOLD);copy.addView(name);TextView detail=label(description,13);detail.setTextColor(MUTED);detail.setPadding(0,dp(4),0,0);copy.addView(detail);row.addView(copy,new LinearLayout.LayoutParams(0,-2,1));row.setContentDescription(title+". "+description);row.setFocusable(true);row.setOnClickListener(v->run.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(8);box.addView(row,lp);}
 private void loadExploration(String query,String order,int minimum,int maximum){String url=ExplorationPlan.url(query,order,minimum,maximum);if(url.isEmpty()){Toast.makeText(this,"Controlla nome e intervallo di prezzo",Toast.LENGTH_SHORT).show();return;}if(closed||web==null||loading)return;loading=true;pageFailed=false;refreshStatus();web.loadUrl(url);}
 private void surprise(){if(closed||web==null||loading)return;try{ingest.execute(()->{String query="";try(DealDatabase lookup=new DealDatabase(getApplicationContext())){query=lookup.randomExplorationTitle();}catch(RuntimeException ignored){}final String title=query;String order=currentOrder();int max=currentPriceLimit();runOnUiThread(()->{if(!closed){if(title.isEmpty())Toast.makeText(this,"Nessun titolo disponibile: apro tutti i giochi",Toast.LENGTH_SHORT).show();loadExploration(title,order,0,max);}});});}catch(java.util.concurrent.RejectedExecutionException busy){Toast.makeText(this,"Sto salvando gli annunci. Riprova tra poco.",Toast.LENGTH_SHORT).show();}}
 private void showMenu(){android.app.Dialog dialog=sheet("Opzioni browser");LinearLayout box=sheetBody(dialog);
  if("SEARCH".equals(mode)){choice(box,LudoIcons.SLIDERS,uiState==BrowserUiState.exploreExpanded?"Comprimi controlli":"Espandi controlli","Cambia lo spazio occupato da Ludo",()->{dialog.dismiss();uiState=uiState==BrowserUiState.exploreExpanded?BrowserUiState.exploreCollapsed:BrowserUiState.exploreExpanded;if(!enabled)setCapture(true);refreshStatus();});
   choice(box,LudoIcons.USER,"Match manuale","Metti Ludo in pausa",()->{dialog.dismiss();uiState=BrowserUiState.manualMatch;setCapture(false);refreshStatus();});}
  choice(box,LudoIcons.INFO,"Dati della cattura","Controlla gli annunci acquisiti",()->{dialog.dismiss();showReport();});
  if("BUNDLE".equals(mode)){choice(box,enabled?LudoIcons.PAUSE:LudoIcons.PLAY,enabled?"Pausa cattura":"Riprendi cattura","Controlla la cattura del venditore",()->{dialog.dismiss();setCapture(!enabled);});choice(box,LudoIcons.CAMERA,"Cattura pagina","Acquisisci i dati già visibili",()->{dialog.dismiss();captureNow();});}
  dialog.show();dialog.getWindow().setLayout(-1,-2);
 }
 private void navigate(String command,String argument){if(web==null||loading||pageFailed||!supported||("next".equals(command)&&!next.isEnabled()))return;final long token=pageGeneration;final String page=navigationUrl;String gate="next".equals(command)&&uiState!=BrowserUiState.manualMatch?"window.LudoCaptureControl.canAdvance("+token+")&&":"";String script="window.LudoCaptureControl?("+gate+"window.LudoCaptureControl.navigationUrl("+JSONObject.quote(command)+","+JSONObject.quote(argument)+","+JSONObject.quote(lastSearchUrl)+")):null";web.evaluateJavascript(script,result->{if(closed||web==null||loading||token!=pageGeneration||!samePage(page,navigationUrl))return;try{Object value=new org.json.JSONTokener(result).nextValue();if(value instanceof String&&VintedBrowserPolicy.allowedPage((String)value)){loading=true;pageDrained=false;refreshStatus();web.loadUrl((String)value);}else if("next".equals(command)){pageDrained=false;refreshStatus();}}catch(Exception ignored){}});}
 private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 private int statusBarHeight(){int id=getResources().getIdentifier("status_bar_height","dimen","android");return id==0?0:getResources().getDimensionPixelSize(id);}
 private void setCapture(boolean value){if(!supported||web==null)return;captureGeneration++;pageDrained=false;enabled=value;accepting=value&&resumed&&!pageFailed&&VintedBrowserPolicy.allowedPage(navigationUrl);state=value?"CAPTURING":"PAUSED";web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled("+value+")",null);refreshStatus();}
 private void captureNow(){if(!supported||web==null||!resumed||pageFailed||!VintedBrowserPolicy.allowedPage(web.getUrl()))return;captureGeneration++;pageDrained=false;accepting=true;web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.captureNow("+captureGeneration+")",null);}
 private void resetPage(String url){pageDrained=false;cancelCount();shownCount=0;if(counter!=null)counter.setText("0");accepting=false;captureGeneration++;pageGeneration++;navigationUrl=url;if(Uri.parse(url).getPath()!=null&&Uri.parse(url).getPath().startsWith("/catalog"))lastSearchUrl=url;synchronized(items){items.clear();persistedPageIds.clear();updates=0;jsonItems=0;domItems=0;dropped=0;unknownShapes=0;readErrors=0;oversized=0;pageObserved=0;pagePrices=0;intakeError="";}}
 private void bindPage(){if(web==null||!supported)return;accepting=enabled&&resumed&&!pageFailed;web.evaluateJavascript("if(window.LudoCaptureControl){window.LudoCaptureControl.setPageToken("+pageGeneration+");window.LudoCaptureControl.setEnabled("+(enabled&&resumed)+");}",null);}
 private static String messageSequence(String data){if(data==null)return "0";java.util.regex.Matcher m=java.util.regex.Pattern.compile("\"seq\":([0-9]+)").matcher(data.substring(0,Math.min(100,data.length())));return m.find()?m.group(1):"0";}
 private void receive(String data,String origin,boolean mainFrame,androidx.webkit.JavaScriptReplyProxy reply){if(data!=null&&data.length()<=5000&&data.startsWith("{\"kind\":\"location\"")){try{if(closed||web==null||!VintedBrowserPolicy.allowedMessage(origin,mainFrame,data.getBytes(StandardCharsets.UTF_8).length))return;String url=new JSONObject(data).optString("url");if(VintedBrowserPolicy.allowedPage(url)&&samePage(url,web.getUrl())&&!samePage(url,navigationUrl)){resetPage(url);loading=false;pageFailed=false;bindPage();refreshStatus();}}catch(Exception ignored){}return;}if(closed||!accepting||data==null||data.length()>128*1024||web==null||!VintedBrowserPolicy.allowedPage(navigationUrl)){rejected.incrementAndGet();reply.postMessage("paused:"+messageSequence(data));return;}int bytes=data.getBytes(StandardCharsets.UTF_8).length;if(!VintedBrowserPolicy.allowedMessage(origin,mainFrame,bytes)){rejected.incrementAndGet();return;}pageDrained=false;refreshStatus();final long generation=captureGeneration,acceptedPageToken=pageGeneration;final String acceptedPageUrl=navigationUrl;try{ingest.execute(()->{boolean persisted=parse(data,generation,acceptedPageUrl,acceptedPageToken);runOnUiThread(()->{if(!closed)reply.postMessage((persisted?"ready:":"retry:")+messageSequence(data));});});}catch(java.util.concurrent.RejectedExecutionException error){rejected.incrementAndGet();reply.postMessage("retry:"+messageSequence(data));}}
 private boolean parse(String data,long generation,String acceptedPageUrl,long acceptedPageToken){try{
  java.util.List<JSONObject> captured=new java.util.ArrayList<>();JSONObject packet=new JSONObject(data);JSONArray incoming=packet.optJSONArray("items");if(packet.optInt("schema")!=1||incoming==null||incoming.length()>32){rejected.incrementAndGet();return true;}
  JSONObject page=packet.optJSONObject("page");if(page==null||!samePage(page.optString("url"),acceptedPageUrl)){rejected.incrementAndGet();return true;}
  synchronized(items){if(!samePage(page.optString("url"),acceptedPageUrl)||packet.optLong("pageToken",-1)!=acceptedPageToken)return true;boolean currentPage=acceptedPageToken==pageGeneration;if(currentPage){pageObserved=bound(page.optInt("observed"));pagePrices=bound(page.optInt("withPrice"));}for(int i=0;i<incoming.length();i++){JSONObject item=incoming.optJSONObject(i);if(item==null||!VintedBrowserPolicy.matchesItem(item.optString("url"),item.optString("id"))||item.optString("title").length()>600){rejected.incrementAndGet();continue;}String id=item.getString("id");if(currentPage&&!items.containsKey(id)&&items.size()>=500){dropped++;continue;}JSONObject clean=new JSONObject();for(String key:new String[]{"id","url","title","priceCents","protectedPriceCents","brand","condition","currency","sellerId","sellerName","description","language","publication","source","photos"}){Object value=item.opt(key);if(value==null||value==JSONObject.NULL)continue;if(value instanceof String&&((String)value).length()<=("description".equals(key)?2000:600))clean.put(key,value);else if(("priceCents".equals(key)||"protectedPriceCents".equals(key))&&value instanceof Number&&((Number)value).longValue()>0&&((Number)value).longValue()<=1000000000L)clean.put(key,value);else if("photos".equals(key)&&value instanceof JSONArray){JSONArray photos=new JSONArray();JSONArray source=(JSONArray)value;for(int n=0;n<Math.min(10,source.length());n++){String url=BrowserCapturePolicy.photo(source.optString(n));if(!url.isEmpty())photos.put(url);}if(photos.length()>0)clean.put(key,photos);}else if("publication".equals(key)&&value instanceof JSONObject){JSONObject p=(JSONObject)value;if(p.optString("raw").length()<=100&&p.optString("source").length()<=50)clean.put(key,new JSONObject().put("raw",p.optString("raw")).put("source",p.optString("source")));}}
   captured.add(clean);if(currentPage){JSONObject previous=items.get(id);if(previous!=null&&!previous.toString().equals(clean.toString()))updates++;items.put(id,clean);if("dom".equals(clean.optString("source")))domItems++;else jsonItems++;}}
   JSONObject stats=packet.optJSONObject("stats");if(currentPage&&stats!=null){dropped=Math.max(dropped,bound(stats.optInt("dropped")));unknownShapes=Math.max(unknownShapes,bound(stats.optInt("unknownShapes")));readErrors=Math.max(readErrors,bound(stats.optInt("readErrors")));oversized=Math.max(oversized,bound(stats.optInt("oversized")));}lastReport=reportLocked();}
  boolean persistedAll=true;String batchError="";if(!captured.isEmpty()){if(captureDatabase==null){captureDatabase=new DealDatabase(getApplicationContext());captureStore=new MarketStore(getApplicationContext(),captureDatabase);}for(JSONObject item:captured){try{long persisted=captureStore.captureBrowserItem(item,System.currentTimeMillis());if(persisted>0)synchronized(items){if(packet.optLong("pageToken",-1)==pageGeneration)persistedPageIds.add(item.optString("id"));} }catch(Exception failure){persistedAll=false;batchError=failure.getClass().getSimpleName();}}sendBroadcast(new android.content.Intent(BrowserCapturePolicy.READY_ACTION).setPackage(getPackageName()));sendBroadcast(new android.content.Intent("it.vintedaffari.app.DEALS_UPDATED").setPackage(getPackageName()));}
  final String currentError=batchError;final boolean persisted=persistedAll;boolean complete=packet.optBoolean("complete");saveReport();runOnUiThread(()->{if(!closed){if(acceptedPageToken==pageGeneration&&generation==captureGeneration){intakeError=currentError;pageDrained=persisted&&packet.optBoolean("settled")&&dropped==0&&readErrors==0&&oversized==0&&intakeError.isEmpty();}if(persisted&&complete&&!enabled&&packet.optLong("captureToken",-1)==captureGeneration&&generation==captureGeneration)accepting=false;refreshStatus();}});
 return persistedAll;}catch(Exception error){if(acceptedPageToken==pageGeneration&&generation==captureGeneration)intakeError=error.getClass().getSimpleName();rejected.incrementAndGet();return false;}}
 private static boolean samePage(String a,String b){try{return Uri.parse(a).buildUpon().fragment(null).build().equals(Uri.parse(b).buildUpon().fragment(null).build());}catch(Exception e){return false;}}
 private static int bound(int n){return Math.max(0,Math.min(1000000,n));}
 private void observeRoute(Uri uri){if(uri==null||!"https".equals(uri.getScheme())||!("www.vinted.it".equals(uri.getHost())||"vinted.it".equals(uri.getHost())))return;String path=uri.getPath();if(path==null||!path.startsWith("/api/"))return;path=path.replaceAll("[0-9]+","{id}").replaceAll("[^a-zA-Z0-9/{}_\\-]","_");if(path.length()>160)path=path.substring(0,160);synchronized(routes){if(routes.size()<20)routes.add(path);}}
 private String reportLocked(){int price=0,seller=0,publication=0,language=0;for(JSONObject item:items.values()){if(item.has("priceCents"))price++;if(item.has("sellerId"))seller++;if(item.has("publication"))publication++;if(item.has("language"))language++;}String routeSummary;synchronized(routes){routeSummary=routes.toString();}return "build=browser-engine-intake-v1;app="+BuildConfig.VERSION_NAME+";state="+state+";mode="+mode+";features="+supported+";capture="+enabled+";scope=currentPage;page="+pageNumber()+";pageObserved="+pageObserved+";pagePrices="+pagePrices+";acquiredUnique="+items.size()+";updated="+updates+";price="+price+";seller="+seller+";publication="+publication+";language="+language+";jsonOrInitial="+jsonItems+";dom="+domItems+";dropped="+dropped+";unknownShapes="+unknownShapes+";readErrors="+readErrors+";oversized="+oversized+";rejected="+rejected.get()+";extraRequestsByCapture=0;networkScope=capturer-only;catalogWrites="+persistedPageIds.size()+";intakeScope=currentPage;pageDrained="+pageDrained+";intakeError="+intakeError+";sellerCoverage=partial;routes="+routeSummary;}
 private void saveReport(){String report; synchronized(items){report=reportLocked();lastReport=report;}getSharedPreferences("vinted_browser_experiment",MODE_PRIVATE).edit().putString("report",report).putLong("at",System.currentTimeMillis()).apply();}
 private int pageNumber(){try{return Math.max(1,Math.min(10,Integer.parseInt(Uri.parse(navigationUrl).getQueryParameter("page"))));}catch(Exception ignored){return 1;}}
 private static boolean captureReady(boolean enabled,boolean pageDrained,int saved,int observed,int acquired,String error,boolean animating){return enabled&&pageDrained&&saved==observed&&acquired==observed&&error.isEmpty()&&!animating;}
 private boolean pageAdvanceReady(int saved,int size,boolean moving){return uiState==BrowserUiState.manualMatch||captureReady(enabled,pageDrained,saved,pageObserved,size,intakeError,moving);}
 private void refreshStatus(){int size,saved;synchronized(items){size=items.size();saved=persistedPageIds.size();}if(status==null)return;
  boolean catalog=Uri.parse(navigationUrl).getPath()!=null&&Uri.parse(navigationUrl).getPath().startsWith("/catalog");
  animateCount(saved);previous.setEnabled(supported&&catalog&&!loading&&!pageFailed&&pageNumber()>1);
  next.setEnabled(supported&&catalog&&!loading&&!pageFailed&&pageNumber()<10&&pageAdvanceReady(saved,size,countMotion!=null&&countMotion.isRunning()));
  previous.setAlpha(previous.isEnabled()?1f:.35f);next.setAlpha(next.isEnabled()?1f:.35f);
  pageIndicator.setText(pageNumber()+" di 10");pageIndicator.setContentDescription("Pagina "+pageNumber()+" di 10");
  controlsHost.setVisibility(uiState==BrowserUiState.exploreExpanded&&"SEARCH".equals(mode)?View.VISIBLE:View.GONE);layoutPagination();
  manualCard.setVisibility(uiState==BrowserUiState.manualMatch?View.VISIBLE:View.GONE);
  counterRow.setVisibility(uiState==BrowserUiState.manualMatch?View.GONE:View.VISIBLE);
  syncExplorationControls();
  String problem=!supported?"Cattura non disponibile su questa WebView":rendererGone?"Browser interrotto":pageFailed||state.equals("PAGE_BLOCKED")?"Pagina non disponibile":!intakeError.isEmpty()?"Salvataggio da riprovare":readErrors>0||dropped>0||oversized>0?"Cattura incompleta":"";
  status.setVisibility(problem.isEmpty()?View.GONE:View.VISIBLE);status.setText(problem.isEmpty()?"":problem+" · Tocca per ricaricare");
  next.setContentDescription("Pagina successiva"+(next.isEnabled()?"":loading?" · Caricamento":uiState==BrowserUiState.manualMatch?"":" · Attendi il salvataggio degli annunci"));saveReport();
 }
 private void cancelCount(){if(countMotion!=null){countMotion.removeAllListeners();countMotion.cancel();countMotion=null;}}
 private void animateCount(int target){if(counter==null)return;if(progressSummary!=null)progressSummary.setContentDescription(target+" annunci salvati nella pagina corrente");if(target==shownCount)return;if(countMotion!=null&&countMotion.isRunning()&&countTarget==target)return;cancelCount();if(!resumed||!android.animation.ValueAnimator.areAnimatorsEnabled()||target<shownCount){shownCount=target;counter.setText(String.valueOf(target));return;}android.animation.ValueAnimator motion=android.animation.ValueAnimator.ofInt(shownCount,target);countMotion=motion;countTarget=target;motion.setDuration(Math.min(800,Math.max(250,(target-shownCount)*8L)));motion.setInterpolator(new android.view.animation.AccelerateInterpolator());motion.addUpdateListener(a->{shownCount=(Integer)a.getAnimatedValue();counter.setText(String.valueOf(shownCount));});motion.addListener(new android.animation.AnimatorListenerAdapter(){@Override public void onAnimationEnd(android.animation.Animator a){if(countMotion!=motion)return;countMotion=null;shownCount=target;counter.setText(String.valueOf(target));counter.setContentDescription(target+" annunci salvati");refreshStatus();}});motion.start();}
 private void showReport(){String report;StringBuilder samples=new StringBuilder();synchronized(items){report=reportLocked();int n=0;for(JSONObject item:items.values()){if(n++>=8)break;samples.append("\n\n#").append(item.optString("id")).append(" · ").append(item.optString("title")).append("\n").append(item.optString("source")).append(" · ").append(item.opt("publication"));}}final String publicReport=report;TextView text=new TextView(this);text.setTextColor(TEXT);text.setTextSize(13);text.setPadding(dp(16),dp(16),dp(16),dp(16));text.setText("Gli annunci catturati vengono salvati per l’analisi locale. Prezzo e dati mancanti restano da acquisire; il sito può mostrare solo parte degli annunci del venditore.\n\n"+report+samples);text.setTextIsSelectable(true);ScrollView scroll=new ScrollView(this);scroll.addView(text);new AlertDialog.Builder(this).setTitle("Cattura browser · diagnostica").setView(scroll).setPositiveButton("Torna a Vinted",null).setNeutralButton("Copia report",(d,w)->{ClipboardManager clipboard=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("Diagnostica browser",publicReport));}).show();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else finish();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putString("browser_ui",uiState.name());out.putInt("price_limit",priceLimitCents);}
 @Override protected void onPause(){super.onPause();resumed=false;pageDrained=false;cancelCount();captureGeneration++;accepting=false;if(web!=null)web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled(false)",null);saveReport();}
 @Override protected void onResume(){super.onResume();resumed=true;sendBroadcast(new android.content.Intent(BrowserCapturePolicy.READY_ACTION).setPackage(getPackageName()));if(web!=null&&supported){accepting=enabled&&resumed&&!pageFailed&&VintedBrowserPolicy.allowedPage(navigationUrl);web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled("+(enabled&&resumed)+")",null);}}
 @Override protected void onDestroy(){closed=true;cancelCount();accepting=false;ingest.shutdown();if(web!=null){web.stopLoading();web.destroy();web=null;}super.onDestroy();}
}



