package it.vintedaffari.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.content.res.ColorStateList;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.webkit.CookieManager;
import android.webkit.RenderProcessGoneDetail;
import android.webkit.WebResourceRequest;
import android.webkit.WebResourceResponse;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.HorizontalScrollView;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;
import org.json.JSONArray;
import org.json.JSONObject;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

/** Public browser capture with durable local intake; no endpoint replay or automatic navigation. */
public final class VintedBrowserActivity extends Activity {
 private static final int BG=Color.rgb(10,11,20),TEXT=Color.WHITE,MUTED=Color.rgb(170,170,195);
 private final ThreadPoolExecutor ingest=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(4)){@Override protected void terminated(){if(captureDatabase!=null)captureDatabase.close();}};
 private final LinkedHashMap<String,JSONObject> items=new LinkedHashMap<>();
 private final LinkedHashSet<String> routes=new LinkedHashSet<>();
 private final AtomicInteger rejected=new AtomicInteger();
 private volatile boolean accepting,closed,resumed;
 private volatile long captureGeneration,pageGeneration;
 private boolean enabled,supported,rendererGone,pageFailed;
 private String mode,state="STARTING",expectedSeller="",lastReport="",navigationUrl="",lastSearchUrl="https://www.vinted.it/catalog/4881-board-games";
 private int updates,jsonItems,domItems,dropped,unknownShapes,readErrors,oversized;
 private DealDatabase captureDatabase;private MarketStore captureStore;
 private final LinkedHashSet<String> persistedPageIds=new LinkedHashSet<>();private volatile String intakeError="";
 private WebView web;private TextView status,previous,next;private TextView toggle,capture;private Button explore;
 private Typeface appTypeface;private boolean loading;private int pageObserved,pagePrices;private volatile boolean pageDrained;private TextView counter;private LinearLayout progressSummary;private android.animation.ValueAnimator countMotion;private int shownCount,countTarget;
 @Override public void onCreate(Bundle saved){super.onCreate(saved);mode=getIntent().getStringExtra("mode");if(!"SEARCH".equals(mode)&&!"BUNDLE".equals(mode))mode="VIEW";enabled=VintedBrowserPolicy.startsEnabled(mode);expectedSeller=getIntent().getStringExtra("expected_seller_id");if(expectedSeller==null||!expectedSeller.matches("[1-9][0-9]{0,18}"))expectedSeller="";
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(0,statusBarHeight(),0,0);setContentView(root);
  try{appTypeface=Typeface.createFromAsset(getAssets(),"fonts/remus-variable.ttf");}catch(Exception ignored){appTypeface=Typeface.create("sans-serif",Typeface.NORMAL);}
  LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(16),dp(8),dp(16),dp(8));bar.setGravity(Gravity.CENTER_VERTICAL);bar.setMinimumHeight(dp(64));
  bar.addView(icon(LudoIcons.XMARK,"Chiudi browser",this::finish),new LinearLayout.LayoutParams(dp(48),dp(48)));
  TextView title=label("Vinted",20);title.setMaxLines(1);title.setEllipsize(android.text.TextUtils.TruncateAt.END);title.setPadding(dp(12),0,dp(12),0);bar.addView(title,new LinearLayout.LayoutParams(0,-2,1));
  bar.addView(icon(LudoIcons.ELLIPSIS_VERTICAL,"Diagnostica e chiusura browser",this::showMenu),new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(bar);
  LinearLayout controls=new LinearLayout(this);controls.setPadding(dp(16),0,dp(16),dp(8));controls.setGravity(Gravity.CENTER_VERTICAL);
  explore=action("Nuova esplorazione",this::explorations);LinearLayout.LayoutParams primaryParams=new LinearLayout.LayoutParams(0,-2,1);primaryParams.rightMargin=dp(8);controls.addView(explore,primaryParams);explore.setVisibility("SEARCH".equals(mode)?View.VISIBLE:View.GONE);
  toggle=icon(enabled?LudoIcons.PAUSE:LudoIcons.PLAY,enabled?"Metti in pausa la cattura":"Riprendi la cattura",()->setCapture(!enabled));controls.addView(toggle,new LinearLayout.LayoutParams(dp(48),dp(48)));
  capture=icon(LudoIcons.CAMERA,"Cattura gli annunci della pagina visibile",this::captureNow);LinearLayout.LayoutParams captureParams=new LinearLayout.LayoutParams(dp(48),dp(48));captureParams.leftMargin=dp(8);controls.addView(capture,captureParams);root.addView(controls);
  if("SEARCH".equals(mode)){LinearLayout shortcuts=new LinearLayout(this);shortcuts.setPadding(dp(16),0,dp(16),dp(8));shortcuts.setOrientation(getResources().getConfiguration().fontScale>1.3f?LinearLayout.VERTICAL:LinearLayout.HORIZONTAL);boolean stacked=shortcuts.getOrientation()==LinearLayout.VERTICAL;shortcuts.addView(action("Sorprendimi",this::surprise),new LinearLayout.LayoutParams(stacked?-1:0,-2,stacked?0:1));LinearLayout.LayoutParams filters=new LinearLayout.LayoutParams(stacked?-1:0,-2,stacked?0:1);if(stacked)filters.topMargin=dp(8);else filters.leftMargin=dp(8);shortcuts.addView(action("Ricerca e filtri",this::customExploration),filters);root.addView(shortcuts);}
  LinearLayout progress=new LinearLayout(this);progressSummary=progress;progress.setFocusable(true);progress.setGravity(Gravity.CENTER_VERTICAL);progress.setPadding(dp(20),dp(4),dp(20),dp(4));counter=label("0",32);counter.setTypeface(appTypeface,Typeface.BOLD);counter.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);progress.addView(counter);TextView caption=label("annunci salvati",14);caption.setTextColor(MUTED);caption.setPadding(dp(12),0,0,0);progress.addView(caption);progress.setContentDescription("Annunci salvati nella pagina corrente");root.addView(progress);
  LinearLayout pages=new LinearLayout(this);pages.setPadding(dp(16),dp(4),dp(16),dp(12));pages.setGravity(Gravity.CENTER_VERTICAL);
  previous=icon(LudoIcons.CHEVRON_LEFT,"Pagina precedente",()->navigate("previous",""));pages.addView(previous,new LinearLayout.LayoutParams(dp(48),dp(48)));
  status=label("Caricamento…",13);status.setMinHeight(dp(48));status.setOnClickListener(v->{if(web!=null&&!loading&&(pageFailed||!intakeError.isEmpty()||readErrors>0||dropped>0||oversized>0)){pageDrained=false;web.reload();}});status.setTextColor(MUTED);status.setGravity(Gravity.CENTER);status.setPadding(dp(8),dp(8),dp(8),dp(8));pages.addView(status,new LinearLayout.LayoutParams(0,-2,1));
  next=icon(LudoIcons.CHEVRON_RIGHT,"Pagina successiva",()->navigate("next",""));pages.addView(next,new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(pages);

  web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));
  WebView.setWebContentsDebuggingEnabled(false);WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setSafeBrowsingEnabled(true);settings.setSupportMultipleWindows(false);settings.setJavaScriptCanOpenWindowsAutomatically(false);CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);
  web.setWebViewClient(new WebViewClient(){
   @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){if(!request.isForMainFrame())return false;boolean allowed=VintedBrowserPolicy.allowedPage(request.getUrl().toString());if(!allowed)Toast.makeText(VintedBrowserActivity.this,"Questa pagina non fa parte del test pubblico",Toast.LENGTH_SHORT).show();return !allowed;}
   @Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){observeRoute(request.getUrl());return null;}
   @Override public void onPageStarted(WebView view,String url,android.graphics.Bitmap icon){resetPage(url);loading=true;pageFailed=false;refreshStatus();if(!VintedBrowserPolicy.allowedPage(url)){view.stopLoading();state="PAGE_BLOCKED";refreshStatus();}}
   @Override public void onPageFinished(WebView view,String url){if(closed||rendererGone)return;navigationUrl=url;loading=false;if(pageFailed){accepting=false;}else if(!VintedBrowserPolicy.allowedPage(url)){state="PAGE_BLOCKED";accepting=false;}else{state=supported?(enabled?"CAPTURING":"PAUSED"):"UNSUPPORTED_PROVIDER";accepting=supported&&enabled&&resumed;if(supported)bindPage();}refreshStatus();}
   @Override public void onReceivedError(WebView view,WebResourceRequest request,android.webkit.WebResourceError error){if(request.isForMainFrame()){loading=false;pageFailed=true;accepting=false;state="PAGE_ERROR";refreshStatus();}}
   @Override public void onReceivedHttpError(WebView view,WebResourceRequest request,WebResourceResponse response){if(request.isForMainFrame()&&response.getStatusCode()>=400){loading=false;pageFailed=true;accepting=false;state="PAGE_ERROR";refreshStatus();}}
   @Override public boolean onRenderProcessGone(WebView view,RenderProcessGoneDetail detail){accepting=false;rendererGone=true;state="RENDERER_GONE";((LinearLayout)view.getParent()).removeView(view);view.destroy();web=null;refreshStatus();Toast.makeText(VintedBrowserActivity.this,"Browser interrotto. Chiudi e riapri per riprovare.",Toast.LENGTH_LONG).show();return true;}
  });
  supported=WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)&&WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER);
  try{if(supported){WebViewCompat.addWebMessageListener(web,"LudoCapture",new LinkedHashSet<>(java.util.Arrays.asList("https://www.vinted.it","https://vinted.it")),(view,message,origin,mainFrame,reply)->receive(message.getData(),origin.toString(),mainFrame,reply));String script;try(java.io.InputStream input=getAssets().open("browser/vinted-capture.js")){java.io.ByteArrayOutputStream output=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[4096];int count;while((count=input.read(buffer))!=-1)output.write(buffer,0,count);script=new String(output.toByteArray(),StandardCharsets.UTF_8);}JSONObject initial=new JSONObject();initial.put("enabled",enabled);initial.put("expectedSeller",expectedSeller);WebViewCompat.addDocumentStartJavaScript(web,"window.__LudoCaptureInitial="+initial+";\n"+script,new LinkedHashSet<>(java.util.Arrays.asList("https://www.vinted.it","https://vinted.it")));}}
  catch(Exception error){supported=false;accepting=false;state="CAPTURE_INIT_ERROR";}
  toggle.setEnabled(supported);capture.setEnabled(supported);refreshStatus();String url=getIntent().getStringExtra("url");if(!VintedBrowserPolicy.allowedPage(url))url="https://www.vinted.it/catalog/4881-board-games";if("SEARCH".equals(mode)){Uri original=Uri.parse(url);Uri.Builder b=original.buildUpon().path("/catalog/4881-board-games").clearQuery();for(String key:original.getQueryParameterNames())if(!key.equals("catalog[]")&&!key.equals("catalog_ids[]")&&!key.equals("catalog_id"))for(String value:original.getQueryParameters(key))b.appendQueryParameter(key,value);url=b.build().toString();}navigationUrl=url;accepting=supported&&enabled&&resumed;web.loadUrl(url);
 }
 private TextView label(String name,int size){TextView t=new TextView(this);t.setText(name);t.setTextSize(size);t.setTextColor(TEXT);t.setTypeface(appTypeface);t.setIncludeFontPadding(false);return t;}
 private android.graphics.drawable.Drawable capsule(){GradientDrawable shape=new GradientDrawable();shape.setColor(Color.rgb(22,26,47));shape.setCornerRadius(dp(24));shape.setStroke(dp(1),Color.rgb(43,51,100));return new RippleDrawable(ColorStateList.valueOf(Color.argb(65,164,151,255)),shape,null);}
 private TextView icon(String glyph,String description,Runnable run){TextView t=label(glyph,18);t.setTypeface(LudoIcons.solid(this));t.setGravity(Gravity.CENTER);t.setContentDescription(description);t.setBackground(new android.graphics.drawable.InsetDrawable(capsule(),dp(3)));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setOnClickListener(v->run.run());return t;}
 private Button action(String name,Runnable run){Button b=new Button(this);b.setText(name);b.setTextColor(TEXT);b.setTextSize(14);b.setTypeface(appTypeface);b.setAllCaps(false);b.setMinWidth(dp(48));b.setMinimumWidth(dp(48));b.setMinHeight(dp(56));b.setMinimumHeight(dp(56));b.setBackground(new android.graphics.drawable.InsetDrawable(capsule(),dp(3)));b.setPadding(dp(16),dp(12),dp(16),dp(12));b.setContentDescription(name);b.setOnClickListener(v->run.run());return b;}
 private android.app.Dialog sheet(String title){android.app.Dialog dialog=new android.app.Dialog(this);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(20),dp(20),dp(24));box.setBackground(capsule());TextView heading=label(title,24);heading.setTypeface(appTypeface,Typeface.BOLD);heading.setPadding(0,0,0,dp(16));box.addView(heading);scroll.addView(box);dialog.setContentView(scroll);dialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);dialog.getWindow().setGravity(Gravity.BOTTOM);dialog.getWindow().setLayout(-1,-2);box.setTag(dialog);return dialog;}
 private LinearLayout sheetBody(android.app.Dialog dialog){return (LinearLayout)((ScrollView)((android.widget.FrameLayout)dialog.findViewById(android.R.id.content)).getChildAt(0)).getChildAt(0);}
 private void choice(LinearLayout box,String glyph,String title,String description,Runnable run){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(16),dp(16),dp(16),dp(16));row.setMinimumHeight(dp(72));row.setBackground(capsule());TextView symbol=label(glyph,22);symbol.setTypeface(LudoIcons.solid(this));row.addView(symbol,new LinearLayout.LayoutParams(dp(36),dp(36)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);TextView name=label(title,17);name.setTypeface(appTypeface,Typeface.BOLD);copy.addView(name);TextView detail=label(description,13);detail.setTextColor(MUTED);detail.setPadding(0,dp(4),0,0);copy.addView(detail);row.addView(copy,new LinearLayout.LayoutParams(0,-2,1));row.setContentDescription(title+". "+description);row.setFocusable(true);row.setOnClickListener(v->run.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(8);box.addView(row,lp);}
 private void explorations(){android.app.Dialog dialog=sheet("Nuova esplorazione");LinearLayout box=sheetBody(dialog);choice(box,LudoIcons.SEARCH,"Esplora tutti i giochi","Gli annunci più rilevanti",()->{dialog.dismiss();loadExploration("","relevance",0,0);});choice(box,LudoIcons.CLOCK,"Appena pubblicati","Scopri le novità",()->{dialog.dismiss();loadExploration("","newest_first",0,0);});choice(box,LudoIcons.STAR,"Piccoli prezzi","Giochi fino a 5 €",()->{dialog.dismiss();loadExploration("","relevance",0,500);});choice(box,LudoIcons.SEARCH,"Cerca un gioco","Nome, prezzo e ordine",()->{dialog.dismiss();customExploration();});dialog.show();dialog.getWindow().setLayout(-1,-2);}
 private void loadExploration(String query,String order,int minimum,int maximum){String url=ExplorationPlan.url(query,order,minimum,maximum);if(url.isEmpty()){Toast.makeText(this,"Controlla nome e intervallo di prezzo",Toast.LENGTH_SHORT).show();return;}if(closed||web==null||loading)return;loading=true;pageFailed=false;refreshStatus();web.loadUrl(url);}
 private void surprise(){if(closed||web==null||loading)return;try{ingest.execute(()->{String query="";try(DealDatabase lookup=new DealDatabase(getApplicationContext())){query=lookup.randomExplorationTitle();}catch(RuntimeException ignored){}final String title=query;java.util.Random random=new java.util.Random();String order=random.nextBoolean()?"relevance":"newest_first";int max=new int[]{0,100,200,500,1000,2000}[random.nextInt(6)];runOnUiThread(()->{if(!closed){if(title.isEmpty())Toast.makeText(this,"Esploro il catalogo generale con filtri casuali",Toast.LENGTH_SHORT).show();loadExploration(title,order,0,max);}});});}catch(java.util.concurrent.RejectedExecutionException busy){Toast.makeText(this,"Sto salvando gli annunci. Riprova tra poco.",Toast.LENGTH_SHORT).show();}}
 private EditText field(String hint,boolean price){EditText input=new EditText(this);input.setHint(hint);input.setContentDescription(hint);input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setTypeface(appTypeface);input.setTextSize(16);input.setSingleLine(true);input.setMinHeight(dp(56));input.setPadding(dp(16),dp(12),dp(16),dp(12));if(price)input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);return input;}
 private void customExploration(){android.app.Dialog dialog=sheet("Ricerca e filtri");LinearLayout form=sheetBody(dialog);EditText term=field("Gioco, oppure tutti i giochi",false);term.setText(Uri.parse(lastSearchUrl).getQueryParameter("search_text"));form.addView(term);EditText minimum=field("Prezzo minimo € · facoltativo",true),maximum=field("Prezzo massimo € · facoltativo",true);minimum.setText(Uri.parse(lastSearchUrl).getQueryParameter("price_from"));maximum.setText(Uri.parse(lastSearchUrl).getQueryParameter("price_to"));form.addView(minimum);form.addView(maximum);TextView caption=label("Ordina gli annunci",16);caption.setTypeface(appTypeface,Typeface.BOLD);caption.setPadding(0,dp(20),0,dp(8));form.addView(caption);android.widget.RadioGroup order=new android.widget.RadioGroup(this);String[] orders={"Rilevanza","Appena pubblicati","Prezzo crescente","Prezzo decrescente"},keys={"relevance","newest_first","price_low_to_high","price_high_to_low"};String currentOrder=Uri.parse(lastSearchUrl).getQueryParameter("order");int selected=0;for(int i=0;i<orders.length;i++){android.widget.RadioButton option=new android.widget.RadioButton(this);option.setId(100+i);option.setText(orders[i]);option.setTypeface(appTypeface);option.setTextColor(TEXT);option.setTextSize(16);option.setButtonTintList(ColorStateList.valueOf(Color.rgb(164,151,255)));option.setMinHeight(dp(48));option.setPadding(dp(12),dp(8),dp(12),dp(8));order.addView(option);if(keys[i].equals(currentOrder))selected=i;}order.check(100+selected);order.setContentDescription("Ordine degli annunci");form.addView(order);Button begin=action("Esplora",()->{try{String lo=minimum.getText().toString().trim(),hi=maximum.getText().toString().trim();int min=lo.isEmpty()?0:new java.math.BigDecimal(lo.replace(',','.')).movePointRight(2).intValueExact(),max=hi.isEmpty()?0:new java.math.BigDecimal(hi.replace(',','.')).movePointRight(2).intValueExact();String query=term.getText().toString().trim(),sort=keys[order.getCheckedRadioButtonId()-100];if(ExplorationPlan.url(query,sort,min,max).isEmpty())throw new IllegalArgumentException();dialog.dismiss();loadExploration(query,sort,min,max);}catch(RuntimeException invalid){maximum.setError("Prezzi validi, massimo non inferiore al minimo");maximum.requestFocus();}});LinearLayout.LayoutParams buttonParams=new LinearLayout.LayoutParams(-1,-2);buttonParams.topMargin=dp(20);form.addView(begin,buttonParams);form.addView(action("Annulla",dialog::dismiss));dialog.show();dialog.getWindow().setLayout(-1,-2);dialog.getWindow().setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}
 private void search(){EditText input=new EditText(this);input.setSingleLine(true);input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setHint("Nome del gioco");LinearLayout form=new LinearLayout(this);form.setPadding(dp(16),dp(12),dp(16),dp(12));form.addView(input,new LinearLayout.LayoutParams(-1,-2));new AlertDialog.Builder(this).setTitle("Cerca giochi su Vinted").setView(form).setNegativeButton("Annulla",null).setPositiveButton("Cerca",(d,w)->{String value=input.getText().toString().trim().replace("\n"," ");if(value.length()<=100)navigate("search",value);}).show();}
 private void sort(){new AlertDialog.Builder(this).setTitle("Ordina annunci").setItems(new String[]{"Appena pubblicati","Rilevanza","Prezzo crescente","Prezzo decrescente"},(d,n)->navigate("order",new String[]{"newest_first","relevance","price_low_to_high","price_high_to_low"}[n])).show();}
 private void minimumPrice(){new AlertDialog.Builder(this).setTitle("Prezzo minimo").setItems(new String[]{"Aumenta di 1 €","Riduci di 1 €"},(d,n)->navigate(n==0?"pricePlus":"priceMinus","")).show();}
 private void showMenu(){android.app.Dialog dialog=sheet("Opzioni browser");LinearLayout box=sheetBody(dialog);choice(box,LudoIcons.CAMERA,"Dati della cattura","Controlla gli annunci acquisiti",()->{dialog.dismiss();showReport();});choice(box,LudoIcons.XMARK,"Chiudi browser","Torna a Ludo",()->{dialog.dismiss();finish();});dialog.show();dialog.getWindow().setLayout(-1,-2);}
 private void navigate(String command,String argument){if(web==null||loading||pageFailed||!supported||("next".equals(command)&&!next.isEnabled()))return;final long token=pageGeneration;final String page=navigationUrl;String gate="next".equals(command)?"window.LudoCaptureControl.canAdvance("+token+")&&":"";String script="window.LudoCaptureControl?("+gate+"window.LudoCaptureControl.navigationUrl("+JSONObject.quote(command)+","+JSONObject.quote(argument)+","+JSONObject.quote(lastSearchUrl)+")):null";web.evaluateJavascript(script,result->{if(closed||web==null||loading||token!=pageGeneration||!samePage(page,navigationUrl))return;try{Object value=new org.json.JSONTokener(result).nextValue();if(value instanceof String&&VintedBrowserPolicy.allowedPage((String)value)){loading=true;pageDrained=false;refreshStatus();web.loadUrl((String)value);}else if("next".equals(command)){pageDrained=false;refreshStatus();}}catch(Exception ignored){}});}
 private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 private int statusBarHeight(){int id=getResources().getIdentifier("status_bar_height","dimen","android");return id==0?0:getResources().getDimensionPixelSize(id);}
 private void setCapture(boolean value){if(!supported||web==null)return;captureGeneration++;pageDrained=false;enabled=value;accepting=value&&resumed&&!pageFailed&&VintedBrowserPolicy.allowedPage(navigationUrl);state=value?"CAPTURING":"PAUSED";web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled("+value+")",null);refreshStatus();}
 private void captureNow(){if(!supported||web==null||!resumed||pageFailed||!VintedBrowserPolicy.allowedPage(web.getUrl()))return;captureGeneration++;pageDrained=false;accepting=true;web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.captureNow("+captureGeneration+")",null);}
 private void resetPage(String url){pageDrained=false;cancelCount();shownCount=0;if(counter!=null)counter.setText("0");accepting=false;captureGeneration++;pageGeneration++;navigationUrl=url;if(Uri.parse(url).getPath()!=null&&Uri.parse(url).getPath().startsWith("/catalog"))lastSearchUrl=url;synchronized(items){items.clear();persistedPageIds.clear();updates=0;jsonItems=0;domItems=0;dropped=0;unknownShapes=0;readErrors=0;oversized=0;pageObserved=0;pagePrices=0;intakeError="";}}
 private void bindPage(){if(web==null||!supported)return;accepting=enabled&&resumed&&!pageFailed;web.evaluateJavascript("if(window.LudoCaptureControl){window.LudoCaptureControl.setPageToken("+pageGeneration+");window.LudoCaptureControl.setEnabled("+(enabled&&resumed)+");}",null);}
 private static String messageSequence(String data){if(data==null)return "0";java.util.regex.Matcher m=java.util.regex.Pattern.compile("\"seq\":([0-9]+)").matcher(data.substring(0,Math.min(100,data.length())));return m.find()?m.group(1):"0";}
 private void receive(String data,String origin,boolean mainFrame,androidx.webkit.JavaScriptReplyProxy reply){if(data!=null&&data.length()<=5000&&data.startsWith("{\"kind\":\"location\"")){try{if(closed||web==null||!VintedBrowserPolicy.allowedMessage(origin,mainFrame,data.getBytes(StandardCharsets.UTF_8).length))return;String url=new JSONObject(data).optString("url");if(VintedBrowserPolicy.allowedPage(url)&&samePage(url,web.getUrl())&&!samePage(url,navigationUrl)){resetPage(url);loading=false;pageFailed=false;bindPage();refreshStatus();}}catch(Exception ignored){}return;}if(closed||!accepting||data==null||data.length()>128*1024||web==null||!VintedBrowserPolicy.allowedPage(navigationUrl)){rejected.incrementAndGet();reply.postMessage("paused:"+messageSequence(data));return;}int bytes=data.getBytes(StandardCharsets.UTF_8).length;if(!VintedBrowserPolicy.allowedMessage(origin,mainFrame,bytes)){rejected.incrementAndGet();return;}pageDrained=false;refreshStatus();final long generation=captureGeneration,acceptedPageToken=pageGeneration;final String acceptedPageUrl=navigationUrl;try{ingest.execute(()->{boolean persisted=parse(data,generation,acceptedPageUrl,acceptedPageToken);runOnUiThread(()->{if(!closed)reply.postMessage((persisted?"ready:":"retry:")+messageSequence(data));});});}catch(java.util.concurrent.RejectedExecutionException error){rejected.incrementAndGet();reply.postMessage("retry:"+messageSequence(data));}}
 private boolean parse(String data,long generation,String acceptedPageUrl,long acceptedPageToken){try{
  java.util.List<JSONObject> captured=new java.util.ArrayList<>();JSONObject packet=new JSONObject(data);JSONArray incoming=packet.optJSONArray("items");if(packet.optInt("schema")!=1||incoming==null||incoming.length()>32){rejected.incrementAndGet();return true;}
  JSONObject page=packet.optJSONObject("page");if(page==null||!samePage(page.optString("url"),acceptedPageUrl)){rejected.incrementAndGet();return true;}
  synchronized(items){if(!samePage(page.optString("url"),acceptedPageUrl)||packet.optLong("pageToken",-1)!=acceptedPageToken)return true;boolean currentPage=acceptedPageToken==pageGeneration;if(currentPage){pageObserved=bound(page.optInt("observed"));pagePrices=bound(page.optInt("withPrice"));}for(int i=0;i<incoming.length();i++){JSONObject item=incoming.optJSONObject(i);if(item==null||!VintedBrowserPolicy.matchesItem(item.optString("url"),item.optString("id"))||item.optString("title").length()>600){rejected.incrementAndGet();continue;}String id=item.getString("id");if(currentPage&&!items.containsKey(id)&&items.size()>=500){dropped++;continue;}JSONObject clean=new JSONObject();for(String key:new String[]{"id","url","title","priceCents","protectedPriceCents","brand","condition","currency","sellerId","sellerName","description","language","publication","source","photos"}){Object value=item.opt(key);if(value==null||value==JSONObject.NULL)continue;if(value instanceof String&&((String)value).length()<=("description".equals(key)?2000:600))clean.put(key,value);else if(("priceCents".equals(key)||"protectedPriceCents".equals(key))&&value instanceof Number&&((Number)value).longValue()>0&&((Number)value).longValue()<=1000000000L)clean.put(key,value);else if("photos".equals(key)&&value instanceof JSONArray){JSONArray photos=new JSONArray();JSONArray source=(JSONArray)value;for(int n=0;n<Math.min(10,source.length());n++){String url=BrowserCapturePolicy.photo(source.optString(n));if(!url.isEmpty())photos.put(url);}if(photos.length()>0)clean.put(key,photos);}else if("publication".equals(key)&&value instanceof JSONObject){JSONObject p=(JSONObject)value;if(p.optString("raw").length()<=100&&p.optString("source").length()<=50)clean.put(key,new JSONObject().put("raw",p.optString("raw")).put("source",p.optString("source")));}}
   captured.add(clean);if(currentPage){JSONObject previous=items.get(id);if(previous!=null&&!previous.toString().equals(clean.toString()))updates++;items.put(id,clean);if("dom".equals(clean.optString("source")))domItems++;else jsonItems++;}}
   JSONObject stats=packet.optJSONObject("stats");if(currentPage&&stats!=null){dropped=Math.max(dropped,bound(stats.optInt("dropped")));unknownShapes=Math.max(unknownShapes,bound(stats.optInt("unknownShapes")));readErrors=Math.max(readErrors,bound(stats.optInt("readErrors")));oversized=Math.max(oversized,bound(stats.optInt("oversized")));}lastReport=reportLocked();}
  boolean persistedAll=true;String batchError="";if(!captured.isEmpty()){if(captureDatabase==null){captureDatabase=new DealDatabase(getApplicationContext());captureStore=new MarketStore(getApplicationContext(),captureDatabase);}for(JSONObject item:captured){try{long persisted=captureStore.captureBrowserItem(item,System.currentTimeMillis());if(persisted>0)synchronized(items){if(packet.optLong("pageToken",-1)==pageGeneration)persistedPageIds.add(item.optString("id"));} }catch(Exception failure){persistedAll=false;batchError=failure.getClass().getSimpleName();}}sendBroadcast(new android.content.Intent(BrowserCapturePolicy.READY_ACTION).setPackage(getPackageName()));sendBroadcast(new android.content.Intent("it.vintedaffari.app.DEALS_UPDATED").setPackage(getPackageName()));}
  final String currentError=batchError;final boolean persisted=persistedAll;boolean complete=packet.optBoolean("complete");saveReport();runOnUiThread(()->{if(!closed){if(acceptedPageToken==pageGeneration&&generation==captureGeneration){intakeError=currentError;pageDrained=persisted&&packet.optBoolean("settled")&&dropped==0&&readErrors==0&&oversized==0&&intakeError.isEmpty();}if(persisted&&complete&&!enabled&&packet.optLong("captureToken",-1)==captureGeneration&&generation==captureGeneration)accepting=false;refreshStatus();}});
 return persistedAll;}catch(Exception error){if(acceptedPageToken==pageGeneration&&generation==captureGeneration)intakeError=error.getClass().getSimpleName();rejected.incrementAndGet();return false;}}
 private static boolean samePage(String a,String b){try{return Uri.parse(a).buildUpon().fragment(null).build().equals(Uri.parse(b).buildUpon().fragment(null).build());}catch(Exception e){return false;}}
 private static int bound(int n){return Math.max(0,Math.min(1000000,n));}
 private void observeRoute(Uri uri){if(uri==null||!"https".equals(uri.getScheme())||!("www.vinted.it".equals(uri.getHost())||"vinted.it".equals(uri.getHost())))return;String path=uri.getPath();if(path==null||!path.startsWith("/api/"))return;path=path.replaceAll("[0-9]+","{id}").replaceAll("[^a-zA-Z0-9/{}_\\-]","_");if(path.length()>160)path=path.substring(0,160);synchronized(routes){if(routes.size()<20)routes.add(path);}}
 private String reportLocked(){int price=0,seller=0,publication=0,language=0;for(JSONObject item:items.values()){if(item.has("priceCents"))price++;if(item.has("sellerId"))seller++;if(item.has("publication"))publication++;if(item.has("language"))language++;}String routeSummary;synchronized(routes){routeSummary=routes.toString();}return "build=browser-engine-intake-v1;app="+BuildConfig.VERSION_NAME+";state="+state+";mode="+mode+";features="+supported+";capture="+enabled+";scope=currentPage;page="+pageNumber()+";pageObserved="+pageObserved+";pagePrices="+pagePrices+";acquiredUnique="+items.size()+";updated="+updates+";price="+price+";seller="+seller+";publication="+publication+";language="+language+";jsonOrInitial="+jsonItems+";dom="+domItems+";dropped="+dropped+";unknownShapes="+unknownShapes+";readErrors="+readErrors+";oversized="+oversized+";rejected="+rejected.get()+";extraRequestsByCapture=0;networkScope=capturer-only;catalogWrites="+persistedPageIds.size()+";intakeScope=currentPage;pageDrained="+pageDrained+";intakeError="+intakeError+";sellerCoverage=partial;routes="+routeSummary;}
 private void saveReport(){String report; synchronized(items){report=reportLocked();lastReport=report;}getSharedPreferences("vinted_browser_experiment",MODE_PRIVATE).edit().putString("report",report).putLong("at",System.currentTimeMillis()).apply();}
 private int pageNumber(){try{return Math.max(1,Math.min(10,Integer.parseInt(Uri.parse(navigationUrl).getQueryParameter("page"))));}catch(Exception ignored){return 1;}}
 private static boolean captureReady(boolean enabled,boolean pageDrained,int saved,int observed,int acquired,String error,boolean animating){return enabled&&pageDrained&&saved==observed&&acquired==observed&&error.isEmpty()&&!animating;}
 private void refreshStatus(){int size,price,saved; synchronized(items){size=items.size();saved=persistedPageIds.size();price=0;for(JSONObject x:items.values())if(x.has("priceCents"))price++;}if(status==null)return;toggle.setText(enabled?LudoIcons.PAUSE:LudoIcons.PLAY);toggle.setContentDescription(enabled?"Metti in pausa la cattura":"Riprendi la cattura");toggle.setEnabled(supported&&!rendererGone&&web!=null);explore.setEnabled(!loading&&!rendererGone&&web!=null);boolean catalog=Uri.parse(navigationUrl).getPath()!=null&&Uri.parse(navigationUrl).getPath().startsWith("/catalog");animateCount(saved);previous.setEnabled(supported&&catalog&&!loading&&!pageFailed&&pageNumber()>1);next.setEnabled(supported&&catalog&&!loading&&!pageFailed&&pageNumber()<10&&captureReady(enabled,pageDrained,saved,pageObserved,size,intakeError,countMotion!=null&&countMotion.isRunning()));previous.setAlpha(previous.isEnabled()?1f:.35f);next.setAlpha(next.isEnabled()?1f:.35f);capture.setEnabled(supported&&!loading&&!pageFailed&&web!=null);String minimum=Uri.parse(navigationUrl).getQueryParameter("price_from");String order=Uri.parse(navigationUrl).getQueryParameter("order");String orderLabel="newest_first".equals(order)?" · Nuovi":"price_low_to_high".equals(order)?" · Prezzo ↑":"price_high_to_low".equals(order)?" · Prezzo ↓":" · Rilevanza";String maximum=Uri.parse(navigationUrl).getQueryParameter("price_to"),query=Uri.parse(navigationUrl).getQueryParameter("search_text");String context=catalog?"Pagina "+pageNumber()+" / 10"+orderLabel+(minimum==null?"":" · da "+minimum+" €")+(maximum==null?"":" · fino a "+maximum+" €")+(query==null||query.isEmpty()?"":"\n"+query):"Annuncio / venditore";status.setText(!supported?"Cattura non disponibile su questa WebView":rendererGone?"Browser interrotto":pageFailed||state.equals("PAGE_BLOCKED")?"Pagina non disponibile per la cattura":loading?"Caricamento…":context+"\n"+(enabled?(pageDrained?"Annunci caricati salvati":"Ludo sta leggendo…"):"Cattura in pausa · riprendi per continuare")+(!intakeError.isEmpty()?"\nSalvataggio da riprovare":"")+(dropped>0?"\nLimite cattura raggiunto · "+dropped+" eventi scartati":"")+((pageFailed||!intakeError.isEmpty()||readErrors>0||dropped>0||oversized>0)?"\nTocca qui per ricaricare la pagina":""));saveReport();}
 private void cancelCount(){if(countMotion!=null){countMotion.removeAllListeners();countMotion.cancel();countMotion=null;}}
 private void animateCount(int target){if(counter==null)return;if(progressSummary!=null)progressSummary.setContentDescription(target+" annunci salvati nella pagina corrente");if(target==shownCount)return;if(countMotion!=null&&countMotion.isRunning()&&countTarget==target)return;cancelCount();if(!resumed||!android.animation.ValueAnimator.areAnimatorsEnabled()||target<shownCount){shownCount=target;counter.setText(String.valueOf(target));return;}android.animation.ValueAnimator motion=android.animation.ValueAnimator.ofInt(shownCount,target);countMotion=motion;countTarget=target;motion.setDuration(Math.min(800,Math.max(250,(target-shownCount)*8L)));motion.setInterpolator(new android.view.animation.AccelerateInterpolator());motion.addUpdateListener(a->{shownCount=(Integer)a.getAnimatedValue();counter.setText(String.valueOf(shownCount));});motion.addListener(new android.animation.AnimatorListenerAdapter(){@Override public void onAnimationEnd(android.animation.Animator a){if(countMotion!=motion)return;countMotion=null;shownCount=target;counter.setText(String.valueOf(target));counter.setContentDescription(target+" annunci salvati");refreshStatus();}});motion.start();}
 private void showReport(){String report;StringBuilder samples=new StringBuilder();synchronized(items){report=reportLocked();int n=0;for(JSONObject item:items.values()){if(n++>=8)break;samples.append("\n\n#").append(item.optString("id")).append(" · ").append(item.optString("title")).append("\n").append(item.optString("source")).append(" · ").append(item.opt("publication"));}}final String publicReport=report;TextView text=new TextView(this);text.setTextColor(TEXT);text.setTextSize(13);text.setPadding(dp(16),dp(16),dp(16),dp(16));text.setText("Gli annunci catturati vengono salvati per l’analisi locale. Prezzo e dati mancanti restano da acquisire; il sito può mostrare solo parte degli annunci del venditore.\n\n"+report+samples);text.setTextIsSelectable(true);ScrollView scroll=new ScrollView(this);scroll.addView(text);new AlertDialog.Builder(this).setTitle("Cattura browser · diagnostica").setView(scroll).setPositiveButton("Torna a Vinted",null).setNeutralButton("Copia report",(d,w)->{ClipboardManager clipboard=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("Diagnostica browser",publicReport));}).show();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else finish();}
 @Override protected void onPause(){super.onPause();resumed=false;pageDrained=false;cancelCount();captureGeneration++;accepting=false;if(web!=null)web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled(false)",null);saveReport();}
 @Override protected void onResume(){super.onResume();resumed=true;sendBroadcast(new android.content.Intent(BrowserCapturePolicy.READY_ACTION).setPackage(getPackageName()));if(web!=null&&supported){accepting=enabled&&resumed&&!pageFailed&&VintedBrowserPolicy.allowedPage(navigationUrl);web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled("+(enabled&&resumed)+")",null);}}
 @Override protected void onDestroy(){closed=true;cancelCount();accepting=false;ingest.shutdown();if(web!=null){web.stopLoading();web.destroy();web=null;}super.onDestroy();}
}


