package it.vintedaffari.app;

import android.app.Activity;
import android.app.Dialog;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.*;
import android.net.Uri;
import android.text.TextUtils;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.content.Context;
import android.widget.*;
import java.math.BigDecimal;
import java.util.*;

/** Native Catalog vocabulary. Only selected filters are chips; navigation requires a gesture. */
public final class VintedBrowserControls {
 public interface Listener {void onNavigate(String url);void onCapture();void onToggle();void onOpenEngine(long captureId);void onClose();void onMenu();}
 public static final class State {
  public String permittedURL="https://www.vinted.it/catalog/4881-board-games",query="",order="relevance",message="";
  public Integer minCents,maxCents;public int page=1,committed,withPrice,incomplete,pending;public long captureId;
  public boolean loading,capture,supported,catalog=true;
 }
 private static final int BG=Color.rgb(10,11,20),SURFACE=Color.rgb(22,26,47),OUTLINE=Color.rgb(43,51,100),MUTED=Color.rgb(142,148,177),ACCENT=Color.rgb(164,151,255),WHITE=Color.WHITE;
 private static final String[] ORDERS={"relevance","newest_first","price_low_to_high","price_high_to_low"},ORDER_NAMES={"Rilevanza","Appena pubblicati","Prezzo crescente","Prezzo decrescente"};
 private final Activity activity;private final Listener listener;private final LinearLayout root,chipRow;private final EditText search;
 private final TextView previous,next,pageLabel,sort,filter,toggle,capture,engine,status;private final HorizontalScrollView chips;private final Typeface font;
 private State state=new State();private Dialog sheet;
 public VintedBrowserControls(Activity activity,Listener listener){
  this.activity=activity;this.listener=listener;Typeface face;try{face=Typeface.createFromAsset(activity.getAssets(),"fonts/remus-variable.ttf");}catch(Exception e){face=Typeface.DEFAULT;}font=face;
  root=column();root.setBackgroundColor(BG);root.setPadding(dp(16),dp(8),dp(16),dp(12));
  LinearLayout header=row();header.addView(icon(LudoIcons.XMARK,"Chiudi browser",WHITE,false,listener::onClose),params(48,48));TextView title=text("Vinted",20,WHITE,true);title.setMaxLines(1);title.setEllipsize(TextUtils.TruncateAt.END);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));
  capture=icon(LudoIcons.CAMERA,"Cattura questa pagina",MUTED,false,listener::onCapture);header.addView(capture,params(48,48));toggle=icon("\uf04c","Metti in pausa la cattura",ACCENT,false,listener::onToggle);header.addView(toggle,params(48,48));header.addView(icon(LudoIcons.ELLIPSIS_VERTICAL,"Menu browser",WHITE,false,listener::onMenu),params(48,48));root.addView(header);
  LinearLayout searchRow=row();LinearLayout pill=row();pill.setPadding(dp(12),0,dp(8),0);pill.setBackground(shape(SURFACE,27,true));TextView magnify=icon(LudoIcons.SEARCH,"Cerca su Vinted",MUTED,false,this::submitSearch);pill.addView(magnify,params(30,48));search=new EditText(activity);search.setTypeface(font);search.setTextSize(16);search.setTextColor(WHITE);search.setHintTextColor(MUTED);search.setHint("Cerca giochi da tavolo");search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(8),0,0,0);search.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);search.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){submitSearch();return true;}return false;});pill.addView(search,new LinearLayout.LayoutParams(0,dp(54),1));TextView clear=icon(LudoIcons.XMARK,"Cancella testo di ricerca",MUTED,false,()->search.setText(""));pill.addView(clear,params(32,48));searchRow.addView(pill,new LinearLayout.LayoutParams(0,dp(54),1));filter=icon(LudoIcons.SLIDERS,"Filtri di ricerca",WHITE,true,this::showFilters);LinearLayout.LayoutParams fp=params(54,54);fp.leftMargin=dp(10);searchRow.addView(filter,fp);LinearLayout.LayoutParams sr=new LinearLayout.LayoutParams(-1,-2);sr.topMargin=dp(12);root.addView(searchRow,sr);
  chips=new HorizontalScrollView(activity);chips.setHorizontalScrollBarEnabled(false);chips.setFillViewport(false);chipRow=row();chips.addView(chipRow);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(8);root.addView(chips,cp);
  LinearLayout options=row();sort=text("Rilevanza",13,MUTED,false);sort.setMinHeight(dp(48));sort.setGravity(Gravity.CENTER_VERTICAL);sort.setCompoundDrawablesWithIntrinsicBounds(LudoIcons.drawable(activity,LudoIcons.SORT,MUTED,dp(16)),null,null,null);sort.setCompoundDrawablePadding(dp(8));sort.setContentDescription("Ordina risultati");sort.setOnClickListener(v->showSort());options.addView(sort,new LinearLayout.LayoutParams(0,-2,1));previous=icon(LudoIcons.CHEVRON_LEFT,"Pagina precedente",MUTED,false,()->navigate(state.query,state.order,state.minCents,state.maxCents,state.page-1));options.addView(previous,params(48,48));pageLabel=text("1 / 10",13,WHITE,true);pageLabel.setGravity(Gravity.CENTER);pageLabel.setMaxLines(1);options.addView(pageLabel,params(56,48));next=icon(LudoIcons.CHEVRON_RIGHT,"Pagina successiva",BG,true,()->navigate(state.query,state.order,state.minCents,state.maxCents,state.page+1));next.setBackground(ripple(ACCENT,16,false));options.addView(next,params(48,48));root.addView(options);
  LinearLayout intake=row();intake.setPadding(dp(12),dp(8),dp(4),dp(8));intake.setBackground(shape(SURFACE,16,true));status=text("Attendo gli annunci…",12,MUTED,false);status.setMaxLines(3);intake.addView(status,new LinearLayout.LayoutParams(0,-2,1));engine=icon(LudoIcons.GEAR,"Apri Motore",ACCENT,false,()->listener.onOpenEngine(state.captureId));intake.addView(engine,params(48,48));root.addView(intake);render(state);
 }
 public View view(){return root;}
 public void render(State model){state=model;if(!search.hasFocus()&&!search.getText().toString().equals(model.query))search.setText(model.query);sort.setText(orderName(model.order));pageLabel.setText(model.catalog?model.page+" / 10":"—");enable(previous,model.catalog&&!model.loading&&model.page>1);enable(next,model.catalog&&!model.loading&&model.page<10);enable(capture,model.supported&&!model.loading);enable(toggle,model.supported);enable(engine,model.captureId>0);enable(sort,model.catalog&&!model.loading);enable(filter,model.catalog&&!model.loading);LudoIcons.apply(toggle,model.capture?"\uf04c":"\uf04b",18,ACCENT,false);toggle.setContentDescription(model.capture?"Metti in pausa la cattura":"Attiva cattura");status.setText(!model.message.isEmpty()?model.message:model.loading?"Caricamento pagina…":model.committed>0?model.committed+" acquisiti · "+model.withPrice+" con prezzo"+(model.incomplete>0?"\n"+model.incomplete+" con dati da completare":""):(model.capture?"Cattura attiva · attendo gli annunci":"Cattura in pausa"));renderChips();}
 private void renderChips(){chipRow.removeAllViews();int count=0;if(state.minCents!=null){chip("Da "+euros(state.minCents)+" €",()->navigate(state.query,state.order,null,state.maxCents,1));count++;}if(state.maxCents!=null){chip("Fino a "+euros(state.maxCents)+" €",()->navigate(state.query,state.order,state.minCents,null,1));count++;}Uri url=Uri.parse(state.permittedURL);for(String key:url.getQueryParameterNames())if(extraFilter(key)){final String field=key;List<String> values=url.getQueryParameters(key);String label=filterName(key);chip(label+" ("+values.size()+")",()->removeExtra(field));count+=values.size();}chips.setVisibility(count==0?View.GONE:View.VISIBLE);filter.setContentDescription(count>0?"Filtri di ricerca, "+count+" selezionati":"Filtri di ricerca");filter.setCompoundDrawables(null,null,null,null);filter.setText(count>0?LudoIcons.SLIDERS+" · "+count:LudoIcons.SLIDERS);filter.setTextSize(count>0?15:20);}
 private void chip(String label,Runnable action){TextView chip=text(label,12,WHITE,false);chip.setMinHeight(dp(48));chip.setGravity(Gravity.CENTER);chip.setPadding(dp(12),0,dp(12),0);chip.setCompoundDrawablesWithIntrinsicBounds(null,null,LudoIcons.drawable(activity,LudoIcons.XMARK,MUTED,dp(12)),null);chip.setCompoundDrawablePadding(dp(8));chip.setBackground(ripple(SURFACE,24,true));chip.setContentDescription("Rimuovi filtro "+label);chip.setOnClickListener(v->action.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.rightMargin=dp(8);chipRow.addView(chip,p);}
 private static boolean extraFilter(String key){return !Arrays.asList("search_text","order","price_from","price_to","page","per_page","catalog[]","catalog_ids[]","catalog_id").contains(key);}
 private static String filterName(String key){if(key.startsWith("brand"))return "Marca";if(key.startsWith("status"))return "Condizioni";if(key.startsWith("size"))return "Formato";if(key.startsWith("color"))return "Colore";return "Filtro Vinted";}
 private void removeExtra(String key){Uri uri=Uri.parse(state.permittedURL);Uri.Builder b=uri.buildUpon().clearQuery();for(String name:uri.getQueryParameterNames())if(!key.equals(name))for(String value:uri.getQueryParameters(name))b.appendQueryParameter(name,value);String url=BrowserSearchNavigation.build(b.build().toString(),state.query,state.order,state.minCents,state.maxCents,1);listener.onNavigate(url);}
 private void submitSearch(){navigate(search.getText().toString().trim(),state.order,state.minCents,state.maxCents,1);search.clearFocus();InputMethodManager keyboard=(InputMethodManager)activity.getSystemService(Context.INPUT_METHOD_SERVICE);if(keyboard!=null)keyboard.hideSoftInputFromWindow(search.getWindowToken(),0);}
 private void navigate(String query,String order,Integer min,Integer max,int page){if(state.loading)return;try{listener.onNavigate(BrowserSearchNavigation.build(state.permittedURL,query,order,min,max,page));}catch(IllegalArgumentException e){Toast.makeText(activity,e.getMessage(),Toast.LENGTH_SHORT).show();}}
 private void showSort(){LinearLayout box=sheet("Ordina risultati");for(int i=0;i<ORDERS.length;i++){final String order=ORDERS[i];TextView choice=text(ORDER_NAMES[i],16,order.equals(state.order)?ACCENT:WHITE,order.equals(state.order));choice.setMinHeight(dp(54));choice.setGravity(Gravity.CENTER_VERTICAL);choice.setOnClickListener(v->{sheet.dismiss();navigate(state.query,order,state.minCents,state.maxCents,1);});box.addView(choice);}sheet.show();sizeSheet();}
 private void showFilters(){LinearLayout box=sheet("Filtri di ricerca");TextView context=text("Giochi da tavolo",13,MUTED,false);context.setPadding(0,0,0,dp(16));box.addView(context);box.addView(text("Prezzo articolo",16,WHITE,true));LinearLayout range=row();EditText min=priceInput("Minimo",state.minCents),max=priceInput("Massimo",state.maxCents);range.addView(min,new LinearLayout.LayoutParams(0,dp(54),1));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,dp(54),1);mp.leftMargin=dp(12);range.addView(max,mp);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.topMargin=dp(12);rp.bottomMargin=dp(16);box.addView(range,rp);TextView error=text("",13,Color.rgb(255,133,143),false);box.addView(error);Button apply=button("Applica filtri",true);apply.setContentDescription("Applica filtri");apply.setOnClickListener(v->{try{Integer low=readPrice(min),high=readPrice(max);String url=BrowserSearchNavigation.build(state.permittedURL,state.query,state.order,low,high,1);sheet.dismiss();listener.onNavigate(url);}catch(IllegalArgumentException e){error.setText("Inserisci un intervallo di prezzo valido.");}});box.addView(apply,new LinearLayout.LayoutParams(-1,-2));Button reset=button("Azzera prezzi",false);reset.setOnClickListener(v->{min.setText("");max.setText("");error.setText("");});box.addView(reset,new LinearLayout.LayoutParams(-1,-2));
  String saved=activity.getSharedPreferences("vinted_browser_experiment",Context.MODE_PRIVATE).getString("searchTags","");if(!saved.trim().isEmpty()){TextView heading=text("Le tue ricerche salvate",14,MUTED,true);heading.setPadding(0,dp(16),0,dp(8));box.addView(heading);for(String term:saved.split("\\n"))if(!term.trim().isEmpty()){TextView item=text(term,15,WHITE,false);item.setMinHeight(dp(48));item.setGravity(Gravity.CENTER_VERTICAL);item.setOnClickListener(v->{sheet.dismiss();navigate(term,state.order,state.minCents,state.maxCents,1);});box.addView(item);}}
  sheet.show();sizeSheet();
 }
 private LinearLayout sheet(String title){if(sheet!=null&&sheet.isShowing())sheet.dismiss();sheet=new Dialog(activity,android.R.style.Theme_Material_Dialog_NoActionBar_MinWidth);ScrollView scroll=new ScrollView(activity);LinearLayout box=column();box.setPadding(dp(22),dp(20),dp(22),dp(24));box.setBackground(shape(SURFACE,26,false));LinearLayout head=row();TextView heading=text(title,22,WHITE,true);head.addView(heading,new LinearLayout.LayoutParams(0,-2,1));head.addView(icon(LudoIcons.XMARK,"Chiudi pannello",MUTED,false,()->sheet.dismiss()),params(48,48));box.addView(head);scroll.addView(box);sheet.setContentView(scroll);sheet.setCanceledOnTouchOutside(true);Window w=sheet.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setGravity(Gravity.BOTTOM);w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}return box;}
 private void sizeSheet(){Window w=sheet.getWindow();if(w!=null)w.setLayout(-1,-2);}
 private EditText priceInput(String hint,Integer value){EditText input=new EditText(activity);input.setTypeface(font);input.setTextSize(16);input.setTextColor(WHITE);input.setHintTextColor(MUTED);input.setHint(hint+" €");input.setContentDescription(hint+" prezzo articolo");input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);input.setSingleLine(true);input.setPadding(dp(14),0,dp(14),0);input.setBackground(shape(BG,16,true));input.setText(value==null?"":euros(value));return input;}
 private static Integer readPrice(EditText input){String raw=input.getText().toString().trim();if(raw.isEmpty())return null;try{BigDecimal value=new BigDecimal(raw.replace(',','.'));if(value.signum()<0)return invalid();return value.movePointRight(2).intValueExact();}catch(Exception e){throw new IllegalArgumentException("Prezzo non valido");}}
 private static Integer invalid(){throw new IllegalArgumentException("Prezzo non valido");}
 private static String euros(Integer cents){return BigDecimal.valueOf(cents,2).stripTrailingZeros().toPlainString().replace('.',',');}
 private static String orderName(String value){for(int i=0;i<ORDERS.length;i++)if(ORDERS[i].equals(value))return ORDER_NAMES[i];return ORDER_NAMES[0];}
 private LinearLayout column(){LinearLayout v=new LinearLayout(activity);v.setOrientation(LinearLayout.VERTICAL);return v;}
 private LinearLayout row(){LinearLayout v=new LinearLayout(activity);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private TextView text(String value,int size,int color,boolean bold){TextView v=new TextView(activity);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setTypeface(font,bold?Typeface.BOLD:Typeface.NORMAL);v.setIncludeFontPadding(false);return v;}
 private TextView icon(String glyph,String description,int color,boolean filled,Runnable action){TextView v=LudoIcons.view(activity,glyph,20,color);v.setContentDescription(description);v.setMinHeight(dp(48));v.setMinWidth(dp(48));v.setBackground(ripple(filled?SURFACE:BG,24,filled));v.setOnClickListener(x->action.run());return v;}
 private Button button(String value,boolean primary){Button b=new Button(activity);b.setAllCaps(false);b.setText(value);b.setTextSize(16);b.setTypeface(font);b.setTextColor(primary?BG:WHITE);b.setMinHeight(dp(54));b.setBackground(ripple(primary?ACCENT:SURFACE,27,!primary));return b;}
 private GradientDrawable shape(int color,int radius,boolean border){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(border)d.setStroke(dp(1),OUTLINE);return d;}
 private Drawable ripple(int color,int radius,boolean border){return new RippleDrawable(ColorStateList.valueOf(Color.argb(45,164,151,255)),shape(color,radius,border),null);}
 private static void enable(View view,boolean value){view.setEnabled(value);view.setAlpha(value?1f:.35f);}
 private LinearLayout.LayoutParams params(int width,int height){return new LinearLayout.LayoutParams(dp(width),dp(height));}
 private int dp(int value){return Math.round(value*activity.getResources().getDisplayMetrics().density);}
 public void close(){if(sheet!=null)sheet.dismiss();}
}
