package it.vintedaffari.app;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import androidx.webkit.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Public user-controlled browser. Passive packets become durable local work, never endpoint replays. */
public final class VintedBrowserActivity extends Activity {
 private final ThreadPoolExecutor writer=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(4));
 private final ExecutorService reads=Executors.newSingleThreadExecutor();
 private final AtomicInteger rejected=new AtomicInteger();private final Set<String> routes=new LinkedHashSet<>();
 private static final class Session {final String url,key;volatile long id;Session(String url,long id){this.url=url;this.key=searchKey(url);this.id=id;}}
 private DealDatabase db;private BrowserCaptureStore store;private BrowserCaptureIntake intake;private VintedBrowserControls controls;private WebView web;
 private volatile Session session;private volatile boolean closed,resumed,accepting;private volatile long pageGeneration,captureGeneration;
 private boolean enabled,supported,loading,pageFailed,rendererGone,snapshotPending;private String mode,state="STARTING",navigationUrl="",lastSearchUrl="https://www.vinted.it/catalog/4881-board-games",deliveryMessage="",expectedSeller="";
 private int pageObserved,pagePrices,metadataTruncated,rejectedPhotos,rejectedItems,committed,withPrice,incomplete,pending;
 private volatile String lastReport="";private BrowserCaptureStore.Snapshot snapshot;
 @Override public void onCreate(Bundle saved){
  super.onCreate(saved);mode=getIntent().getStringExtra("mode");if(!"SEARCH".equals(mode)&&!"BUNDLE".equals(mode))mode="VIEW";enabled=saved==null?VintedBrowserPolicy.startsEnabled(mode):saved.getBoolean("capture");expectedSeller=getIntent().getStringExtra("expected_seller_id");if(expectedSeller==null||!expectedSeller.matches("[1-9][0-9]{0,18}"))expectedSeller="";
  db=new DealDatabase(getApplicationContext());store=new BrowserCaptureStore(db);intake=new BrowserCaptureIntake(store,writer,this::runOnUiThread,()->QueueWorkScheduler.scheduleLocalBrowser(getApplicationContext()));
  String url=saved==null?getIntent().getStringExtra("url"):saved.getString("browser_url");if(!VintedBrowserPolicy.allowedPage(url))url=lastSearchUrl;
  if("SEARCH".equals(mode)&&!Uri.parse(url).getPath().startsWith("/catalog/4881")){Uri original=Uri.parse(url);Uri.Builder b=original.buildUpon().path("/catalog/4881-board-games").clearQuery();for(String key:original.getQueryParameterNames())if(!Arrays.asList("catalog[]","catalog_ids[]","catalog_id").contains(key))for(String value:original.getQueryParameters(key))b.appendQueryParameter(key,value);url=b.build().toString();}
  if(saved!=null&&VintedBrowserPolicy.allowedPage(saved.getString("last_search")))lastSearchUrl=saved.getString("last_search");navigationUrl=url;
  if(saved!=null&&saved.getLong("capture_id")>0)session=new Session(saved.getString("capture_url",url),saved.getLong("capture_id"));else startSession(url);
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(10,11,20));getWindow().setStatusBarColor(Color.rgb(10,11,20));getWindow().setNavigationBarColor(Color.rgb(10,11,20));
  root.setOnApplyWindowInsetsListener((v,insets)->{int left,right,top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets safe=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()|WindowInsets.Type.ime());left=safe.left;right=safe.right;top=safe.top;bottom=safe.bottom;}else{left=insets.getSystemWindowInsetLeft();right=insets.getSystemWindowInsetRight();top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();if(bottom>dp(120))bottom=0;}v.setPadding(left,top,right,bottom);return insets;});setContentView(root);
  controls=new VintedBrowserControls(this,new VintedBrowserControls.Listener(){public void onNavigate(String next){navigate(next);}public void onCapture(){captureNow();}public void onToggle(){setCapture(!enabled);}public void onOpenEngine(long id){openEngine(id);}public void onClose(){finish();}public void onMenu(){showMenu();}});root.addView(controls.view(),new LinearLayout.LayoutParams(-1,-2));
  web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));WebView.setWebContentsDebuggingEnabled(false);WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setSafeBrowsingEnabled(true);settings.setSupportMultipleWindows(false);settings.setJavaScriptCanOpenWindowsAutomatically(false);CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);
  web.setWebViewClient(new WebViewClient(){
   public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){if(!request.isForMainFrame())return false;return !VintedBrowserPolicy.allowedPage(request.getUrl().toString());}
   public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){observeRoute(request.getUrl());return null;}
   public void onPageStarted(WebView view,String url,android.graphics.Bitmap icon){resetPage(url);loading=true;pageFailed=false;if(!VintedBrowserPolicy.allowedPage(url)){view.stopLoading();pageFailed=true;state="PAGE_BLOCKED";}refreshStatus();}
   public void onPageFinished(WebView view,String url){if(closed||rendererGone)return;navigationUrl=url;loading=false;if(!pageFailed&&VintedBrowserPolicy.allowedPage(url)){state=supported?(enabled?"CAPTURING":"PAUSED"):"UNSUPPORTED_PROVIDER";bindPage();}refreshStatus();refreshSnapshot();}
   public void onReceivedError(WebView view,WebResourceRequest request,WebResourceError error){if(request.isForMainFrame()){loading=false;pageFailed=true;accepting=false;state="PAGE_ERROR";refreshStatus();}}
   public void onReceivedHttpError(WebView view,WebResourceRequest request,WebResourceResponse response){if(request.isForMainFrame()&&response.getStatusCode()>=400){loading=false;pageFailed=true;accepting=false;state="PAGE_ERROR";refreshStatus();}}
   public boolean onRenderProcessGone(WebView view,RenderProcessGoneDetail detail){accepting=false;rendererGone=true;state="RENDERER_GONE";((LinearLayout)view.getParent()).removeView(view);view.destroy();web=null;refreshStatus();return true;}
  });
  supported=WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)&&WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER);
  try{if(supported){Set<String> origins=new LinkedHashSet<>(Arrays.asList("https://www.vinted.it","https://vinted.it"));WebViewCompat.addWebMessageListener(web,"LudoCapture",origins,(view,message,origin,mainFrame,reply)->receive(message.getData(),origin.toString(),mainFrame,reply));String script;try(java.io.InputStream input=getAssets().open("browser/vinted-capture.js")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[4096];int n;while((n=input.read(buffer))!=-1)out.write(buffer,0,n);script=new String(out.toByteArray(),StandardCharsets.UTF_8);}JSONObject initial=new JSONObject().put("enabled",false).put("expectedSeller",expectedSeller);WebViewCompat.addDocumentStartJavaScript(web,"window.__LudoCaptureInitial="+initial+";\n"+script,origins);}}
  catch(Exception error){supported=false;state="CAPTURE_INIT_ERROR";}
  refreshStatus();if(saved==null||web.restoreState(saved)==null)web.loadUrl(url);else{navigationUrl=web.getUrl()==null?url:web.getUrl();loading=false;bindPage();}root.requestApplyInsets();
 }
 private void startSession(String url){Session previous=session,next=new Session(url,0);session=next;snapshot=null;committed=withPrice=incomplete=pending=0;
  try{writer.execute(()->{try{if(previous!=null&&previous.id>0)store.finishCapture(previous.id,"CLOSED",System.currentTimeMillis());next.id=store.beginCapture(url,System.currentTimeMillis());runOnUiThread(()->{if(!closed&&session==next){bindPage();refreshSnapshot();refreshStatus();}});}catch(RuntimeException error){runOnUiThread(()->{if(!closed&&session==next){deliveryMessage="Ricerca non salvata. Chiudi e riapri per riprovare.";state="CAPTURE_CREATE_ERROR";accepting=false;refreshStatus();}});}});}catch(RejectedExecutionException full){deliveryMessage="Salvataggio occupato. Riprova la ricerca.";state="CAPTURE_CREATE_ERROR";accepting=false;}
 }
 private void resetPage(String url){accepting=false;captureGeneration++;pageGeneration++;navigationUrl=url;pageObserved=pagePrices=0;deliveryMessage="";if(isCatalog(url)){lastSearchUrl=url;if(session==null||!session.key.equals(searchKey(url)))startSession(url);}}
 private void navigate(String url){if(web==null||loading||!VintedBrowserPolicy.allowedPage(url))return;loading=true;accepting=false;refreshStatus();web.loadUrl(url);}
 private void setCapture(boolean value){if(!supported||web==null)return;captureGeneration++;enabled=value;deliveryMessage="";state=value?"CAPTURING":"PAUSED";accepting=value&&resumed&&!loading&&!pageFailed&&session!=null&&session.id>0;web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled("+accepting+")",null);refreshStatus();}
 private void captureNow(){if(!supported||web==null||!resumed||loading||pageFailed||session==null||session.id<=0)return;captureGeneration++;deliveryMessage="";accepting=true;web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.captureNow("+captureGeneration+")",null);refreshStatus();}
 private void bindPage(){if(web==null||!supported)return;accepting=enabled&&resumed&&!loading&&!pageFailed&&session!=null&&session.id>0&&VintedBrowserPolicy.allowedPage(navigationUrl);web.evaluateJavascript("if(window.LudoCaptureControl){window.LudoCaptureControl.setPageToken("+pageGeneration+");window.LudoCaptureControl.setEnabled("+accepting+");}",null);}
 private void receive(String data,String origin,boolean mainFrame,JavaScriptReplyProxy reply){
  if(data==null||data.length()>128*1024||!VintedBrowserPolicy.allowedMessage(origin,mainFrame,data.getBytes(StandardCharsets.UTF_8).length)){rejected.incrementAndGet();return;}
  try{JSONObject envelope=new JSONObject(data);String kind=envelope.optString("kind");if("location".equals(kind)){String url=envelope.optString("url");if(!closed&&web!=null&&VintedBrowserPolicy.allowedPage(url)&&samePage(url,web.getUrl())&&!samePage(url,navigationUrl)){resetPage(url);loading=false;pageFailed=false;bindPage();refreshStatus();}return;}if("deliveryError".equals(kind)){if(envelope.optLong("pageToken",-1)==pageGeneration&&samePage(envelope.optString("url"),navigationUrl)){deliveryMessage="Cattura interrotta. Tocca la fotocamera per riprovare.";state="DELIVERY_ERROR";accepting=false;refreshStatus();}return;}}
  catch(JSONException invalid){reply.postMessage("rejected:"+sequence(data));rejected.incrementAndGet();return;}
  if(closed||!accepting||web==null||session==null||session.id<=0){reply.postMessage("paused:"+sequence(data));return;}
  final Session admitted=session;final long document=pageGeneration,generation=captureGeneration;final String url=navigationUrl,seq=sequence(data);final int page=pageNumber(url);final BrowserCapturePacket packet;
  try{packet=BrowserCapturePacket.parse(data,url,document,System.currentTimeMillis());}catch(IllegalArgumentException invalid){rejected.incrementAndGet();reply.postMessage("rejected:"+seq);deliveryMessage="Alcuni dati della pagina non sono leggibili.";state="PACKET_REJECTED";refreshStatus();return;}
  metadataTruncated+=packet.truncatedMetadata;rejectedPhotos+=packet.rejectedPhotos;rejectedItems+=packet.rejectedItems;pageObserved=packet.observed;pagePrices=packet.withPrice;pending++;
  intake.submit(admitted.id,page,packet.candidates,System.currentTimeMillis(),()->!closed&&session==admitted&&document==pageGeneration&&generation==captureGeneration,(result,receipt)->{
   pending=Math.max(0,pending-1);String ack=result;if("limit".equals(result)){ack="rejected";deliveryMessage="Limite di 500 annunci su questa pagina. Puoi passare alla successiva.";state="PAGE_LIMIT";accepting=false;}else if("rejected".equals(result)){deliveryMessage="Dati non salvati. Tocca la fotocamera per riprovare.";state="COMMIT_ERROR";accepting=false;}else if("retry".equals(result)){state="COMMIT_RETRY";}
   reply.postMessage(ack+":"+seq);if("ready".equals(result)){state=enabled?"CAPTURING":"PAUSED";if(packet.complete&&!enabled&&packet.captureToken==captureGeneration)accepting=false;refreshSnapshot();}refreshStatus();
  });
 }
 private void refreshSnapshot(){Session selected=session;if(closed||selected==null||selected.id<=0||snapshotPending)return;snapshotPending=true;reads.execute(()->{BrowserCaptureStore.Snapshot result=null;try{result=store.snapshot(selected.id);}catch(RuntimeException ignored){}final BrowserCaptureStore.Snapshot ready=result;runOnUiThread(()->{snapshotPending=false;if(closed||session!=selected)return;if(ready!=null){snapshot=ready;committed=ready.rows.size();withPrice=0;for(BrowserCaptureStore.Row row:ready.rows)if(row.candidate.priceCents!=null)withPrice++;incomplete=BrowserCapturePresentation.groups(ready).rows("INCOMPLETE").size();}else{deliveryMessage="Conteggi temporaneamente non disponibili.";}refreshStatus();});});}
 private void refreshStatus(){if(controls==null)return;VintedBrowserControls.State model=new VintedBrowserControls.State();model.permittedURL=isCatalog(navigationUrl)?navigationUrl:lastSearchUrl;Uri url=Uri.parse(model.permittedURL);model.query=value(url,"search_text","");model.order=value(url,"order","relevance");model.minCents=price(url.getQueryParameter("price_from"));model.maxCents=price(url.getQueryParameter("price_to"));model.page=pageNumber(navigationUrl);model.catalog=isCatalog(navigationUrl);model.loading=loading;model.supported=supported&&web!=null&&!pageFailed;model.capture=enabled;model.captureId=session==null?0:session.id;model.committed=committed;model.withPrice=withPrice;model.incomplete=incomplete;model.pending=pending;model.message=!supported?"Cattura non disponibile su questa WebView":rendererGone?"Browser interrotto. Chiudi e riapri.":pageFailed?"Pagina non disponibile per la cattura.":deliveryMessage;controls.render(model);saveReport();}
 private void saveReport(){String routeSummary;synchronized(routes){routeSummary=routes.toString();}int localJobs=snapshot==null?0:BrowserCapturePresentation.groups(snapshot).localWork();lastReport="build=browser-durable-capture-v1;app="+BuildConfig.VERSION_NAME+";state="+state+";mode="+mode+";features="+supported+";capture="+enabled+";scope=capture;captureId="+(session==null?0:session.id)+";page="+pageNumber(navigationUrl)+";pageObserved="+pageObserved+";pagePrices="+pagePrices+";committedUnique="+committed+";withPrice="+withPrice+";incomplete="+incomplete+";pendingPackets="+pending+";localWork="+localJobs+";rejectedItems="+rejectedItems+";rejectedPhotos="+rejectedPhotos+";metadataTruncated="+metadataTruncated+";rejected="+rejected.get()+";extraRequestsByCapture=0;networkScope=capturer-only;canonicalWriter=local-analysis;routes="+routeSummary;getSharedPreferences("vinted_browser_experiment",MODE_PRIVATE).edit().putString("report",lastReport).putLong("at",System.currentTimeMillis()).apply();}
 private void observeRoute(Uri uri){if(uri==null||!"https".equals(uri.getScheme())||!("www.vinted.it".equals(uri.getHost())||"vinted.it".equals(uri.getHost())))return;String path=uri.getPath();if(path==null||!path.startsWith("/api/"))return;path=path.replaceAll("[0-9]+","{id}").replaceAll("[^a-zA-Z0-9/{}_\\-]","_");if(path.length()>160)path=path.substring(0,160);synchronized(routes){if(routes.size()<20)routes.add(path);}}
 private void openEngine(long id){if(id<=0)return;Intent intent=new Intent(this,MainActivity.class).putExtra("open_engine",true).putExtra("browser_capture_id",id);startActivity(intent);}
 private void showMenu(){new AlertDialog.Builder(this).setTitle("Browser Vinted").setItems(new String[]{"Dati della cattura","Chiudi browser"},(dialog,which)->{if(which==0){TextView text=new TextView(this);text.setText(lastReport);text.setTextColor(Color.WHITE);text.setTextSize(13);text.setTextIsSelectable(true);text.setPadding(dp(16),dp(16),dp(16),dp(16));ScrollView scroll=new ScrollView(this);scroll.addView(text);new AlertDialog.Builder(this).setTitle("Diagnostica cattura").setView(scroll).setPositiveButton("Chiudi",null).setNeutralButton("Copia dati",(d,w)->{ClipboardManager clipboard=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("Diagnostica browser",lastReport));}).show();}else finish();}).show();}
 private static String sequence(String data){java.util.regex.Matcher m=java.util.regex.Pattern.compile("\"seq\":([0-9]+)").matcher(data.substring(0,Math.min(100,data.length())));return m.find()?m.group(1):"0";}
 private static boolean isCatalog(String url){return url!=null&&Uri.parse(url).getPath()!=null&&Uri.parse(url).getPath().startsWith("/catalog");}
 private static boolean samePage(String a,String b){return a!=null&&b!=null&&Uri.parse(a).buildUpon().fragment(null).build().equals(Uri.parse(b).buildUpon().fragment(null).build());}
 private static String searchKey(String url){Uri uri=Uri.parse(url);List<String> values=new ArrayList<>();for(String key:uri.getQueryParameterNames())if(!key.equals("page"))for(String value:uri.getQueryParameters(key))values.add(key+"="+value);Collections.sort(values);return uri.getPath()+"?"+values;}
 private static int pageNumber(String url){try{return Math.max(1,Math.min(10,Integer.parseInt(Uri.parse(url).getQueryParameter("page"))));}catch(Exception ignored){return 1;}}
 private static String value(Uri url,String key,String fallback){String value=url.getQueryParameter(key);return value==null?fallback:value;}
 private static Integer price(String raw){try{return raw==null?null:new java.math.BigDecimal(raw).movePointRight(2).intValueExact();}catch(Exception ignored){return null;}}
 private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putBoolean("capture",enabled);out.putString("browser_url",navigationUrl);out.putString("last_search",lastSearchUrl);Session current=session;if(current!=null){out.putLong("capture_id",current.id);out.putString("capture_url",current.url);}if(web!=null)web.saveState(out);}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else finish();}
 @Override protected void onPause(){super.onPause();resumed=false;captureGeneration++;accepting=false;pending=0;if(web!=null)web.evaluateJavascript("window.LudoCaptureControl&&window.LudoCaptureControl.setEnabled(false)",null);saveReport();}
 @Override protected void onResume(){super.onResume();resumed=true;bindPage();refreshSnapshot();}
 @Override protected void onDestroy(){closed=true;accepting=false;reads.shutdown();Session current=session;intake.close(()->{try{if(current!=null&&current.id>0&&isFinishing())store.finishCapture(current.id,"CLOSED",System.currentTimeMillis());}finally{db.close();}});if(controls!=null)controls.close();if(web!=null){web.stopLoading();web.destroy();web=null;}super.onDestroy();}
}
