package it.vintedaffari.app;
import org.json.*;import java.util.*;import java.util.regex.*;
/** Reads JSON, Next hydration and React Flight strings; never runs site JavaScript. */
public final class VintedStructuredData {
 public static final class Scan {public final List<JSONObject> items=new ArrayList<>();public int scripts,decoded,objects,owned,rejected;public String summary(){return "scripts="+scripts+"; json="+decoded+"; objects="+objects+"; owned="+owned+"; rejected="+rejected;}}
 public static Scan scan(String html,String sellerId){Scan result=new Scan();Set<String> seen=new HashSet<>();Matcher scripts=Pattern.compile("<script\\b[^>]*>(.*?)</script>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html==null?"":html);StringBuilder flight=new StringBuilder();while(scripts.find()){result.scripts++;String body=scripts.group(1);decode(body,sellerId,result,seen,0);if(body.contains("__next_f"))for(String json:EmbeddedJson.structures(body)){try{Object o=new JSONTokener(json).nextValue();if(o instanceof JSONArray){JSONArray a=(JSONArray)o;if(a.length()>1&&a.opt(1) instanceof String)flight.append(a.optString(1));}}catch(Exception ignored){}}}if(flight.length()>0)decode(flight.toString(),sellerId,result,seen,0);return result;}
 private static void decode(String raw,String seller,Scan scan,Set<String> seen,int depth){if(depth>5||raw.length()>8_000_000)return;for(String chunk:EmbeddedJson.structures(raw)){try{Object root=new JSONTokener(chunk).nextValue();scan.decoded++;walk(root,seller,"",scan,seen,0);}catch(Exception ignored){}}for(String quoted:EmbeddedJson.strings(raw)){if(!quoted.contains("\\\"")||(!quoted.contains("items")&&!quoted.contains("price")&&!quoted.contains("user")))continue;try{Object decoded=new JSONTokener(quoted).nextValue();if(decoded instanceof String&&!decoded.equals(raw))decode((String)decoded,seller,scan,seen,depth+1);}catch(Exception ignored){}}}
 private static String owner(JSONObject x){for(String k:new String[]{"user_id","seller_id","owner_id","userId","sellerId","ownerId"})if(x.optString(k,"").matches("[0-9]+"))return x.optString(k,"");for(String k:new String[]{"user","seller","owner"}){JSONObject user=x.optJSONObject(k);if(user!=null&&user.has("id"))return user.optString("id","");}return "";}
 private static void walk(Object value,String seller,String inherited,Scan scan,Set<String> seen,int depth){if(depth>60||scan.objects>60000)return;if(value instanceof JSONArray){JSONArray a=(JSONArray)value;for(int i=0;i<a.length();i++)walk(a.opt(i),seller,inherited,scan,seen,depth+1);return;}if(!(value instanceof JSONObject))return;JSONObject x=(JSONObject)value;scan.objects++;String explicit=owner(x),scope=explicit.isEmpty()?inherited:explicit;boolean item=x.has("id")&&x.has("title")&&x.has("price");if(item){if(seller==null||seller.equals(scope)){String id=x.optString("id","");if(id.matches("[0-9]+")&&seen.add(id)){scan.items.add(x);if(!scope.isEmpty())scan.owned++;}}else scan.rejected++;}
 Iterator<String> keys=x.keys();while(keys.hasNext()){String key=keys.next();String k=key.toLowerCase(Locale.ROOT);if(k.contains("recommend")||k.contains("similar")||k.contains("suggest")||k.contains("promoted"))continue;Object child=x.opt(key);String childScope="";if(key.equals("items")||key.equals("catalog_items")||key.equals("catalogItems")||key.equals("catalog"))childScope=scope;walk(child,seller,childScope,scan,seen,depth+1);}}
 public static JSONObject item(String html,String id){for(JSONObject x:scan(html,null).items)if(id.equals(x.optString("id")))return x;return null;}
}
