import it.vintedaffari.app.*;import java.util.*;
public class BundleRegression {
 static int checks;static void check(boolean condition,String message){checks++;if(!condition)throw new AssertionError(message);}
 static DealRecord deal(String id,String seller){DealRecord d=new DealRecord();d.signature="vinted:"+id;d.vintedItemId=id;d.sellerId=seller;d.vintedUrl="https://www.vinted.it/items/"+id;d.bggId="42";d.lifecycle="ACTIVE";d.tier="good";d.itemPriceCents=1000;return d;}
 public static void main(String[] args){DealRecord a=deal("1","10"),b=deal("2","10"),foreign=deal("3","20");List<BundleSuggestion> pairs=BundlePlanner.forSource(a,Arrays.asList(a,b,foreign));check(pairs.size()==1,"Only same-seller pair");check("2".equals(pairs.get(0).itemId),"Correct item link");check(pairs.get(0).estimatedBundleTotalCents==null,"No invented shipping total");check(pairs.get(0).savingPct==null,"No invented discount");b.tier="verify";check(BundlePlanner.forSource(a,Arrays.asList(b)).isEmpty(),"Unverified expansion excluded");b.tier="good";b.lifecycle="USER_HIDDEN";check(BundlePlanner.forSource(a,Arrays.asList(b)).isEmpty(),"User exclusion respected");b.lifecycle="ACTIVE";b.sellerId=null;check(BundlePlanner.forSource(a,Arrays.asList(b)).isEmpty(),"Unknown seller excluded");check(BundlePlanner.forSource(a,Arrays.asList(deal("1","10"))).isEmpty(),"Same item cannot pair with itself");
 b=deal("4","10");b.rating=5.2;check(BundlePlanner.forSource(a,Arrays.asList(b)).isEmpty(),"Known BGG rating below 6 excluded");
 long t=1_700_000_000_000L;check("4 h".equals(RelativeTime.fromLabel("2 ore fa",t,t+2*60*60_000L)),"Relative Vinted age advances without refetch");
 String photo="https://images1.vinted.net/t/03_01234_photo/f800/172.jpg?s=x";String thumb="https://images1.vinted.net/t/03_01234_photo/f100/172.jpg?s=y";check(PhotoIdentity.unique(Arrays.asList(thumb,photo)).size()==1,"Photo variants collapse");check(PhotoIdentity.unique(Arrays.asList(thumb,photo)).get(0).equals(photo),"Largest available photo wins");check(PhotoIdentity.unique(Arrays.asList(photo,photo.replace("photo","other"))).size()==2,"Different photos preserved");
 check(SearchRanking.score("Root Vagabond Pack","Root: The Vagabond Pack")>SearchRanking.score("Root Vagabond Pack","Root"),"Expansion before base game");check(SearchRanking.score("Brass Birmingam","Brass Birmingham")>=500,"Typo tolerance");check(SearchRanking.score("El Dorado","The Quest for El Dorado")>=500,"Title variants");check(SearchRanking.score("root","Brass Birmingham")<500,"No unrelated suggestions");System.out.println("PASS: "+checks+" bundle, photo identity and search checks");}
}
