const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const file=path.join(__dirname,'../app/src/main/assets/browser/vinted-capture.js');
const script=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';
async function until(predicate){const end=Date.now()+5000;while(!predicate()){if(Date.now()>end)throw Error("condition timeout");await new Promise(r=>setTimeout(r,20));}}
const sleep=()=>new Promise(r=>setTimeout(r,350));
function fixture({href='https://www.vinted.it/catalog?search_text=catan',enabled=true,seller='',cards=[],scripts=[],ack=true,ackDelay=0,delayResponse=false,xhrStatus=200}={}){
 const messages=[];const requests=[];let payload={items:[]};let response,pendingResolve,mutationCallback;
 class Xhr{constructor(){this.listeners={};this.responseType='';this.responseText='';this.status=xhrStatus;}open(method,url){this.url=url;}addEventListener(name,cb){(this.listeners[name]??=[]).push(cb);}send(){requests.push(this.url);this.responseURL=this.url;this.responseText=JSON.stringify(payload);for(const cb of this.listeners.load??[])cb.call(this);for(const cb of this.listeners.loadend??[])cb.call(this);}}
 const document={readyState:'complete',querySelectorAll(selector){if(selector==='script[type="application/ld+json"],script#__NEXT_DATA__')return scripts;return cards;},addEventListener(){}};
 const window={location:{href,origin:'https://www.vinted.it'},document,__LudoCaptureInitial:{enabled,expectedSeller:seller},LudoCapture:{postMessage(s){messages.push(JSON.parse(s));if(ack&&JSON.parse(s).seq)setTimeout(()=>window.LudoCapture.onmessage?.({data:"ready:"+JSON.parse(s).seq}),ackDelay);}},XMLHttpRequest:Xhr,fetch(...args){requests.push(args);response=new Response(JSON.stringify(payload),{headers:{'Content-Type':'application/json'}});return delayResponse?new Promise(r=>pendingResolve=r):Promise.resolve(response);},MutationObserver:class{constructor(cb){this.cb=cb;mutationCallback=cb;}observe(){}},TextDecoder,URL,TextEncoder,setTimeout,clearTimeout};window.window=window;window.history={pushState(state,title,url){window.location.href=new URL(url,window.location.href).href;},replaceState(state,title,url){window.location.href=new URL(url,window.location.href).href;}};
 const originalFetch=window.fetch,originalOpen=Xhr.prototype.open;
 const ctx=vm.createContext(window);vm.runInContext(script,ctx);
 return {window,messages,requests,ctx,originalFetch,originalOpen,setPayload(p){payload=p;},response(){return response;},resolve(){pendingResolve(response);},mutate(){mutationCallback();},items(){return messages.flatMap(m=>m.items||[]);},async fetch(p,url='https://www.vinted.it/api/v2/catalog/items'){payload=p;return await window.fetch(url);}};
}
function item(id=10,price='12.50',seller=7){return {id,title:'Catan',price:{amount:price,currency_code:'EUR'},user:{id:seller,login:'seller'},photo:{url:'https://images1.vinted.net/photo.jpg',timestamp:1712345678}};}
test('continuous capture emits a saved-drain checkpoint after every batch is acknowledged',async()=>{const f=fixture({ack:false});f.window.LudoCaptureControl.setPageToken(77);await f.fetch({items:Array.from({length:65},(_,i)=>item(i+1))});await until(()=>f.messages.some(m=>m.items?.length));assert.equal(f.window.LudoCaptureControl.canAdvance(77),false);let handled=0;for(let n=0;n<8;n++){await new Promise(r=>setTimeout(r,40));const pending=f.messages.filter(m=>m.seq).slice(handled);for(const m of pending){handled++;f.window.LudoCapture.onmessage({data:'ready:'+m.seq});}}assert.equal(f.items().length,65);assert.ok(f.messages.some(m=>m.settled===true&&m.page.observed===65));assert.equal(f.window.LudoCaptureControl.canAdvance(77),true);assert.equal(f.window.LudoCaptureControl.canAdvance(76),false);});
test('in-flight page request and retry keep pagination blocked',async()=>{const f=fixture({ack:false,delayResponse:true});f.window.LudoCaptureControl.setPageToken(19);const promise=f.fetch({items:[item()]});await new Promise(r=>setTimeout(r,50));assert.equal(f.window.LudoCaptureControl.canAdvance(19),false);for(const m of f.messages.filter(m=>m.seq))f.window.LudoCapture.onmessage({data:'ready:'+m.seq});f.resolve();await promise;await until(()=>f.messages.some(m=>m.items?.length));const m=f.messages.find(m=>m.items?.length);f.window.LudoCapture.onmessage({data:'retry:'+m.seq});assert.equal(f.window.LudoCaptureControl.canAdvance(19),false);});
test('pause cannot claim a completed capture and new cards revoke drain',async()=>{const f=fixture();f.window.LudoCaptureControl.setPageToken(21);await f.fetch({items:[item()]});await sleep();assert.equal(f.window.LudoCaptureControl.canAdvance(21),true);f.window.LudoCaptureControl.setEnabled(false);assert.equal(f.window.LudoCaptureControl.canAdvance(21),false);f.window.LudoCaptureControl.setEnabled(true);await f.fetch({items:[item(22)]});assert.equal(f.window.LudoCaptureControl.canAdvance(21),false);await sleep();assert.equal(f.window.LudoCaptureControl.canAdvance(21),true);});
test('document-start installs control before page requests',()=>{const f=fixture();assert.equal(typeof f.window.LudoCaptureControl?.captureNow,'function');});
test('fetch response remains readable and no additional request is issued',async()=>{const f=fixture();const p={items:[item()]};const res=await f.fetch(p);assert.deepEqual(await res.json(),p);await sleep();assert.equal(f.requests.length,1);assert.equal(f.items()[0]?.id,'10');assert.equal(f.items()[0]?.priceCents,1250);assert.equal(f.items()[0]?.sellerId,'7');});
test('capture off sends nothing and a snapshot can be captured without replay',async()=>{const f=fixture({enabled:false});await f.fetch({items:[item()]});await sleep();assert.equal(f.messages.length,0);assert.ok(f.window.LudoCaptureControl);f.window.LudoCaptureControl.captureNow();await sleep();assert.equal(f.items().length,1);assert.equal(f.requests.length,1);await f.fetch({items:[item(11)]});await sleep();assert.equal(f.items().length,1);});
test('same id and same content dedupe; changed price updates',async()=>{const f=fixture();for(const p of ['12.50','12.50','10.00']){await f.fetch({items:[item(10,p)]});await sleep();}assert.deepEqual(f.items().map(x=>x.priceCents),[1250,1000]);});
test('seller identity is explicit and recommendations do not inherit page owner',async()=>{const f=fixture({seller:'7'});await f.fetch({items:[item(10,'12',7),item(11,'13',8),{id:12,title:'Azul',price:'9'}]});await sleep();assert.deepEqual(f.items().map(x=>x.sellerId),['7','8',null]);assert.equal(f.items()[1].expectedSellerMatch,false);});
test('photo timestamp and created_at are not claimed as published time',async()=>{const f=fixture();await f.fetch({items:[{...item(),created_at:1712345678}]});await sleep();assert.equal(f.items()[0]?.publication,null);});
test('explicit publication remains source-labelled',async()=>{const f=fixture();await f.fetch({items:[{...item(),published_at:'2026-10-02T12:00:00Z'}]});await sleep();assert.deepEqual(f.items()[0]?.publication,{raw:'2026-10-02T12:00:00Z',source:'json:published_at'});});
test('invalid price stays absent and distinct ids remain distinct',async()=>{const f=fixture();await f.fetch({items:[item(10,'bad'),item(11,'bad')]});await sleep();assert.equal(f.items().length,2);assert.equal(f.items()[0].priceCents,null);});
test('private chat responses are never read or sent',async()=>{const f=fixture();await f.fetch({items:[item()]},'https://www.vinted.it/api/v2/conversations/10');await sleep();assert.equal(f.messages.length,0);});
test('account and message APIs cannot inject item-shaped payloads into catalog capture',async()=>{for(const endpoint of ['https://www.vinted.it/api/v2/conversations/10','https://www.vinted.it/api/v2/messages/42','https://www.vinted.it/api/v2/users/7']){const f=fixture();await f.fetch({items:[item(78)]},endpoint);await sleep();assert.equal(f.items().length,0,endpoint);assert.equal(f.messages.length,0,endpoint);}});

test('DOM item links yield exact ids without guessing seller or price',async()=>{const card={getAttribute(n){return n==='href'?'/items/222-catan':null;},textContent:'Catan',querySelector(){return {getAttribute(n){return n==='alt'?'Catan':n==='src'?'https://images1.vinted.net/a.jpg':null;}};}};const f=fixture({cards:[card]});await sleep();assert.equal(f.items()[0]?.id,'222');assert.equal(f.items()[0]?.sellerId,null);assert.equal(f.items()[0]?.priceCents,null);});
test('DOM responsive image uses currentSrc or srcset for AI evidence',async()=>{const image={currentSrc:'https://images1.vinted.net/current.webp',getAttribute(n){return n==='alt'?'Catan':n==='src'?'':n==='srcset'?'https://images1.vinted.net/small.webp 1x, https://images1.vinted.net/large.webp 2x':null;}};const card={getAttribute(n){return n==='href'?'/items/223-catan':null;},textContent:'Catan',querySelector(){return image;}};const f=fixture({cards:[card]});await sleep();assert.deepEqual(f.items()[0]?.photos,['https://images1.vinted.net/current.webp']);});
test('initial structured item data is captured without a request',async()=>{const f=fixture({scripts:[{textContent:JSON.stringify({items:[item()]})}]});await sleep();assert.equal(f.items()[0]?.id,'10');assert.equal(f.requests.length,0);});
test('XHR hook preserves original send and captures response',async()=>{const f=fixture();f.setPayload({items:[item()]});const x=new f.window.XMLHttpRequest();x.open('GET','https://www.vinted.it/api/v2/catalog/items');x.send();await sleep();assert.equal(f.requests.length,1);assert.equal(f.items()[0]?.id,'10');});
test('repeated injection does not double-wrap fetch',async()=>{const f=fixture();const fetch=f.window.fetch;vm.runInContext(script,f.ctx);assert.equal(f.window.fetch,fetch);await f.fetch({items:[item()]});await sleep();assert.equal(f.items().length,1);});
test('batch and registry limits are enforced and overflow is visible',async()=>{const f=fixture({ackDelay:30});await f.fetch({items:Array.from({length:510},(_,i)=>item(i+1))});await until(()=>f.items().length===500);assert.equal(f.items().length,500);assert.ok(f.messages.every(m=>m.items.length<=32));assert.ok(f.messages.some(m=>m.stats.dropped>=10));assert.ok(f.messages.every(m=>Buffer.byteLength(JSON.stringify(m))<=128*1024));});
test('pause suppresses queued output; resume snapshots without network',async()=>{const f=fixture();await f.fetch({items:[item()]});f.window.LudoCaptureControl?.setEnabled(false);await sleep();assert.equal(f.messages.length,0);f.window.LudoCaptureControl.setEnabled(true);await sleep();assert.equal(f.items().length,1);assert.equal(f.requests.length,1);});
test('cross-origin response and non-json pages do not become items',async()=>{const f=fixture();await f.fetch({items:[item()]},'https://evil.example/api/v2/catalog/items');await sleep();assert.equal(f.messages.length,0);});
test('DOM refresh cannot downgrade richer JSON title and provenance',async()=>{const card={getAttribute(n){return n==='href'?'/items/10-card':null;},textContent:'Different accessibility label',querySelector(){return {getAttribute(n){return n==='alt'?'Generic photo label':null;}};}};const f=fixture({cards:[card]});await sleep();await f.fetch({items:[item()]});await sleep();f.window.LudoCaptureControl.captureNow();await sleep();assert.equal(f.items().at(-1)?.title,'Catan');assert.equal(f.items().at(-1)?.source,'json');});
test('private current page prevents capture even for a catalog response',async()=>{const f=fixture();f.window.location.href='https://www.vinted.it/inbox';await f.fetch({items:[item()]});await sleep();assert.equal(f.messages.length,0);});
test('unsafe and conflicting item links are not normalized',async()=>{const f=fixture();await f.fetch({items:[{...item(),url:'https://www.vinted.it/items/11-x'},{...item(12),url:'https://evil.example/items/12'}]});await sleep();assert.equal(f.items().length,0);});

test('resume reoffers cached records when a native pause discarded delivery',async()=>{const f=fixture();await f.fetch({items:[item()]});await sleep();f.messages.length=0;f.window.LudoCaptureControl.setEnabled(false);f.window.LudoCaptureControl.setEnabled(true);await sleep();assert.equal(f.items().length,1);assert.equal(f.requests.length,1);});

test("rich batches split by byte budget without losing items",async()=>{const f=fixture();await f.fetch({items:Array.from({length:32},(_,i)=>({...item(i+1),description:"x".repeat(2000),photos:Array.from({length:10},()=>({url:"https://images1.vinted.net/"+"x".repeat(300)}))}))});await sleep();assert.equal(f.items().length,32);assert.ok(f.messages.length>1);assert.ok(f.messages.every(m=>Buffer.byteLength(JSON.stringify(m))<=128*1024));});

test('one-shot freezes items present at the button press',async()=>{const f=fixture({enabled:false,ack:false});await f.fetch({items:[item(1)]});await sleep();f.window.LudoCaptureControl.captureNow();await sleep();const seq=f.messages[0].seq;await f.fetch({items:[item(2)]});await sleep();f.window.LudoCapture.onmessage({data:'ready:'+seq});await sleep();assert.deepEqual(f.items().map(x=>x.id),['1']);assert.equal(f.messages.at(-1).complete,true);});
test('empty unknown shape sends diagnostic counters',async()=>{const f=fixture();await f.fetch({unexpected:true});await sleep();assert.equal(f.items().length,0);assert.ok(f.messages.some(x=>x.stats.unknownShapes>0));});
test('non-item objects cannot fabricate item URLs',async()=>{const f=fixture();await f.fetch({items:[{id:7,name:'Seller',url:'https://www.vinted.it/member/7'},{id:8,name:'Category'}]});await sleep();assert.equal(f.items().length,0);});

function card(href,alt){return {getAttribute(n){return n==='href'?href:n==='title'?alt:null;},textContent:'',querySelector(){return {getAttribute(n){return n==='alt'?alt:n==='src'?'https://images1.vinted.net/a.jpg':null;}};}};}
test('DOM extracts sticker and protected price without confusing title numbers',async()=>{const f=fixture({cards:[card('/items/44-catan','Catan 25 anniversario, Brand: Kosmos, Condizioni: Ottime, 20.00 €, 21.70 € incl.')]});await sleep();const x=f.items()[0];assert.equal(x?.title,'Catan 25 anniversario');assert.equal(x?.priceCents,2000);assert.equal(x?.protectedPriceCents,2170);assert.equal(x?.brand,'Kosmos');assert.equal(x?.condition,'Ottime');assert.equal(x?.sellerId,null);});
test('DOM accepts Italian decimal prices but does not infer shipping',async()=>{const f=fixture({cards:[card('/items/45-azul','Azul, Brand: Next Move, Condizioni: Buone, 9,50 €, 10,68 € incl.')]});await sleep();assert.equal(f.items()[0]?.priceCents,950);assert.equal(f.items()[0]?.protectedPriceCents,1068);});
test('item card title with a euro amount is not enough price evidence',async()=>{const f=fixture({cards:[card('/items/46-x','Monopoly 100 € edition')]});await sleep();assert.equal(f.items()[0]?.priceCents,null);});
test('page diagnostics report IDs and prices actually delivered',async()=>{const f=fixture({cards:[card('/items/44-x','Catan, Brand: Kosmos, Condizioni: Ottime, 20.00 €, 21.70 € incl.')]});await sleep();assert.ok(f.messages.some(m=>m.page?.observed===1&&m.page?.withPrice===1));});
test('page arrows preserve search filters and board games category',()=>{const f=fixture();f.window.location.href='https://www.vinted.it/catalog/4881-board-games?search_text=Catan&order=newest_first&price_from=2&page=3&status_ids[]=2';const u=f.window.LudoCaptureControl?.navigationUrl?.('next');assert.ok(u);const x=new URL(u);assert.equal(x.pathname,'/catalog/4881-board-games');assert.equal(x.searchParams.get('page'),'4');assert.equal(x.searchParams.get('search_text'),'Catan');assert.equal(x.searchParams.get('price_from'),'2');assert.equal(x.searchParams.get('status_ids[]'),'2');assert.equal(f.requests.length,0);});
test('price increment resets page and enforces board game search',()=>{const f=fixture();f.window.location.href='https://www.vinted.it/catalog?search_text=Catan&page=5&price_from=2&catalog[]=1&price_to=2';const u=f.window.LudoCaptureControl?.navigationUrl?.('pricePlus');assert.ok(u);const x=new URL(u);assert.equal(x.pathname,'/catalog/4881-board-games');assert.equal(x.searchParams.get('price_from'),'3');assert.equal(x.searchParams.get('order'),'price_low_to_high');assert.equal(x.searchParams.get('page'),'1');assert.equal(x.searchParams.has('price_to'),false);assert.equal(x.searchParams.has('catalog[]'),false);});
test('search shortcut resets page without discarding other filters',()=>{const f=fixture();f.window.location.href='https://www.vinted.it/catalog/4881-board-games?search_text=Catan&page=3&price_from=5';const u=f.window.LudoCaptureControl?.navigationUrl?.('search','Azul & giochi');assert.ok(u);const x=new URL(u);assert.equal(x.searchParams.get('search_text'),'Azul & giochi');assert.equal(x.searchParams.get('page'),'1');assert.equal(x.searchParams.get('price_from'),'5');});
test('page arrows refuse outside search, first previous and tenth next',()=>{const f=fixture();assert.equal(f.window.LudoCaptureControl?.navigationUrl?.('previous'),null);f.window.location.href='https://www.vinted.it/catalog?page=10';assert.equal(f.window.LudoCaptureControl?.navigationUrl?.('next'),null);f.window.location.href='https://www.vinted.it/items/44';assert.equal(f.window.LudoCaptureControl?.navigationUrl?.('next'),null);});

test('search shortcuts work from item using remembered catalog filters',()=>{const f=fixture();f.window.location.href='https://www.vinted.it/items/44';const u=f.window.LudoCaptureControl.navigationUrl('search','Azul','https://www.vinted.it/catalog/4881-board-games?price_from=5&page=4');assert.ok(u);const x=new URL(u);assert.equal(x.searchParams.get('price_from'),'5');assert.equal(x.searchParams.get('search_text'),'Azul');assert.equal(x.searchParams.get('page'),'1');});

test('price stepping keeps decimal minima usable across repeated taps',()=>{const f=fixture();f.window.location.href='https://www.vinted.it/catalog?price_from=1.11';let u=f.window.LudoCaptureControl.navigationUrl('pricePlus');assert.equal(new URL(u).searchParams.get('price_from'),'2.11');f.window.location.href=u;u=f.window.LudoCaptureControl.navigationUrl('pricePlus');assert.equal(new URL(u).searchParams.get('price_from'),'3.11');});
test('formatted thousands cannot be truncated into a cheaper price',async()=>{const f=fixture({cards:[card('/items/44-x','Catan, Brand: Kosmos, Condizioni: Ottime, 1,234.00 €, 1,296.40 € incl.')]});await sleep();assert.equal(f.items()[0]?.priceCents,null);});

test('SPA navigation resets captured records and labels new document token',async()=>{const cards=[card('/items/1-x','Catan, Brand: Kosmos, Condizioni: Ottime, 20.00 €, 21.70 € incl.')];const f=fixture({cards});await sleep();f.messages.length=0;cards.splice(0,1,card('/items/2-x','Azul, Brand: Next Move, Condizioni: Buone, 9.50 €, 10.68 € incl.'));f.window.history.pushState(null,'','/catalog/4881-board-games?page=2');f.window.LudoCaptureControl.setPageToken(9);await sleep();assert.deepEqual(f.items().map(x=>x.id),['2']);assert.ok(f.messages.some(x=>x.kind==='location'));assert.ok(f.messages.some(x=>x.pageToken===9&&x.page?.observed===1));});
test('late response from previous page does not populate new page',async()=>{const f=fixture({delayResponse:true});const request=f.fetch({items:[item(1)]});f.window.history.pushState(null,'','/catalog/4881-board-games?page=2');f.resolve();await request;await sleep();assert.equal(f.items().length,0);assert.equal(f.requests.length,1);});

test('SPA router updates URL before DOM without importing stale cards or initial state',async()=>{const cards=[card('/items/1-x','Catan, Brand: Kosmos, Condizioni: Ottime, 20.00 €, 21.70 € incl.')];const f=fixture({cards,scripts:[{textContent:JSON.stringify({items:[item(8)]})}]});await sleep();f.messages.length=0;f.window.history.pushState(null,'','/catalog/4881-board-games?page=2');f.window.history.replaceState(null,'','/catalog/4881-board-games?page=2&order=newest_first');f.window.LudoCaptureControl.setPageToken(10);f.window.LudoCaptureControl.setEnabled(true);await sleep();assert.equal(f.items().length,0);cards.splice(0,1,card('/items/2-x','Azul, Brand: Next Move, Condizioni: Buone, 9.50 €, 10.68 € incl.'));f.mutate();await until(()=>f.items().some(x=>x.id==='2'));assert.deepEqual(f.items().map(x=>x.id),['2']);});
test('unreadable sticker never promotes protection price to sticker',async()=>{const f=fixture({cards:[card('/items/44-x','Catan, Brand: Kosmos, Condizioni: Ottime, 1,234.00 €, 1235.00 € incl.')]});await sleep();assert.equal(f.items()[0]?.priceCents,null);});

test('hash-only SPA navigation retains page token and records',async()=>{const f=fixture();f.window.LudoCaptureControl.setPageToken(12);await f.fetch({items:[item(1)]});await sleep();f.messages.length=0;f.window.history.pushState(null,'','#details');await f.fetch({items:[item(2)]});await sleep();assert.equal(f.messages.some(m=>m.kind==='location'),false);assert.deepEqual(f.items().map(x=>x.id),['2']);assert.equal(f.messages.find(m=>m.items?.length)?.pageToken,12);f.window.LudoCaptureControl.captureNow();await sleep();assert.equal(f.messages.find(m=>m.complete)?.page.observed,2);});

test('Next rechecks newly rendered DOM even before observer debounce runs',async()=>{const cards=[card('/items/1-x','Catan')];const f=fixture({cards});f.window.LudoCaptureControl.setPageToken(30);await sleep();assert.equal(f.window.LudoCaptureControl.canAdvance(30),true);cards.push(card('/items/2-x','Azul'));f.mutate();assert.equal(f.window.LudoCaptureControl.canAdvance(30),false);await sleep();assert.equal(f.window.LudoCaptureControl.canAdvance(30),true);assert.equal(f.items().some(x=>x.id==='2'),true);});

test('failed XHR response never claims that page capture completed',async()=>{const f=fixture({xhrStatus:429});f.window.LudoCaptureControl.setPageToken(41);f.setPayload({items:[item()]});const x=new f.window.XMLHttpRequest();x.open('GET','https://www.vinted.it/api/v2/catalog/items');x.send();await sleep();assert.equal(f.window.LudoCaptureControl.canAdvance(41),false);assert.equal(f.messages.some(m=>m.stats?.readErrors>0),true);});

test('session refresh installs no capture control or network interception',async()=>{const f=fixture({href:'https://www.vinted.it/session-refresh?redirect=%2Fcatalog',enabled:true});assert.equal(f.window.LudoCaptureControl,undefined);assert.equal(f.window.fetch,f.originalFetch);assert.equal(f.window.XMLHttpRequest.prototype.open,f.originalOpen);await f.fetch({items:[item()]});await sleep();assert.equal(f.messages.length,0);assert.equal(f.requests.length,1);});
