const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const file=path.join(__dirname,'../app/src/main/assets/browser/vinted-capture.js');
const script=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';
const sleep=()=>new Promise(r=>setTimeout(r,35));
function fixture({enabled=true,seller='',cards=[],scripts=[]}={}){
 const messages=[];const requests=[];let payload={items:[]};let response;
 class Xhr{constructor(){this.listeners={};this.responseType='';this.responseText='';this.status=200;}open(method,url){this.url=url;}addEventListener(name,cb){(this.listeners[name]??=[]).push(cb);}send(){requests.push(this.url);this.responseURL=this.url;this.responseText=JSON.stringify(payload);for(const cb of this.listeners.load??[])cb.call(this);}}
 const document={readyState:'complete',querySelectorAll(selector){if(selector==='script[type="application/ld+json"],script#__NEXT_DATA__')return scripts;return cards;},addEventListener(){}};
 const window={location:{href:'https://www.vinted.it/catalog?search_text=catan',origin:'https://www.vinted.it'},document,__LudoCaptureInitial:{enabled,expectedSeller:seller},LudoCapture:{postMessage(s){messages.push(JSON.parse(s));}},XMLHttpRequest:Xhr,fetch(...args){requests.push(args);response=new Response(JSON.stringify(payload),{headers:{'Content-Type':'application/json'}});return Promise.resolve(response);},MutationObserver:class{constructor(cb){this.cb=cb;}observe(){}},TextDecoder,URL,TextEncoder,setTimeout,clearTimeout};window.window=window;
 const ctx=vm.createContext(window);vm.runInContext(script,ctx);
 return {window,messages,requests,ctx,setPayload(p){payload=p;},response(){return response;},items(){return messages.flatMap(m=>m.items);},async fetch(p,url='https://www.vinted.it/api/v2/catalog/items'){payload=p;return await window.fetch(url);}};
}
function item(id=10,price='12.50',seller=7){return {id,title:'Catan',price:{amount:price,currency_code:'EUR'},user:{id:seller,login:'seller'},photo:{url:'https://images1.vinted.net/photo.jpg',timestamp:1712345678}};}
test('document-start installs control before page requests',()=>{const f=fixture();assert.equal(typeof f.window.LudoCaptureControl?.captureNow,'function');});
test('fetch response remains readable and no additional request is issued',async()=>{const f=fixture();const p={items:[item()]};const res=await f.fetch(p);assert.deepEqual(await res.json(),p);await sleep();assert.equal(f.requests.length,1);assert.equal(f.items()[0]?.id,'10');assert.equal(f.items()[0]?.priceCents,1250);assert.equal(f.items()[0]?.sellerId,'7');});
test('capture off sends nothing and a snapshot can be captured without replay',async()=>{const f=fixture({enabled:false});await f.fetch({items:[item()]});await sleep();assert.equal(f.messages.length,0);assert.ok(f.window.LudoCaptureControl);f.window.LudoCaptureControl.captureNow();await sleep();assert.equal(f.items().length,1);assert.equal(f.requests.length,1);await f.fetch({items:[item(11)]});await sleep();assert.equal(f.items().length,1);});
test('same id and same content dedupe; changed price updates',async()=>{const f=fixture();for(const p of ['12.50','12.50','10.00']){await f.fetch({items:[item(10,p)]});await sleep();}assert.deepEqual(f.items().map(x=>x.priceCents),[1250,1000]);});
test('seller identity is explicit and recommendations do not inherit page owner',async()=>{const f=fixture({seller:'7'});await f.fetch({items:[item(10,'12',7),item(11,'13',8),{id:12,title:'Azul',price:'9'}]});await sleep();assert.deepEqual(f.items().map(x=>x.sellerId),['7','8',null]);assert.equal(f.items()[1].expectedSellerMatch,false);});
test('photo timestamp and created_at are not claimed as published time',async()=>{const f=fixture();await f.fetch({items:[{...item(),created_at:1712345678}]});await sleep();assert.equal(f.items()[0]?.publication,null);});
test('explicit publication remains source-labelled',async()=>{const f=fixture();await f.fetch({items:[{...item(),published_at:'2026-10-02T12:00:00Z'}]});await sleep();assert.deepEqual(f.items()[0]?.publication,{raw:'2026-10-02T12:00:00Z',source:'json:published_at'});});
test('invalid price stays absent and distinct ids remain distinct',async()=>{const f=fixture();await f.fetch({items:[item(10,'bad'),item(11,'bad')]});await sleep();assert.equal(f.items().length,2);assert.equal(f.items()[0].priceCents,null);});
test('private chat responses are never read or sent',async()=>{const f=fixture();await f.fetch({items:[item()]},'https://www.vinted.it/api/v2/conversations/10');await sleep();assert.equal(f.messages.length,0);});
test('DOM item links yield exact ids without guessing seller or price',async()=>{const card={getAttribute(n){return n==='href'?'/items/222-catan':null;},textContent:'Catan',querySelector(){return {getAttribute(n){return n==='alt'?'Catan':n==='src'?'https://images1.vinted.net/a.jpg':null;}};}};const f=fixture({cards:[card]});await sleep();assert.equal(f.items()[0]?.id,'222');assert.equal(f.items()[0]?.sellerId,null);assert.equal(f.items()[0]?.priceCents,null);});
test('initial structured item data is captured without a request',async()=>{const f=fixture({scripts:[{textContent:JSON.stringify({items:[item()]})}]});await sleep();assert.equal(f.items()[0]?.id,'10');assert.equal(f.requests.length,0);});
test('XHR hook preserves original send and captures response',async()=>{const f=fixture();f.setPayload({items:[item()]});const x=new f.window.XMLHttpRequest();x.open('GET','https://www.vinted.it/api/v2/catalog/items');x.send();await sleep();assert.equal(f.requests.length,1);assert.equal(f.items()[0]?.id,'10');});
test('repeated injection does not double-wrap fetch',async()=>{const f=fixture();const fetch=f.window.fetch;vm.runInContext(script,f.ctx);assert.equal(f.window.fetch,fetch);await f.fetch({items:[item()]});await sleep();assert.equal(f.items().length,1);});
test('batch and registry limits are enforced and overflow is visible',async()=>{const f=fixture();await f.fetch({items:Array.from({length:510},(_,i)=>item(i+1))});await sleep();assert.equal(f.items().length,500);assert.ok(f.messages.every(m=>m.items.length<=32));assert.ok(f.messages.some(m=>m.stats.dropped>=10));assert.ok(f.messages.every(m=>Buffer.byteLength(JSON.stringify(m))<=128*1024));});
test('pause suppresses queued output; resume snapshots without network',async()=>{const f=fixture();await f.fetch({items:[item()]});f.window.LudoCaptureControl?.setEnabled(false);await sleep();assert.equal(f.messages.length,0);f.window.LudoCaptureControl.setEnabled(true);await sleep();assert.equal(f.items().length,1);assert.equal(f.requests.length,1);});
test('cross-origin response and non-json pages do not become items',async()=>{const f=fixture();await f.fetch({items:[item()]},'https://evil.example/api/v2/catalog/items');await sleep();assert.equal(f.messages.length,0);});
