package it.vintedaffari.app;
import android.test.AndroidTestCase;
import android.database.Cursor;
import android.content.ContentValues;
import org.json.JSONObject;
import java.util.*;
public class BrowserAnalysisCommitterTest extends AndroidTestCase {
 private DealDatabase db;private BrowserCaptureStore captures;private MarketStore market;private BrowserAnalysisCommitter committer;
 protected void setUp()throws Exception{super.setUp();getContext().deleteDatabase("vinted_affari.db");db=new DealDatabase(getContext());captures=new BrowserCaptureStore(db);market=new MarketStore(getContext(),db);committer=new BrowserAnalysisCommitter(db,market,captures);}
 protected void tearDown()throws Exception{db.close();getContext().deleteDatabase("vinted_affari.db");super.tearDown();}
 private BrowserCandidate card(String id,int price,long at){return new BrowserCandidate(id,"https://www.vinted.it/items/"+id,"Azul gioco da tavolo",price,null,Collections.emptyMap(),Collections.emptyMap(),at);}
 private GameAnalysis analysis()throws Exception{return GameAnalysis.fromJson(new JSONObject().put("status","matched").put("game",new JSONObject().put("bggId","230802").put("name","Azul").put("averageRating",7.8)).put("deal",new JSONObject().put("totalCents",1600).put("benchmarkCents",2500).put("tier","good")));}

 private long count(String sql){try(Cursor c=db.getReadableDatabase().rawQuery(sql,null)){assertTrue(c.moveToFirst());return c.getLong(0);}}
 public void testDistinctIdsMaterializeAndNoRemoteMetadataJobs()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Arrays.asList(card("101",1000,10),card("102",1000,10)),10);for(BrowserCaptureStore.Claim claim:captures.claim(8,20))assertTrue(committer.commit(claim,analysis(),30));assertEquals(2,count("SELECT COUNT(*) FROM market_listings WHERE vinted_item_id IN ('101','102')"));assertEquals(2,count("SELECT COUNT(DISTINCT signature) FROM observations WHERE signature LIKE 'vinted:%'"));market.reconcileQueue();assertEquals(0,count("SELECT COUNT(*) FROM processing_jobs WHERE job_type IN ('VINTED_ENRICHMENT','VINTED_DEEP_ENRICHMENT')"));}
 public void testStaleResultDoesNotMaterialize()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);BrowserCaptureStore.Claim old=captures.claim(8,20).get(0);captures.commit(id,1,Collections.singletonList(card("101",900,30)),30);assertFalse(committer.commit(old,analysis(),40));assertEquals(0,count("SELECT COUNT(*) FROM market_listings WHERE vinted_item_id='101'"));}
 public void testHiddenExactListingNotReactivated()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));db.getWritableDatabase().execSQL("UPDATE market_listings SET lifecycle='USER_HIDDEN' WHERE vinted_item_id='101'");captures.commit(id,1,Collections.singletonList(card("101",900,40)),40);assertTrue(committer.commit(captures.claim(8,50).get(0),analysis(),60));assertEquals(1,count("SELECT COUNT(*) FROM market_listings WHERE vinted_item_id='101' AND lifecycle='USER_HIDDEN'"));}
 public void testPriceRevisionRetainsExactListing()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));long listing=count("SELECT id FROM market_listings WHERE vinted_item_id='101'");captures.commit(id,1,Collections.singletonList(card("101",900,40)),40);assertTrue(committer.commit(captures.claim(8,50).get(0),analysis(),60));assertEquals(listing,count("SELECT id FROM market_listings WHERE vinted_item_id='101'"));assertEquals(900,count("SELECT current_price_cents FROM market_listings WHERE vinted_item_id='101'"));}
 public void testSameTextCannotPromoteLegacyIdentity()throws Exception{VintedCard legacy=new VintedCard("Azul gioco da tavolo","","",10.0,null,null,new android.graphics.Rect(),"");long old=market.recordSighting(legacy,ListingClassifier.classify(legacy),5);long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));assertEquals(2,count("SELECT COUNT(*) FROM market_listings"));assertEquals(0,count("SELECT COUNT(*) FROM market_listings WHERE id="+old+" AND vinted_item_id='101'"));}
 public void testQuarantineKeepsRawWithoutTrustedDeal()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);BrowserCandidate noise=new BrowserCandidate("101","https://www.vinted.it/items/101","Nintendo 3DS caricatore",1000,null,Collections.emptyMap(),Collections.emptyMap(),10);captures.commit(id,1,Collections.singletonList(noise),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));assertEquals("FILTERED",captures.snapshot(id).rows.get(0).state);assertEquals("Nintendo 3DS caricatore",captures.snapshot(id).rows.get(0).candidate.title);assertEquals(0,count("SELECT COUNT(*) FROM deals WHERE signature='vinted:101'"));}
 public void testSellerMetadataDoesNotWriteAbsentObservationColumn()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);BrowserCandidate rich=new BrowserCandidate("101","https://www.vinted.it/items/101","Azul gioco da tavolo",1000,null,Collections.singletonMap("sellerName","Mario"),Collections.emptyMap(),10);captures.commit(id,1,Collections.singletonList(rich),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));assertEquals(1,count("SELECT COUNT(*) FROM market_listings WHERE seller_name='Mario'"));assertEquals(1,count("SELECT COUNT(*) FROM observations WHERE signature='vinted:101'"));}
 public void testHiddenBggGameNotRevivedByNewListing()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));db.getWritableDatabase().execSQL("UPDATE games SET database_visible=0,filter_reason='USER_HIDDEN' WHERE bgg_id='230802'");captures.commit(id,1,Collections.singletonList(card("102",900,40)),40);assertTrue(committer.commit(captures.claim(8,50).get(0),analysis(),60));assertEquals(0,count("SELECT database_visible FROM games WHERE bgg_id='230802'"));assertEquals(0,count("SELECT COUNT(*) FROM deals WHERE vinted_item_id='102'"));}
 public void testChangedStickerCannotReuseOldBuyerTotal(){BrowserCandidate first=new BrowserCandidate("101","https://www.vinted.it/items/101","Azul",1000,1300,Collections.emptyMap(),Collections.emptyMap(),10);BrowserCandidate newer=new BrowserCandidate("101","https://www.vinted.it/items/101","Azul",2000,null,Collections.emptyMap(),Collections.emptyMap(),20);BrowserCandidate merged=first.merge(newer);assertEquals(Integer.valueOf(1300),merged.protectedPriceCents);assertNull(BrowserAnalysisCommitter.toCard(merged).protectedPrice);}
}
