package it.vintedaffari.app;
import android.test.AndroidTestCase;
import org.json.*;
public class BrowserCapturePacketTest extends AndroidTestCase {
 private JSONObject item()throws Exception{return new JSONObject().put("id","101").put("url","https://www.vinted.it/items/101").put("title","Azul").put("priceCents",1000).put("source","json");}
 private String packet(JSONObject item,long token)throws Exception{return new JSONObject().put("schema",1).put("seq",1).put("pageToken",token).put("page",new JSONObject().put("url","https://www.vinted.it/catalog").put("observed",1).put("withPrice",1)).put("items",new JSONArray().put(item)).toString();}
 public void testRetainsObservedMetadataWithSources()throws Exception{JSONObject item=item().put("description","Gioco da tavolo completo").put("sellerName","Mario").put("sellerId","555").put("photos",new JSONArray().put("https://images1.vinted.net/photo.jpg")).put("publication",new JSONObject().put("raw","2 ore fa").put("source","created_at"));BrowserCapturePacket parsed=BrowserCapturePacket.parse(packet(item,3),"https://www.vinted.it/catalog",3,10);BrowserCandidate c=parsed.candidates.get(0);assertEquals("Mario",c.metadata.get("sellerName"));assertEquals("Gioco da tavolo completo",c.metadata.get("description"));assertEquals("2 ore fa",c.metadata.get("publicationRaw"));assertEquals("created_at",c.provenance.get("publicationRaw"));assertTrue(c.metadata.get("photos").contains("images1.vinted.net"));}
 public void testProtectedPriceNeverBecomesSticker()throws Exception{JSONObject item=item();item.remove("priceCents");item.put("protectedPriceCents",1300);BrowserCandidate c=BrowserCapturePacket.parse(packet(item,3),"https://www.vinted.it/catalog",3,10).candidates.get(0);assertNull(c.priceCents);assertEquals(Integer.valueOf(1300),c.protectedPriceCents);assertFalse(c.elaborable());}
 public void testMetadataOverflowIsReported()throws Exception{JSONArray photos=new JSONArray().put("https://evil.example/photo.jpg");for(int i=0;i<13;i++)photos.put("https://images1.vinted.net/photo"+i+".jpg");JSONObject item=item().put("description",String.join("",java.util.Collections.nCopies(2001,"x"))).put("photos",photos);BrowserCapturePacket parsed=BrowserCapturePacket.parse(packet(item,3),"https://www.vinted.it/catalog",3,10);assertTrue(parsed.truncatedMetadata>0);assertTrue(parsed.rejectedPhotos>0);assertEquals(2000,parsed.candidates.get(0).metadata.get("description").length());assertEquals(12,new JSONArray(parsed.candidates.get(0).metadata.get("photos")).length());}
 public void testOldPageTokenRejected()throws Exception{try{BrowserCapturePacket.parse(packet(item(),2),"https://www.vinted.it/catalog",3,10);fail("Old page admitted");}catch(IllegalArgumentException expected){}}
 public void testIdentityMismatchRejectedIndividually()throws Exception{BrowserCapturePacket parsed=BrowserCapturePacket.parse(packet(item().put("url","https://www.vinted.it/items/102"),3),"https://www.vinted.it/catalog",3,10);assertTrue(parsed.candidates.isEmpty());assertEquals(1,parsed.rejectedItems);}
 public void testFractionalCentsStayUnknown()throws Exception{BrowserCandidate c=BrowserCapturePacket.parse(packet(item().put("priceCents",12.5),3),"https://www.vinted.it/catalog",3,10).candidates.get(0);assertNull(c.priceCents);}
}
