package it.vintedaffari.app;
import android.test.InstrumentationTestCase;
import android.content.Intent;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
public class BrowserControlsTest extends InstrumentationTestCase {
 private BrowserControlsTestActivity activity;private android.content.res.Configuration original;
 protected void setUp()throws Exception{super.setUp();Intent intent=new Intent(getInstrumentation().getTargetContext(),BrowserControlsTestActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);activity=(BrowserControlsTestActivity)getInstrumentation().startActivitySync(intent);getInstrumentation().waitForIdleSync();original=new android.content.res.Configuration(activity.getResources().getConfiguration());}
 protected void tearDown()throws Exception{getInstrumentation().runOnMainSync(()->{activity.getResources().updateConfiguration(original,activity.getResources().getDisplayMetrics());activity.finish();});super.tearDown();}
 private View find(View view,String description){if(description.equals(String.valueOf(view.getContentDescription())))return view;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++){View hit=find(((ViewGroup)view).getChildAt(i),description);if(hit!=null)return hit;}return null;}
 private void saveBitmap(android.graphics.Bitmap bitmap,String name)throws Exception{assertNotNull(bitmap);java.io.File directory=getInstrumentation().getTargetContext().getExternalFilesDir("browser-controls");assertTrue(directory!=null&&(directory.exists()||directory.mkdirs()));java.io.File saved=new java.io.File(directory,name+".png");try(java.io.FileOutputStream file=new java.io.FileOutputStream(saved)){assertTrue(bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,file));}finally{bitmap.recycle();}shell("mkdir -p /sdcard/Download/ludo-browser-controls");shell("cp "+saved.getAbsolutePath()+" /sdcard/Download/ludo-browser-controls/"+name+".png");assertTrue("Screenshot export missing",shell("ls /sdcard/Download/ludo-browser-controls/"+name+".png").contains(name+".png"));}
 private String shell(String command)throws Exception{try(android.os.ParcelFileDescriptor descriptor=getInstrumentation().getUiAutomation().executeShellCommand(command);java.io.InputStream output=new android.os.ParcelFileDescriptor.AutoCloseInputStream(descriptor)){java.io.ByteArrayOutputStream text=new java.io.ByteArrayOutputStream();byte[] bytes=new byte[256];int count;while((count=output.read(bytes))!=-1)text.write(bytes,0,count);return text.toString();}}
 private void screenshot(String name)throws Exception{saveBitmap(getInstrumentation().getUiAutomation().takeScreenshot(),name);}
 private String texts(View view){String out=view instanceof TextView?((TextView)view).getText().toString():"";if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)out+="\n"+texts(((ViewGroup)view).getChildAt(i));return out;}
 public void testNoPresetGamesAndDistinctNavigationTargets()throws Exception{screenshot("default");View root=activity.controls.view();assertFalse(texts(root).contains("Catan"));assertFalse(texts(root).contains("Azul"));assertNotNull(find(root,"Pagina precedente"));assertNotNull(find(root,"Pagina successiva"));assertNotNull(find(root,"Apri Motore"));View next=find(root,"Pagina successiva");assertTrue(next.getMeasuredWidth()>=48*activity.getResources().getDisplayMetrics().density);getInstrumentation().runOnMainSync(()->next.performClick());assertEquals(1,activity.navigationCount);assertTrue(activity.navigated.contains("page=3"));assertTrue(activity.navigated.contains("brand_ids%5B%5D=12"));assertTrue(activity.navigated.contains("price_to=30"));}
 public void testNarrowLargeFontLayoutHasNoOverflow()throws Exception{java.util.concurrent.atomic.AtomicReference<android.graphics.Bitmap> image=new java.util.concurrent.atomic.AtomicReference<>();getInstrumentation().runOnMainSync(()->{android.content.res.Configuration config=new android.content.res.Configuration(activity.getResources().getConfiguration());config.fontScale=1.5f;activity.getResources().updateConfiguration(config,activity.getResources().getDisplayMetrics());activity.rebuild();View root=activity.controls.view();int width=Math.round(320*activity.getResources().getDisplayMetrics().density);root.measure(View.MeasureSpec.makeMeasureSpec(width,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(0,View.MeasureSpec.UNSPECIFIED));root.layout(0,0,width,root.getMeasuredHeight());assertTrue(find(root,"Pagina successiva").getRight()<=width);assertTrue(find(root,"Pagina precedente").getLeft()>=0);android.graphics.Bitmap bitmap=android.graphics.Bitmap.createBitmap(width,root.getMeasuredHeight(),android.graphics.Bitmap.Config.ARGB_8888);root.draw(new android.graphics.Canvas(bitmap));image.set(bitmap);});saveBitmap(image.get(),"narrow-font-150");}
}
