package it.vintedaffari.app;
import android.test.InstrumentationTestCase;
import android.view.accessibility.AccessibilityNodeInfo;
import android.graphics.Bitmap;
import android.os.ParcelFileDescriptor;
import java.util.*;
/** Exercises the real :ui MainActivity across the production SQLite process boundary. */
public class BrowserMainUiTest extends InstrumentationTestCase {
 private String shell(String command)throws Exception{try(ParcelFileDescriptor fd=getInstrumentation().getUiAutomation().executeShellCommand(command);java.io.InputStream in=new ParcelFileDescriptor.AutoCloseInputStream(fd)){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] b=new byte[1024];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toString();}}
 private AccessibilityNodeInfo find(AccessibilityNodeInfo root,String target){if(root==null)return null;if(target.equals(String.valueOf(root.getText()))||target.equals(String.valueOf(root.getContentDescription())))return root;for(int i=0;i<root.getChildCount();i++){AccessibilityNodeInfo node=root.getChild(i);AccessibilityNodeInfo hit=find(node,target);if(hit!=null)return hit;if(node!=null)node.recycle();}return null;}
 private AccessibilityNodeInfo await(String target)throws Exception{long deadline=System.currentTimeMillis()+45_000;while(System.currentTimeMillis()<deadline){AccessibilityNodeInfo root=getInstrumentation().getUiAutomation().getRootInActiveWindow();AccessibilityNodeInfo hit=find(root,target);if(hit!=null)return hit;if(root!=null)root.recycle();Thread.sleep(200);}fail("Main UI did not show: "+target);return null;}
 private void screenshot()throws Exception{Bitmap image=getInstrumentation().getUiAutomation().takeScreenshot();assertNotNull(image);java.io.File file=new java.io.File(getInstrumentation().getTargetContext().getExternalFilesDir(null),"motore-browser.png");try(java.io.FileOutputStream out=new java.io.FileOutputStream(file)){assertTrue(image.compress(Bitmap.CompressFormat.PNG,100,out));}finally{image.recycle();}shell("mkdir -p /sdcard/Download/ludo-browser-controls");shell("cp "+file.getAbsolutePath()+" /sdcard/Download/ludo-browser-controls/motore-browser.png");assertTrue(shell("ls /sdcard/Download/ludo-browser-controls/motore-browser.png").contains("motore-browser.png"));}

 public void testRealMainShowsTheSelectedCaptureAndExactIncompleteRows()throws Exception{
  DealDatabase db=new DealDatabase(getInstrumentation().getTargetContext());long capture;try{BrowserCaptureStore store=new BrowserCaptureStore(db);capture=store.beginCapture("https://www.vinted.it/catalog/4881-board-games?search_text=Prova%20ricerca",System.currentTimeMillis());List<BrowserCandidate> rows=new ArrayList<>();for(int i=0;i<3;i++){String id=String.valueOf(9900000111L+i);rows.add(new BrowserCandidate(id,"https://www.vinted.it/items/"+id,"Annuncio prova "+i,null,null,Collections.emptyMap(),Collections.emptyMap(),System.currentTimeMillis()));}store.commit(capture,1,rows,System.currentTimeMillis());assertEquals(3,store.snapshot(capture).rows.size());}finally{db.close();}
  shell("pm grant it.vintedaffari.app android.permission.POST_NOTIFICATIONS");String launched=shell("am start -W -n it.vintedaffari.app/.MainActivity --ez open_engine true --el browser_capture_id "+capture);assertFalse(launched,launched.contains("Error:"));await("3 annunci acquisiti nella ricerca");await("Prova ricerca");AccessibilityNodeInfo root=getInstrumentation().getUiAutomation().getRootInActiveWindow();assertNull(find(root,"Non c’è ancora niente qui"));root.recycle();screenshot();AccessibilityNodeInfo group=await("Mostra Dati da completare, 3 annunci");assertTrue(group.performAction(AccessibilityNodeInfo.ACTION_CLICK));group.recycle();await("3 annunci · Prova ricerca");await("Vinted · 9900000111");await("Prezzo articolo non leggibile");
  // Back returns to this capture, then a second explicit intent selects it again.
  shell("input keyevent 4");await("3 annunci acquisiti nella ricerca");shell("am start -W -n it.vintedaffari.app/.MainActivity --ez open_engine true --el browser_capture_id "+capture);await("3 annunci acquisiti nella ricerca");
 }
}
