package it.vintedaffari.app;
import android.test.AndroidTestCase;
import android.database.Cursor;
import android.content.ContentValues;
import org.json.JSONObject;
import java.util.*;
public class BrowserAnalysisCommitterTest extends AndroidTestCase {
 private DealDatabase db;private BrowserCaptureStore captures;private MarketStore market;private BrowserAnalysisCommitter committer;
 protected void setUp()throws Exception{super.setUp();getContext().deleteDatabase("vinted_affari.db");db=new DealDatabase(getContext());captures=new BrowserCaptureStore(db);market=new MarketStore(getContext(),db);committer=new BrowserAnalysisCommitter(db,market,captures);}
 protected void tearDown()throws Exception{db.close();getContext().deleteDatabase("vinted_affari.db");super.tearDown();}
 private BrowserCandidate card(String id,int price,long at){return new BrowserCandidate(id,"https://www.vinted.it/items/"+id,"Azul gioco da tavolo",price,null,Collections.emptyMap(),Collections.emptyMap(),at);}
 private GameAnalysis analysis()throws Exception{return GameAnalysis.fromJson(new JSONObject().put("status","matched").put("game",new JSONObject().put("bggId","230802").put("name","Azul").put("averageRating",7.8)).put("deal",new JSONObject().put("totalCents",1600).put("benchmarkCents",2500).put("tier","good")));}

 private long count(String sql){try(Cursor c=db.getReadableDatabase().rawQuery(sql,null)){assertTrue(c.moveToFirst());return c.getLong(0);}}
 public void testDistinctIdsMaterializeAndNoRemoteMetadataJobs()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Arrays.asList(card("101",1000,10),card("102",1000,10)),10);for(BrowserCaptureStore.Claim claim:captures.claim(8,20))assertTrue(committer.commit(claim,analysis(),30));assertEquals(2,count("SELECT COUNT(*) FROM market_listings WHERE vinted_item_id IN ('101','102')"));assertEquals(2,count("SELECT COUNT(DISTINCT signature) FROM observations WHERE signature LIKE 'vinted:%'"));market.reconcileQueue();assertEquals(0,count("SELECT COUNT(*) FROM processing_jobs WHERE job_type IN ('VINTED_ENRICHMENT','VINTED_DEEP_ENRICHMENT')"));}
 public void testStaleResultDoesNotMaterialize()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);BrowserCaptureStore.Claim old=captures.claim(8,20).get(0);captures.commit(id,1,Collections.singletonList(card("101",900,30)),30);assertFalse(committer.commit(old,analysis(),40));assertEquals(0,count("SELECT COUNT(*) FROM market_listings WHERE vinted_item_id='101'"));}
 public void testHiddenExactListingNotReactivated()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));db.getWritableDatabase().execSQL("UPDATE market_listings SET lifecycle='USER_HIDDEN' WHERE vinted_item_id='101'");captures.commit(id,1,Collections.singletonList(card("101",900,40)),40);assertTrue(committer.commit(captures.claim(8,50).get(0),analysis(),60));assertEquals(1,count("SELECT COUNT(*) FROM market_listings WHERE vinted_item_id='101' AND lifecycle='USER_HIDDEN'"));}
 public void testPriceRevisionRetainsExactListing()throws Exception{long id=captures.beginCapture("https://www.vinted.it/catalog",10);captures.commit(id,1,Collections.singletonList(card("101",1000,10)),10);assertTrue(committer.commit(captures.claim(8,20).get(0),analysis(),30));long listing=count("SELECT id FROM market_listings WHERE vinted_item_id='101'");captures.commit(id,1,Collections.singletonList(card("101",900,40)),40);assertTrue(committer.commit(captures.claim(8,50).get(0),analysis(),60));assertEquals(listing,count("SELECT id FROM market_listings WHERE vinted_item_id='101'"));assertEquals(900,count("SELECT current_price_cents FROM market_listings WHERE vinted_item_id='101'"));}
}
